<?php/*
+----------------------------------------------------------------------------+
|     e107 website system - Language File.
|
|     $Revision: 1.1 $
|     $Date: 2006-04-15 20:48:49 $
|     $Author: e107coders $
+----------------------------------------------------------------------------+
*/
define("NWSLAN_1", "Notícia apagada.");define("NWSLAN_2", "Por favor seleccione a caixa para confirmar a remoção desta notícia.");define("NWSLAN_3", "Aínda não existem notícias.");define("NWSLAN_4", "Notícias existentes");define("NWSLAN_5", "Abrir editor HTML");define("NWSLAN_6", "Categoria");
define("NWSLAN_9", "Seleccione para confirmar");define("NWSLAN_10", "Sem categorias de notícias");define("NWSLAN_11", "Adicionar/editar categorias");define("NWSLAN_12", "Título");define("NWSLAN_13", "Conteúdo");define("NWSLAN_14", "Extensão");define("NWSLAN_15", "Comentários");define("NWSLAN_16", "Activado");define("NWSLAN_17", "Desactivado");define("NWSLAN_18", "Permitir o envio de comentários para esta notícia");define("NWSLAN_19", "Activação");
define("NWSLAN_21", "Activar entre");define("NWSLAN_22", "Visibilidade");
define("NWSLAN_24", "Prever novamente");define("NWSLAN_25", "Actualizar notícia na base de dados");define("NWSLAN_26", "Publicar notícia na base de dados");define("NWSLAN_27", "Prever");
define("NWSLAN_29", "Envio de notícias"); //News Post
define("NWSLAN_31", "Notícia");define("NWSLAN_32", "apagada");define("NWSLAN_33", "Categoria de notícias");define("NWSLAN_34", "Notícia submetida");define("NWSLAN_35", "Categoria de notícias gravada");define("NWSLAN_36", "Categoria de notícias actualizada");define("NWSLAN_37", "Tem a certeza que deseja apagar esta categoria?");define("NWSLAN_38", "Tem a certeza que deseja apagar esta submissão de notícia?");define("NWSLAN_39", "Tem a certeza que deseja apagar esta notícia?");define("NWSLAN_40", "Título");
define("NWSLAN_42", "Sem título");define("NWSLAN_43", "Sem notícias");define("NWSLAN_44", "Página inicial de notícias");define("NWSLAN_45", "Criar notícia");define("NWSLAN_46", "Categorias");define("NWSLAN_47", "Notícias submetidas");define("NWSLAN_48", "Opções de notícias");define("NWSLAN_49", "Submetido por");
define("NWSLAN_51", "Categorias de notícias existentes");define("NWSLAN_52", "Nome da categoria");define("NWSLAN_53", "Ícone da categoria");define("NWSLAN_54", "Ver imagens");define("NWSLAN_55", "Actualizar categoria de notícias");define("NWSLAN_56", "Criar categoria de notícias");define("NWSLAN_57", "Notícia");define("NWSLAN_58", "Publicar"); //Publicardefine("NWSLAN_59", "Sem submissões de notícias");define("NWSLAN_60", "Notícias submetidas");
define("NWSLAN_62", "Ir para pág.: ");define("NWSLAN_63", "Pesquisar notícias");
define("NWSLAN_66", "Transferir");define("NWSLAN_67", "Imagem");define("NWSLAN_68", "Ficheiro");define("NWSLAN_69", "Transferir uma imagem ou ficheiro para utilizar nesta notícia");define("NWSLAN_70", "A directoria de downloads ".e_FILE." não tem permissões de escrita, deverá alterar as suas permissões para 'CHMOD 777' antes de transferir os ficheiros.");define("NWSLAN_71", "A directoria de imagens de notícias ".e_IMAGE." não tem permissões de escrita, deverá alterar as suas permissões para 'CHMOD 777' antes de transferir as imagens.");define("NWSLAN_72", "Apenas mostrar notícias entre determinadas datas");define("NWSLAN_73", "Tipo de visualização");define("NWSLAN_74", "Escolha a forma como/onde as notícias são publicadas");define("NWSLAN_75", "Por defeito - publicar na página inicial");define("NWSLAN_76", "Apenas título - publicar na página inicial");define("NWSLAN_77", "Publicar noutros menus de notícias");define("NWSLAN_78", "Esta opção não está disponivel uma vez que a transferência de ficheiros para o seu servidor se encontra desactivada.");define("NWSLAN_79","Limpar formulário");define("NWSLAN_83","Extensão da notícia");define("NWSLAN_84","Escolha quais os utilizadores que podem visualizar a notícia");
define("NWSLAN_86", "Mostrar menu no rodapé com categorias de notícias"); //Show News-Category Footer Menudefine("NWSLAN_87", "Colunas de categorias de notícias?"); //News Category Columns?define("NWSLAN_88", "Notícias mostradas em cada página?");define("NWSLAN_89", "Gravar definições de notícias");define("NWSLAN_90", "Definições de notícias");define("NWSLAN_100", "Permitir a transferência de imagens na submissão de notícias");define("NWSLAN_101", "Redimensionamento automático das imagens submetidas");define("NWSLAN_102", "Largura em pixels<br /> ou deixe em branco para desactivar.");define("NWSLAN_103", "Publicar novamente"); //Re-postdefine("NWSLAN_104", "por");define("NWSLAN_105", "Seleccionar a caixa para ajustar a notícia para a data/hora actual");define("NWSLAN_106", "A submissão de notícias pode ser verificada por:"); //Submit-News maybe accessed by:define("NWSLAN_107", "Permitir editor WYSIWYG na página de submissão de notícias.");define("NWSLAN_111", "Mostrar cabeçalho com nova data"); //Show new date headerdefine("NWSLAN_112", "Ao seleccionar esta opção será mostrada uma caixa com a data em cima da notícia publicada noutro dia, útil para distinguir publicações em dias diferentes.");define("NWSLAN_113", "Utilizar modelos não comuns nos esquemas de notícias");define("NWSLAN_114", "Se o tema em utilização tem um modelo de notícias, deverá usá-lo em vez do modelo genérico");define("NWSLAN_115", "Notícias mostradas no arquivo?");define("NWSLAN_116", "Deverá actualizar as definições em primeiro lugar com as mudanças de notícias por página,  e posteriormente voltar a actualizar com as definições do arquivo de notícias (0 = desactivado).");define("NWSLAN_117", "Definir o título para o arquivo de notícias"); //set the title for the newsarchivedefine("NWSLAN_118", "Ver imagens");define("NWSLAN_119", "Definições gravadas");define("NWSLAN_120", "Texto mostrado no início de 'submeter notícias'");
define("LAN_NEWS_5", "Erro! - não foi possível actualizar a notícia na base de dados!");define("LAN_NEWS_6", "Notícia inserida na base de dados.");define("LAN_NEWS_7", "Erro! - não foi possível inserir a notícia na base de dados!!");define("LAN_NEWS_9", "'Mostrar apenas título' está ligado - <b>apenas serão mostrados os títulos das notícias</b>");define("LAN_NEWS_10", "Esta notícia está <b>inactiva</b> (não será mostrada na página principal). ");define("LAN_NEWS_11", "Esta notícia está <b>activa</b> (será mostrada na página principal). ");define("LAN_NEWS_12", "Os comentários encontram-se <b>ligados</b>.");define("LAN_NEWS_13", "Os comentários encontram-se <b>desligados</b>.");define("LAN_NEWS_14", "<br />Período de activação: ");define("LAN_NEWS_15", "Comprimento do conteúdo: ");define("LAN_NEWS_16", "b. Comprimento da extensão: ");define("LAN_NEWS_17", "b.");define("LAN_NEWS_18", "Informação"); //Infodefine("LAN_NEWS_19",  "Agora");define("LAN_NEWS_21", "Notícia actualizada na base de dados.");define("LAN_NEWS_22", "Miniatura");define("LAN_NEWS_23", "Escolha uma imagem miniatura / ícone para esta notícia");define("LAN_NEWS_24", "Imagem + auto-miniatura");define("LAN_NEWS_25", "Tamanho da auto-miniatura");define("LAN_NEWS_26", "Adicionar novo ficheiro"); //add new uploaddefine("LAN_NEWS_27", "Sumário");define("LAN_NEWS_28", "Fixo");define("LAN_NEWS_29", "Defina se esta notícia aparecerá fixa");define("LAN_NEWS_30", "Ao seleccionar fará com que a notícia seja mostrada em cima de todas as outras");define("LAN_NEWS_31", "Esta notícia está <b>fixa</b> (será mostrada em cima de todas as outras). ");define("LAN_NEWS_32", "Data/hora");define("LAN_NEWS_33", "Alterar a data/hora desta notícia.");define("LAN_NEWS_34", "Referência");define("LAN_NEWS_35", "Adicionar URL's de referência");define("LAN_NEWS_36", "<b>Ping de referência</b> (eviar um ping para todos os URLs desta notícia)");define("LAN_NEWS_37", "<b>URL's de referência:</b> (um URL por linha)");define("LAN_NEWS_38", "Inserir imagens");define("LAN_NEWS_39", "Clique no ficheiro para inserí-lo na posição actual do cursor");define("LAN_NEWS_40", "Inserir links de downloads");define("LAN_NEWS_41", "Miniatura / Ícone");define("LAN_NEWS_42", "Ficheiros");define("LAN_NEWS_43", "(não existem imagens em /e107_images/newspost_images)");define("LAN_NEWS_44", "As referências não estão activadas.");define("LAN_NEWS_45", "ID");define("LAN_NEWS_46", "A notícia não foi actualizada uma vez que não foram detectadas alterações.");
?>