// variables langue FR

tinyMCE.addToLang('media',{
title : 'Insertion / édition d\'un média',
desc : 'Insertion / édition d\'un média',
general : 'Général',
advanced : 'Avancé',
file : 'Fichier',
list : 'Liste',
size : 'Dimensions',
preview : 'Prévisualisation',
constrain_proportions : 'Forcer les proportions',
type : 'Type',
id : 'Id',
name : 'Nom',
class_name : 'Style',
vspace : 'Espacement vertical',
hspace : 'Espacement horizontal',
play : 'Lecture automatique',
loop : 'En boucle',
menu : 'Montrer le menu',
quality : 'Qualité',
scale : 'Echelle',
align : 'Alignement',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : 'Arrière-plan',
base : 'Base',
flashvars : 'Variables Flash',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Cache',
hidden : 'Caché',
controller : 'Contrôleur',
kioskmode : 'Mode Kiosque',
playeveryframe : 'Jouer toutes les images',
targetcache : 'Cache cible',
correction : 'Pas de correction',
enablejavascript : 'Autoriser JavaScript',
starttime : 'Point de départ',
endtime : 'Point d\'arrêt',
href : 'Href',
qtsrcchokespeed : 'Choke speed',
target : 'Cible',
volume : 'Volume',
autostart : 'Démarrage automatique',
enabled : 'Activé',
fullscreen : 'Plein écran',
invokeurls : 'Invoke URLs',
mute : 'Silence',
stretchtofit : 'Compresser pour ajuster',
windowlessvideo : 'Vidéo sans fenêtre',
balance : 'Balance',
baseurl : 'Base URL',
captioningid : 'Captioning id',
currentmarker : 'Marqueur courant',
currentposition : 'Position courante',
defaultframe : 'Cadre par défaut',
playcount : 'Compteur',
rate : 'Taux',
uimode : 'UI Mode',
flash_options : 'Options Flash',
qt_options : 'Options Quicktime',
wmp_options : 'Options Windows media player',
rmp_options : 'Options Real media player',
shockwave_options : 'Options Shockwave',
autogotourl : 'Auto goto URL',
center : 'Centrer',
imagestatus : 'Statut de l\'image',
maintainaspect : 'Maintenir l\'aspect',
nojava : 'Java interdit',
prefetch : 'Prefetch',
shuffle : 'Aléatoire',
console : 'Console',
numloop : 'Nombre de boucles',
controls : 'Contrôles',
scriptcallbacks : 'Script callbacks',
swstretchstyle : 'Style d\'affichage',
swstretchhalign : 'Alignement horizontal',
swstretchvalign : 'Alignement vertical',
sound : 'Son',
progress : 'Progression',
qtsrc : 'QT Src',
qt_stream_warn : 'Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..'
});
