// UK lang variables

tinyMCE.addToLang('media',{
title : 'Beágyazott média beillesztés / módosítás',
desc : 'Beágyazott média beillesztés / módosítás',
general : 'Általános',
advanced : 'Haladó',
file : 'File',
list : 'Lista',
size : 'Méretek',
preview : 'Elõnézet',
constrain_proportions : 'Méret korlátozások',
type : 'Típus',
id : 'Id',
name : 'Név',
class_name : 'Csoport',
vspace : 'V-Space',
hspace : 'H-Space',
play : 'Autómatikus lejátszás',
loop : 'Ismétlés',
menu : 'Menü megjelenítése',
quality : 'Minõség',
scale : 'Méretarány',
align : 'Igazítás',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : 'Háttér',
base : 'Bázis',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Cache',
hidden : 'Eérejtés',
controller : 'Vezérlõ panel',
kioskmode : 'Kiosk mode',
playeveryframe : 'Minden képkocka lejátszása',
targetcache : 'Cél cache',
correction : 'Nincs korrekció',
enablejavascript : 'JavaScript engedélyezése',
starttime : 'Indítási idõ',
endtime : 'Befejezési idõ',
href : 'Href',
qtsrcchokespeed : 'Sebesség csökkentése',
target : 'Cél',
volume : 'Hangerõ',
autostart : 'Autómatikus indítás',
enabled : 'Engedélyezve',
fullscreen : 'Teljes képernyõ',
invokeurls : 'Invoke URLs',
mute : 'Némítás',
stretchtofit : 'Megfelelõ méretre igazítás',
windowlessvideo : 'Windowless video',
balance : 'Balansz',
baseurl : 'Bázis URL',
captioningid : 'id felíratozás',
currentmarker : 'Jelenlegi jelzés',
currentposition : 'Jelenlegi helyzet',
defaultframe : 'Alapértelmezett képkocka',
playcount : 'Számlálás lejátszása',
rate : 'Értékelés',
uimode : 'UI Mód',
flash_options : 'Flash beállítások',
qt_options : 'Quicktime beállítások',
wmp_options : 'Windows media player beállítások',
rmp_options : 'Real media player beállítások',
shockwave_options : 'Shockwave beállítások',
autogotourl : 'Autómatikus tovább URL',
center : 'Közép',
imagestatus : 'Kép státusz',
maintainaspect : 'Kezelési szempont',
nojava : 'Nincs java',
prefetch : 'Prefetch',
shuffle : 'Keverés',
console : 'Konzol',
numloop : 'Ismétlések száma',
controls : 'Vezérlés',
scriptcallbacks : 'Script visszahívás',
swstretchstyle : 'Stretch stílus',
swstretchhalign : 'Stretch H-Align',
swstretchvalign : 'Stretch V-Align',
sound : 'Zene',
progress : 'Folyamat',
qtsrc : 'QT Src',
qt_stream_warn : 'Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..'
});
