/*
+-----------------------------------------------------------------------------+
|     e107 website system - Language File
+-----------------------------------------------------------------------------+
|     Spolszczenie systemu e107
|     e107 Polish Team
|     Polskie wsparcie: http://e107pl.org
|
|     $Revision: 1.1 $
|     $Date: 2009-09-13 10:26:32 $
|     $Author: marcelis_pl $
|     $Source: /cvs_backup/e107_langpacks/e107_handlers/tiny_mce/plugins/media/langs/pl_dlg.js,v $
+-----------------------------------------------------------------------------+
|     Zgodne z: /e107_handlers/tiny_mce/plugins/media/langs/pl_dlg.js rev. 1.1
+-----------------------------------------------------------------------------+
*/


tinyMCE.addI18n('pl.media_dlg',{
title:"Wstaw/Edytuj wbudowane media",
general:"G\u0142\u00F3wny",
advanced:"Zaawansowany",
file:"Plik/URL",
list:"Lista",
size:"Wymiary",
preview:"Podgl\u0105d",
constrain_proportions:"Zachowaj proporcje",
type:"Typ",
id:"Id",
name:"Nazwa",
class_name:"Klasa",
vspace:"Marg.-V",
hspace:"Marg.-H",
play:"Autoodtwarzanie",
loop:"Zap\u0119tlenie",
menu:"Poka\u017C menu",
quality:"Jako\u015B\u0107",
scale:"Skala",
align:"Wyr\u00F3wnaj",
salign:"Wyr\u00F3w. (SAlign)",
wmode:"Tryb okna",
bgcolor:"T\u0142o",
base:"Baza",
flashvars:"Parametr flashvars",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Ukryty",
controller:"Menu sterowania",
kioskmode:"Tryb bez menu",
playeveryframe:"Odtwarzaj ka\u017Cd\u0105 ramk\u0119",
targetcache:"Przechowuj filmy zew.",
correction:"Bez korekcji",
enablejavascript:"W\u0142\u0105cz JavaScript",
starttime:"Czas rozp.",
endtime:"Czas zako.",
href:"Href",
qtsrcchokespeed:"Szybkoœæ danych",
target:"Kom\u00F3rka",
volume:"G\u0142o\u015Bno\u015B\u0107",
autostart:"Auto start",
enabled:"Aktywne",
fullscreen:"Pe\u0142ny ekran",
invokeurls:"Odwo\u0142aj si\u0119 do URLs",
mute:"Wycisz",
stretchtofit:"Rozci\u0105gnij aby dopasowa\u0107",
windowlessvideo:"Tryb windowless",
balance:"Balans",
baseurl:"Bazowy URL",
captioningid:"Id opisu",
currentmarker:"Wska\u017Anik",
currentposition:"Aktualna pozycja",
defaultframe:"Domy\u015Blna ramka",
playcount:"Ilo\u015B\u0107 powt\u00F3rze\u0144",
rate:"Tempo",
uimode:"Param. uiMode",
flash_options:"Opcje plik\u00F3dw Flash",
qt_options:"Opcje plik\u00F3dw Quicktime",
wmp_options:"Windows media player opcje",
rmp_options:"Opcje odtwarzacza Real Media",
shockwave_options:"Opcje Shockwave",
autogotourl:"Auto-przej\u015Bcie do URL",
center:"Wy\u015Brodkowanie",
imagestatus:"Status obrazka",
maintainaspect:"Zachowaj proporcje",
nojava:"Bez Javy VM",
prefetch:"Wst\u0119pne \u0142adowanie",
shuffle:"Odtwarzaj losowo",
console:"Konsola",
numloop:"Ilo\u015B\u0107 p\u0119tli",
controls:"Menu kontrolne",
scriptcallbacks:"Skrypt odwo\u0142ania",
swstretchstyle:"Styl dopasowania",
swstretchhalign:"Dopas. wyr\u00F3wnania-H",
swstretchvalign:"Dopas. wyr\u00F3wnania-V",
sound:"D\u017Awi\u0119k",
progress:"Post\u0119p",
qtsrc:"\u0179r\u00F3d\u0142o QT",
qt_stream_warn:"\u0179r\u00F3d\u0142o strumienia protoko\u0142u RTSP powinno zosta\u0107 dodane do pola \'\u0179r\u00F3d\u0142o QT\' w zak\u0142adce \'Zaawansowane\'.\nNale\u017Cy r\u00F3wnie\u017C doda\u0107 wersj\u0119 bez streamingu do pola \'\u0179r\u00F3d\u0142o\'..",
align_top:"G\u00F3ra",
align_right:"Prawo",
align_bottom:"D\u00F3\u0142",
align_left:"Lewo",
align_center:"\u015Arodek",
align_top_left:"G\u00F3rny lewy",
align_top_right:"G\u00F3rny prawy",
align_bottom_left:"Dolny lewy",
align_bottom_right:"Dolny prawy",
flv_options:"Opcje wideo Flash",
flv_scalemode:"Scale mode",
flv_buffer:"Bufor",
flv_startimage:"Grafika pocz\u0105tkowa",
flv_starttime:"Czas rozp.",
flv_defaultvolume:"Domy\u015Blna g³o\u015Bno\u015B\u0107",
flv_hiddengui:"Ukryte GUI",
flv_autostart:"Auto start",
flv_loop:"P\u0119tla",
flv_showscalemodes:"Show scale modes",
flv_smoothvideo:"Smooth video",
flv_jscallback:"JS Callback"
});