// RU lang variables UTF-8

tinyMCE.addI18n('ru.media_dlg',{
title:"Вставить/редактировать медиа-объект",
general:"Общие",
advanced:"Дополнительные",
file:"Файл/адрес",
list:"Список",
size:"Размеры",
preview:"Предварительный просмотр<",
constrain_proportions:"Сохранять пропорции",
type:"Тип",
id:"Идентификатор",
name:"Название",
class_name:"Класс",
vspace:"Вертикальный отступ",
hspace:"Горизонтальный отступ",
play:"Проигрывать автоматически",
loop:"Зациклить",
menu:"Отобразить меню",
quality:"Качество",
scale:"Масштаб",
align:"Выравнивание",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Фон",
base:"Основа",
flashvars:"Переменные Flash",
liveconnect:"SWLiveConnect",
autohref:"Авто ссылка",
cache:"Кеш",
hidden:"Скрытое",
controller:"Контроллер",
kioskmode:"Режим киоска",
playeveryframe:"Проигрывать каждый кадр",
targetcache:"Целевой кеш",
correction:"Без коррекции",
enablejavascript:"Включить JavaScript",
starttime:"Время начала",
endtime:"Время окончания",
href:"Ссылка",
qtsrcchokespeed:"Уменьшить скорость",
target:"Цель",
volume:"Громкость",
autostart:"Авто запуск",
enabled:"Включено",
fullscreen:"Полный экран",
invokeurls:"Активизировать адреса",
mute:"Тишина",
stretchtofit:"Растянуть до размеров",
windowlessvideo:"Безоконное видео",
balance:"Безоконное видео",
baseurl:"Базовый адрес",
captioningid:"Ид ввода субтитров",
currentmarker:"Текущая отметка",
currentposition:"Текущая позиция",
defaultframe:"Кадр по умолчанию",
playcount:"Счетчик",
rate:"Частота",
uimode:"Режим интерфейса",
flash_options:"Опции Flash",
qt_options:"Опции Quicktime",
wmp_options:"Опции проигрывателя Windows media",
rmp_options:"Опции проигрывателя Real media",
shockwave_options:"Опции Shockwave",
autogotourl:"Адрес автоперехода",
center:"Центр",
imagestatus:"Статус изображения",
maintainaspect:"Поддерживать отношение",
nojava:"Без java",
prefetch:"Упреждение",
shuffle:"Перемешать",
console:"Консоль",
numloop:"Количество циклов",
controls:"Управления",
scriptcallbacks:"Обратный вызов скрипта",
swstretchstyle:"Стиль растяжения",
swstretchhalign:"'Г-Выравнивание растяжения",
swstretchvalign:"'В-Выравнивание растяжения",
sound:"Звук",
progress:"Прогресс",
qtsrc:"QT Исх",
qt_stream_warn:"Потоковые rtsp ресурсы должны быть добавлены в поле QT Исх в дополнительную графу.\nВы также должны добавить не потоковую версию в поле Исх..",
align_top:"Вверх",
align_right:"Вправо",
align_bottom:"Вниз",
align_left:"Влево",
align_center:"По центру",
align_top_left:"В верхний левый",
align_top_right:"В верхний правый",
align_bottom_left:"В левый нижний",
align_bottom_right:"В правый нижний",
flv_options:"Опции Flash видео",
flv_scalemode:"Режим масштабирования",
flv_buffer:"Буфер",
flv_startimage:"Начальное изображение",
flv_starttime:"Время начала",
flv_defaultvolume:"Громкость по-умолчанию",
flv_hiddengui:"Спрятать элементы интерфейса",
flv_autostart:"Автозапуск",
flv_loop:"Цикл",
flv_showscalemodes:"Показать режимы масштабирования",
flv_smoothvideo:"Сглаживание",
flv_jscallback:"Обратный вызов JS"
});