<?php
/*
+---------------------------------------------------------------+
|	e107 website system
|	/e107_config.php
|
|	©Steve Dunstan 2001-2002
|	http://e107.org
|	jalist@e107.org
|
|	Released under the terms and conditions of the
|	GNU General Public License (http://gnu.org).
+---------------------------------------------------------------+

This file has been generated by the installation script.

*/

$mySQLserver = "localhost";
$mySQLuser = "stevedunstan";
$mySQLpassword = "foxtrot";
$mySQLdefaultdb = "e107_613";
$mySQLprefix = "e107_";

define("e_HTTP", "/v0.613/");

?>