<?php
/*
+---------------------------------------------------------------+
|        e107 website system
|        /e107_config.php
|
|        ©Steve Dunstan 2001-2002
|        http://e107.org
|        jalist@@e107.org
|
|        Released under the terms and conditions of the
|        GNU General Public License (http://gnu.org).
+---------------------------------------------------------------+

This file has been generated by the installation script.

*/

$mySQLserver = "localhost";
$mySQLuser = "stevedunstan";
$mySQLpassword = "28uswlab";
$mySQLdefaultdb = "e107v07";
$mySQLprefix = "e107_";

$ADMIN_DIRECTORY = "e107_admin/";
$FILES_DIRECTORY = "e107_files/";
$IMAGES_DIRECTORY = "e107_images/";
$THEMES_DIRECTORY = "e107_themes/";
$PLUGINS_DIRECTORY = "e107_plugins/";
$HANDLERS_DIRECTORY = "e107_handlers/";
$LANGUAGES_DIRECTORY = "e107_languages/";
$HELP_DIRECTORY = "e107_docs/help/";
$DOWNLOADS_DIRECTORY =  "e107_files/downloads/";
// $DOWNLOADS_DIRECTORY =  "<fullpath>/downloads/";
// eg. $DOWNLOADS_DIRECTORY =  "/home/downloads/";

define("e_HTTP", "/e107_0.7/");

?>