<?php
/*
+ ----------------------------------------------------------------------------+
|     e107 website system
|
|     ©Steve Dunstan 2001-2002
|     http://e107.org
|     jalist@e107.org
|
|     Released under the terms and conditions of the
|     GNU General Public License (http://gnu.org).
|
|     $Source: /cvs_backup/e107_0.7/sitemap.php,v $
|     $Revision: 1.2 $
|     $Date: 2004-10-07 14:45:21 $
|     $Author: loloirie $
+----------------------------------------------------------------------------+
*/

///////////////////
// If you need to add some links, do NOT edit this file
// BUT Edit e107_handlers/sitemap/sitemap_custom.php"
///////////////////
require_once("class2.php");
require_once(HEADERF);
$sql2 = new db;

if(file_exists(THEME."images/extand_ico.png")){
        define("SM_ICO_EXP","<img onclick=\"if(this.src.indexOf('".THEME."images/extand_ico.png')!=-1){this.src='".THEME."images/extand2_ico.png'}else{this.src='".THEME."images/extand_ico.png'}\" class='icoexp' src='".THEME."images/extand_ico.png' style='border: 0px; width: 11px; height: 11px;' alt=\"\" />");
        define("SM_ICO_URL",THEME."images/extand_ico.png");
}else{
        define("SM_ICO_EXP","<img onclick=\"if(this.src.indexOf('".e_IMAGE."generic/extand_ico.png')!=-1){this.src='".e_IMAGE."generic/extand2_ico.png'}else{this.src='".e_IMAGE."generic/extand_ico.png'}\" class='icoexp' src='".e_IMAGE."generic/extand_ico.png' style='border: 0px; width: 11px; height: 11px;' alt=\"\" />");
        define("SM_ICO_URL",e_IMAGE."generic/extand_ico.png");
}
if(file_exists(THEME."images/extand2_ico.png")){
        define("SM_ICO_URL2",THEME."images/extand2_ico.png");
}else{
        define("SM_ICO_URL2",e_IMAGE."generic/extand2_ico.png");
}


$caption = LANSM_1. " ".SITENAME." <b>".SITEURL."</b>";
$text = "\n\n
<script type='text/javascript' src='".e_HANDLER."javascript/sitemap.php' ></script>
\n\n";



// Help
$text .= "<p>\n<a href=\"#\" onclick=\"ejs_func_todo=ejs_expandall('cats',ejs_func_todo,'subcats');ejs_func_todo2=ejs_expandpics('icoexp',ejs_func_todo2,'".SM_ICO_URL."','".SM_ICO_URL2."');\" > ".LANSM_7."</a> ".LANSM_31." <img src='".e_IMAGE."generic/extand_ico.png' style='border: 0px; width: 11px; height: 11px;' alt=\"\" /> ".LANSM_41."</p>\n";


$text .= "<br /><br />\n
<p><b>".PAGE_NAME."</b></p>\n
<br /><br />\n\n";

// "Home" pages
$text .= "<p class='caption2' style='text-align: left;' >\n
<img src='".THEME."images/bullet2.gif' alt='bullet' /> <a class=\"sitemap2\" href=\"".SITEURL."\" >".LANSM_2."</a> <b class='smalltext' >".LANSM_3."</b>\n
</p><br />\n";

// News
if($sql -> db_Select("news","news_id")){
        require_once(e_HANDLER."sitemap/sitemap_news.php");
        $text .= sm_news();
}

// Links
if($sql -> db_Select("links","link_id","link_category!='1'")){
        require_once(e_HANDLER."sitemap/sitemap_links.php");
        $text .= sm_links();
}

// Forums
if($sql -> db_Select("forum","forum_id")){
        require_once(e_HANDLER."sitemap/sitemap_forums.php");
        $text .= sm_forums();
}

// Downloads
if($sql -> db_Select("download_category","download_category_id")){
        require_once(e_HANDLER."sitemap/sitemap_downloads.php");
        $text .= sm_downloads();
}

// Articles
if($sql -> db_Select("content","content_id","content_type='6' OR (content_type='0' AND content_parent='0')")){
        require_once(e_HANDLER."sitemap/sitemap_articles.php");
        $text .= sm_articles();
}

// Reviews
if($sql -> db_Select("content","content_id","content_type='10' OR (content_type='3' AND content_parent='0')")){
        require_once(e_HANDLER."sitemap/sitemap_reviews.php");
        $text .= sm_reviews();
}

// Content
if($sql -> db_Select("content","content_id","content_type='1'")){
        require_once(e_HANDLER."sitemap/sitemap_content.php");
        $text .= sm_content();
}

// Members
require_once(e_HANDLER."sitemap/sitemap_members.php");
$text .= sm_members();

// Stats
require_once(e_HANDLER."sitemap/sitemap_stats.php");
$text .= sm_stats();

// Plugins
require_once(e_HANDLER."sitemap/sitemap_plugin.php");
$text .= sm_plugins();

// Other pages
require_once(e_HANDLER."sitemap/sitemap_custom.php");
$text .= sm_custom();


// Display Sitemap
$ns -> tablerender($caption, $text);



require_once(FOOTERF);
?>