<?php
/*
+---------------------------------------------------------------+
|	e107 website system
|	/upgrade.php
|
|	©Steve Dunstan 2001-2002
|	http://e107.org
|	jalist@e107.org
|
|	Released under the terms and conditions of the
|	GNU General Public License (http://gnu.org).
+---------------------------------------------------------------+
*/
define("VERSION", "5.3b5");

require_once("config.php");

$sql = new db;
$sql -> db_SetErrorReporting(FALSE);
define("MUSER", $mySQLprefix);
$sql -> db_Connect($mySQLserver, $mySQLuser, $mySQLpassword, $mySQLdefaultdb);

echo "<?xml version=\"1.0\" encoding=\"iso-8859-1\" ?>\n";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><e107 upgrade></title>
<link rel="stylesheet" href="themes/e107/style.css" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta http-equiv="content-style-type" content="text/css" />
</head>
<body>
<div style="text-align:center">
<table style="width:100%" cellspacing="0" cellpadding="0">
<tr>
<td style="width:66%; background-color:#E2E2E2; text-align:left\">
<img src="themes/shared/logo.png" alt="Logo" />
</td>
<td style="background-color:#E2E2E2; text-align:right; vertical-align:bottom" class="smalltext">
©Steve Dunstan 2002. See gpl.txt for licence details.
</td>
<tr> 
<td colspan="2" style="background-color:#000; vertical-align: top;"></td>
</tr>
<tr>
<tr> 
<td colspan="2" style="background-color:#ccc; vertical-align: top;">
<div class="mediumtext">&nbsp;Upgrade</div>
</td>
</tr>
<tr> 
<td colspan="2" style="background-color:#000; vertical-align: top;"></td>
</tr>
<tr>
<td colspan="2" style="vertical-align: top; text-align:center"><br />
<table style="width:66%" class="fborder">
<tr>
<td class="installb">
<br /><img src="themes/e107/images/installlogo.png" alt="" /><br /><span class="smalltext">php/mySQL website system</span><br />
<br />
<span class="installe">e107 upgrade .:. v5.x to v5.4</span>
<br /><br />

<?php

if(IsSet($_POST['usubmit'])){
	if(!$sql -> db_Select("admin", "*", "admin_name='".$_POST['a_name']."' AND admin_password='".md5($_POST['a_password'])."' ")){
		echo "<span class=\"installh\">Administrator not found in database - script halted.</span><br /><br />";
	}else{
		$row = $sql -> db_Fetch();
		extract($row);
		if($admin_permissions != 0){
			echo "<span class=\"installh\">Administrator not found in database - script halted.</span><br /><br />";
		}else{
			echo "<span class=\"installh\">Main site administrator found, click button to begin upgrade process.</span><br /><br />
			<form method=\"post\" action=\"".$_SERVER['PHP_SELF']."\">
			<input type=\"checkbox\" name=\"confirm\" value=\"1\" /> Yes, I have backed up my e107 database and any other relevant content (please tick to confirm)<br /><br />
			<input class=\"button\" type=\"submit\" name=\"csubmit\" value=\"Begin Upgrade\" />
			</form><br /><br />";
		}
	}
	echo "</td></tr></table></body></html>";
	exit;
}

if(IsSet($_POST['csubmit'])){
	if(!$_POST['confirm']){
		echo "<span class=\"installh\">Please back up your information before running the upgrade procedure. Script halted.</span><br /><br />";
		echo "</td></tr></table></body></html>";
		exit;
	}else{
		$fpath = str_replace(strrchr($_SERVER['PHP_SELF'], "/"), "", $_SERVER['PHP_SELF'])."/";
 
$data = chr(60)."?php\n".
chr(47)."*\n+---------------------------------------------------------------+\n|	e107 website system\n|	/config.php\n|\n|	©Steve Dunstan 2001-2002\n|	http://e107.org\n|	jalist@e107.org\n|\n|	Released under the terms and conditions of the\n|	GNU General Public License (http://gnu.org).\n+---------------------------------------------------------------+\n\nThis file has been generated by the installation script.\n\n*".
chr(47)."\n\n".
chr(36)."mySQLserver = ".chr(34).$mySQLserver.chr(34).";\n".
chr(36)."mySQLuser = ".chr(34).$mySQLuser.chr(34).";\n".
chr(36)."mySQLpassword = ".chr(34).$mySQLpassword.chr(34).";\n".
chr(36)."mySQLdefaultdb = ".chr(34).$mySQLdefaultdb.chr(34).";\n".
chr(36)."mySQLprefix = ".chr(34).$mySQLprefix.chr(34).";\n\n".
chr(47).chr(47)."define(".chr(34)."MQ".chr(34).", TRUE);\ndefine(".chr(34)."e_HTTP".chr(34).", ".chr(34).$fpath.chr(34).");\n\n?".chr(62);

		$fp = @fopen("config.php","w");
		if(!@fwrite($fp, $data)){
			$text =  "<span class=\"installe\">* Error *</span><br /><br />Was unable to write config.php to server, the file probably doesn't have the correct permissions set. Try chmodding config.php to 666 or 777 and re-running script. Script halted.";
		}else{
			fclose($fp);
			$text = "<span class=\"installh\">Updated  config file successfully written to server.<br />Commencing table updates ...</span><br /><br />";

			$str = update_tables($mySQLprefix);
			echo $str;
			if(eregi("ERROR", $str)){
				echo "<br /><span class=\"installe\">* Error *</span><br /><br />An error was encountered while running the upgrade process.";
			}else{
				echo "<span class=\"installe\">* Success! *</span><br /><br />Upgrade completed successfully, you are now running version v5.4b1.</span><br /><br /><a href=\"index.php\">Click here to go to your front page</a><br />";
			}
		}
		echo "</td></tr></table></body></html>";
		exit;
	}
}

?>
This script will upgrade your e107 base install from version v5.x to v5.4b1. Please note that while every attempt has been made to make this process as failsafe as possible, it is still highly recommended that you <b>backup your e107 mySQL database and any other site content that would be hard to replace if lost.</b> Please also make a backup of your <b>config.php</b> file as this will be altered by the upgrade process.<br /><br />
Your config.php will need write status so before beginning please ensure it's file permissions are set to 666 or 777 (CHMOD 666 or CHMOD 777).<br /><br />
Please enter your main administrator name and password to begin upgrade.<br /><br />
<?php

echo "<form method=\"post\" action=\"".$_SERVER['PHP_SELF']."\">
<table style=\"width:95%\">
<tr>
<td style=\"width:30%\" class=\"mediumtext\">Main administrator name:</td>
<td style=\"width:70%\">
<input class=\"tbox\" type=\"text\" name=\"a_name\" size=\"60\" value=\"\" maxlength=\"100\" />
</td>
</tr>
<tr>
<td style=\"width:30%\" class=\"mediumtext\">Main administrator Password:</td>
<td style=\"width:70%\">
<input class=\"tbox\" type=\"password\" name=\"a_password\" size=\"60\" value=\"\" maxlength=\"100\" />
</td>
</tr>

<tr>
<td colspan=\"2\" style=\"text-align:center\">
<br />
<input class=\"button\" type=\"submit\" name=\"usubmit\" value=\"Submit\" />
</td>
</tr>
</table>
</form>
</body>
</html>";


function update_tables($mySQLprefix){
	global $pref;
	if(mysql_query("ALTER TABLE `".$mySQLprefix."news` CHANGE `news_author` `news_author` INT UNSIGNED DEFAULT '0' NOT NULL ")){
		if(mysql_query("ALTER TABLE `".$mySQLprefix."news` ADD `news_start` INT UNSIGNED NOT NULL ,ADD `news_end` INT UNSIGNED NOT NULL ,ADD `news_active` TINYINT( 1 ) UNSIGNED NOT NULL ;")){
			$str = "<b>News</b> table updated.<br />";
		}else{
			$str = "<b>ERROR!</b> - Could not update news table.<br />";
			return($str);
		}
	}

	if(mysql_query("ALTER TABLE `".$mySQLprefix."user` ADD `user_login` VARCHAR( 100 ) NOT NULL ,ADD `user_class` TEXT NOT NULL , ADD `user_perms` TEXT NOT NULL ,ADD `user_realm` TEXT NOT NULL ,ADD `user_pwchange` TINYINT( 1 ) UNSIGNED NOT NULL ;")){
		$str .= "<b>User</b> table updated.<br />";
	}else{
		$str .= "<b>ERROR!</b> - Could not update user table.<br />";
		return($str);
	}

	if(mysql_query("ALTER TABLE `".$mySQLprefix."content` CHANGE `content_parent` `content_summary` TEXT NOT NULL")){
		$str .= "<b>Content</b> table updated.<br />";
	}else{
		$str .= "<b>ERROR!</b> - Could not update content table.<br />";
		return($str);
	}

	if(mysql_query("CREATE TABLE `".$mySQLprefix."core` (`e107_name` VARCHAR( 20 ) NOT NULL ,`e107_value` TEXT NOT NULL ,PRIMARY KEY ( `e107_name` ) );")){
		$str .= "<b>Core</b> table created.<br />";
	}else{
		$str .= "<b>ERROR!</b> - Could not create core table.<br />";
		return($str);
	}

	if(mysql_query("ALTER TABLE `".$mySQLprefix."forum` ADD `forum_class` VARCHAR( 100 ) NOT NULL")){
		$str .= "<b>Forum</b> table updated.<br />";
	}else{
		$str .= "<b>ERROR!</b> - Could not update forum table.<br />";
		return($str);
	}

	if(mysql_query("CREATE TABLE ".$mySQLprefix."tmp (tmp_ip varchar(20) NOT NULL default '',tmp_time int(10) unsigned NOT NULL default '0',tmp_info text NOT NULL)")){
		$str .= "<b>tmp</b> table created.<br />";
	}else{
		$str .= "<b>ERROR!</b> - Could not create tmp table.<br />";
		return($str);
	}

	if(mysql_query("ALTER TABLE `".$mySQLprefix."links` ADD `link_open` TINYINT( 1 ) UNSIGNED NOT NULL ")){
		$str .= "<b>Links</b> table updated.<br />";
	}else{
		$str .= "<b>ERROR!</b> - Could not update links table.<br />";
		return($str);
	}

	$str .= "<br />All tables created / updated, updating table contents ...<br /><br />";

	$sql = new db; $sql2 = new db;

	$sql -> db_Select("admin");
	while($row = $sql -> db_Fetch()){
		@extract($row);
		$sql2 -> db_Update("user", "user_perms='$admin_permissions' WHERE user_name='$admin_name' ");
	}
	$str .= "Administrators updated ...<br />";

	$sql -> db_Select("admin");
	while($row = $sql -> db_Fetch()){
		@extract($row);
		$sql2 -> db_Select("user", "*", "user_name='$admin_name' ");
		$row2 = $sql2 -> db_Fetch();
		@extract($row2);
		$sql2 -> db_Update("news", "news_author='$user_id' WHERE news_author='$admin_id' ");
		$sql2 -> db_Update("content", "content_author='$user_id' WHERE content_author='$admin_id' ");
		$sql2 -> db_Update("poll", "poll_admin_id='$user_id' WHERE poll_admin_id='$admin_id' ");
	}
	$str .= "News authors updated ...<br />Content authors updated ...<br />Poll authors updated ...<br />";

	$sql -> db_Select("e107");
	$row = $sql -> db_Fetch();
	@extract($row);
	$row['e107_version'] = "v5.4";
	$row['e107_build'] = "b1";
	$tmp = serialize($row);
	$sql -> db_Insert("core", " 'e107', '$tmp' ");
	$e_SELF = "http://".$_SERVER['HTTP_HOST'].$_SERVER['PHP_SELF'];
	$pref['sitename'][1] = "e107 powered website";
	$pref['siteurl'][1] = "http://yoursite.com";
	$pref['sitebutton'][1] = "button.png";
	$pref['sitetag'][1] = "Website System ".$e107['e107_version']." ".$e107['e107_build'];
	$pref['sitedescription'][1] = "";
	$pref['siteadmin'][1] = $mainsiteadmin;
	$pref['siteadminemail'][1] = $mainsiteadminemail;
	$pref['sitetheme'][1] = "e107";
	$pref['sitedisclaimer'][1] = "All trademarks are &copy; their respective owners, all other content is &copy; e107 powered website.<br />e107 is &copy; e107.org 2002/2003 and is released under the <a href=\"http://www.gnu.org/\">GNU GPL license</a>.";
	$pref['newsposts'][1] = "10";
	$pref['flood_protect'][1] = "";
	$pref['flood_timeout'][1] = "5";
	$pref['flood_time'][1] = "30";
	$pref['flood_hits'][1] = "100";
	$pref['anon_post'][1] = "1";
	$pref['user_reg'][1] = "1";
	$pref['use_coppa'][1] = "1";
	$pref['profanity_filter'][1] = "1";
	$pref['profanity_replace'][1] = "[censored]";
	$pref['chatbox_posts'][1] = "10";
	$pref['smiley_activate'][1] = "";
	$pref['log_activate'][1] = "";
	$pref['log_refertype'][1] = "1";
	$pref['longdate'][1] = "%A %d %B %Y - %H:%M:%S";
	$pref['shortdate'][1] = "%d %b : %H:%M";
	$pref['forumdate'][1] = "%a %b %d %Y, %I:%M%p";
	$pref['sitelanguage'][1] = "English";
	$pref['maintainance_flag'][1] = "0";
	$pref['time_offset'][1] = "0";
	$pref['cb_linkc'][1] = " -link- ";
	$pref['cb_wordwrap'][1] = "30";
	$pref['cb_linkreplace'][1] = "1";
	$pref['log_lvcount'][1] = "10";
	$pref['meta_tag'][1] = "";
	$pref['user_reg_veri'][1] = "1";
	$tmp = serialize($pref);
	$sql -> db_Insert("core", " 'pref', '$tmp' ");
			
	$str .= "Core table propagated ...<br />";

	$sql -> db_Select("userclass_classes", "*", "userclass_name='PRIVATEFORUM' ");
	if($row = $sql -> db_Fetch()){
		@extract($row);
		$sql -> db_Update("forum", "forum_class ='$userclass_id' WHERE forum_active='2' ");
	}
	$str .= "Forum classes updated.<br />";

	if($sql -> db_Select("userclass_users")){
		while($row = $sql -> db_Fetch()){
			@extract($row);
			$sql2 -> db_Update("user", "user_class ='$userclass_class' WHERE user_id='$userclass_user' ");
		}
		$str .= "User classes updated.<br /><br />";
	}

	@mysql_query("DROP TABLE `".MUSER."admin`"); 
	@mysql_query("DROP TABLE `".MUSER."prefs`");
	@mysql_query("DROP TABLE `".MUSER."e107`");

	return($str);
}

class db{
	var $mySQLserver;
	var $mySQLuser;
	var $mySQLpassword;
	var $mySQLdefaultdb;
	var $mySQLaccess;
	var $mySQLresult;
	var $mySQLrows;
	var $mySQLerror;
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------//
	function db_Connect($mySQLserver, $mySQLuser, $mySQLpassword, $mySQLdefaultdb){
		$this->mySQLserver = $mySQLserver;
		$this->mySQLuser = $mySQLuser;
		$this->mySQLpassword = $mySQLpassword;
		$this->mySQLdefaultdb = $mySQLdefaultdb;
		$temp = $this->mySQLerror;
		$this->mySQLerror = FALSE;
		$this->mySQL_access = @mysql_connect($this->mySQLserver, $this->mySQLuser, $this->mySQLpassword);
		@mysql_select_db($this->mySQLdefaultdb);
		$this->dbError("dbConnect/SelectDB");
		return $this->mySQLerror = $temp;
	}
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------//
	function db_Select($table, $fields="*", $arg="", $mode="default"){
//		echo "SELECT ".$fields." FROM ".MUSER.$table." WHERE ".$arg."<br />";
		if($arg != "" && $mode=="default"){
			if($this->mySQLresult = @mysql_query("SELECT ".$fields." FROM ".MUSER.$table." WHERE ".$arg)){
				$this->dbError("dbQuery");
				return $this->db_Rows();
			}else{
				$this->dbError("dbQuery ($query)");
				return FALSE;
			}
		}else if($arg != "" && $mode != "default"){
			if($this->mySQLresult = @mysql_query("SELECT ".$fields." FROM ".MUSER.$table." ".$arg)){
				$this->dbError("dbQuery");
				return $this->db_Rows();
			}else{
				$this->dbError("dbQuery ($query)");
				return FALSE;
			}
		}else{
			if($this->mySQLresult = @mysql_query("SELECT ".$fields." FROM ".MUSER.$table)){
				$this->dbError("dbQuery");
				return $this->db_Rows();
			}else{
				$this->dbError("db_Query ($query)");
				return FALSE;
			}		
		}
	}
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------//
	function db_Insert($table, $arg){
		if($result = $this->mySQLresult = @mysql_query("INSERT INTO ".MUSER.$table." VALUES (".$arg.")" )){
			return $result;
		}else{
			$this->dbError("db_Insert ($query)");
			return FALSE;
		}
	}
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------//
	function db_Update($table, $arg){
		if($result = $this->mySQLresult = @mysql_query("UPDATE ".MUSER.$table." SET ".$arg)){	
			return $result;
		}else{
			$this->dbError("db_Update ($query)");
			return FALSE;
		}
	}
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------//
	function db_Fetch(){
		if($row = @mysql_fetch_array($this->mySQLresult)){
			while (list($key,$val) = each($row)) {
				$row[$key] = stripslashes($val);
			}
			$this->dbError("db_Fetch");
			return $row;
		}else{
			$this->dbError("db_Fetch");
			return FALSE;
		}
	}
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------//
	function db_Close(){
		mysql_close();
		$this->dbError("dbClose");
	}
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------//
	function db_Delete($table, $arg){
		if($arg == ""){
			if($result = $this->mySQLresult = @mysql_query("DELETE FROM ".MUSER.$table)){
				return $result;
			}else{
				$this->dbError("db_Delete ($query)");
				return FALSE;
			}
		}else{
			if($result = $this->mySQLresult = @mysql_query("DELETE FROM ".MUSER.$table." WHERE ".$arg)){
				return $result;
			}else{
				$this->dbError("db_Delete ($query)");
				return FALSE;
			}
		}
	}
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------//
	function db_Rows(){
		$rows = $this->mySQLrows = @mysql_num_rows($this->mySQLresult);
		return $rows;
		$this->dbError("db_Rows");
	}
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------//
	function dbError($from){
		if($error_message = @mysql_error()){
			if($this->mySQLerror == TRUE){
				echo "<b>mySQL Error!</b> Function: $from. [".@mysql_errno()." - $error_message]<br />";
				return $error_message;
			}
		}
	}
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------//
	function db_SetErrorReporting($mode){
		$this->mySQLerror = $mode;
	}
}


?>