tinymce.addI18n('en_GB',{
"Button (Default)": "Button (Default)",	
"Button (Primary)": "Button (Primary)",
"Button (Success)": "Button (Success)",
"Button (Info)": "Button (Info)",
"Button (Warning)": "Button (Warning)",
"Button (Danger)": "Button (Danger)",
"Responsive (recommended)": "Responsive (recommended)",
"Rounded": "Rounded",
"Bordered": "Bordered",
"Condensed": "Condensed",
"Hover": "Hover",
"Striped": "Striped",
"Animate.css Delay": "Animate.css Delay",
"2 sec.": "2 sec.",
"4 sec.": "4 sec.",
"6 sec.": "6 sec.",
"8 sec.": "8 sec.",
"10 sec.": "10 sec.",
"12 sec.": "12 sec.",
"14 sec.": "14 sec.",
"16 sec.": "16 sec.",
"18 sec.": "18 sec.",
"20 sec.": "20 sec.",
"22 sec.": "22 sec.",
"24 sec.": "24 sec.",
"26 sec.": "26 sec.",
"28 sec.": "28 sec.",
"30 sec.": "30 sec.",
"Animate.css Style": "Animate.css Style",
"Bootstrap Inline": "Bootstrap Inline",
"Label (Default)": "Label (Default)",
"Label (Primary)": "Label (Primary)",
"Label (Success)": "Label (Success)",
"Label (Info)": "Label (Info)",
"Label (Warning)": "Label (Warning)",
"Label (Danger)": "Label (Danger)",
"Muted": "Muted",
"Alert (Success)": "Alert (Success)",
"Alert (Info)": "Alert (Info)",
"Alert (Warning)": "Alert (Warning)",
"Alert (Danger)": "Alert (Danger)",
"No Text-Wrap": "No Text-Wrap",
"Clear Float": "Clear Float",
"Insert Media-Manager Image": "Insert Media-Manager Image",
"Insert Media-Manager Video": "Insert Media-Manager Video",
"Insert Media-Manager Glyph": "Insert Media-Manager Glyph",
"Cut": "Cut",
"Heading 5": "Heading 5",
"Header 2": "Header 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.",
"Heading 4": "Heading 4",
"Div": "Div",
"Heading 2": "Heading 2",
"Paste": "Paste",
"Close": "Close",
"Font Family": "Font Family",
"Pre": "Pre",
"Align right": "Align right",
"New document": "New document",
"Blockquote": "Blockquote",
"Numbered list": "Numbered list",
"Heading 1": "Heading 1",
"Headings": "Headings",
"Increase indent": "Increase indent",
"Formats": "Formats",
"Headers": "Headers",
"Select all": "Select all",
"Header 3": "Header 3",
"Blocks": "Blocks",
"Undo": "Undo",
"Strikethrough": "Strike-through",
"Bullet list": "Bullet list",
"Header 1": "Header 1",
"Superscript": "Superscript",
"Clear formatting": "Clear formatting",
"Font Sizes": "Font Sizes",
"Subscript": "Subscript",
"Header 6": "Header 6",
"Redo": "Redo",
"Paragraph": "Paragraph",
"Ok": "Ok",
"Bold": "Bold",
"Code": "Code",
"Italic": "Italic",
"Align center": "Align centre",
"Header 5": "Header 5",
"Heading 6": "Heading 6",
"Heading 3": "Heading 3",
"Decrease indent": "Decrease indent",
"Header 4": "Header 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.",
"Underline": "Underline",
"Cancel": "Cancel",
"Justify": "Justify",
"Inline": "Inline",
"Copy": "Copy",
"Align left": "Align left",
"Visual aids": "Visual aids",
"Lower Greek": "Lower Greek",
"Square": "Square",
"Default": "Default",
"Lower Alpha": "Lower Alpha",
"Circle": "Circle",
"Disc": "Disc",
"Upper Alpha": "Upper Alpha",
"Upper Roman": "Upper Roman",
"Lower Roman": "Lower Roman",
"Name": "Name",
"Anchor": "Anchor",
"You have unsaved changes are you sure you want to navigate away?": "You have unsaved changes are you sure you want to navigate away?",
"Restore last draft": "Restore last draft",
"Special character": "Special character",
"Source code": "Source code",
"B": "B",
"R": "R",
"G": "G",
"Color": "Colour",
"Right to left": "Right to left",
"Left to right": "Left to right",
"Emoticons": "Emoticons",
"Robots": "Robots",
"Document properties": "Document properties",
"Title": "Title",
"Keywords": "Keywords",
"Encoding": "Encoding",
"Description": "Description",
"Author": "Author",
"Fullscreen": "Full-screen",
"Horizontal line": "Horizontal line",
"Horizontal space": "Horizontal space",
"Insert\/edit image": "Insert\/edit image",
"General": "General",
"Advanced": "Advanced",
"Source": "Source",
"Border": "Border",
"Constrain proportions": "Constrain proportions",
"Vertical space": "Vertical space",
"Image description": "Image description",
"Style": "Style",
"Dimensions": "Dimensions",
"Insert image": "Insert image",
"Zoom in": "Zoom in",
"Contrast": "Contrast",
"Back": "Back",
"Gamma": "Gamma",
"Flip horizontally": "Flip horizontally",
"Resize": "Resize",
"Sharpen": "Sharpen",
"Zoom out": "Zoom out",
"Image options": "Image options",
"Apply": "Apply",
"Brightness": "Brightness",
"Rotate clockwise": "Rotate clockwise",
"Rotate counterclockwise": "Rotate counterclockwise",
"Edit image": "Edit image",
"Color levels": "Colour levels",
"Crop": "Crop",
"Orientation": "Orientation",
"Flip vertically": "Flip vertically",
"Invert": "Invert",
"Insert date\/time": "Insert date\/time",
"Remove link": "Remove link",
"Url": "Url",
"Text to display": "Text to display",
"Anchors": "Anchors",
"Insert link": "Insert link",
"New window": "New window",
"None": "None",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?",
"Target": "Target",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?",
"Insert\/edit link": "Insert\/edit link",
"Insert\/edit video": "Insert\/edit video",
"Poster": "Poster",
"Alternative source": "Alternative source",
"Paste your embed code below:": "Paste your embed code below:",
"Insert video": "Insert video",
"Embed": "Embed",
"Nonbreaking space": "Non-breaking space",
"Page break": "Page break",
"Paste as text": "Paste as text",
"Preview": "Preview",
"Print": "Print",
"Save": "Save",
"Could not find the specified string.": "Could not find the specified string.",
"Replace": "Replace",
"Next": "Next",
"Whole words": "Whole words",
"Find and replace": "Find and replace",
"Replace with": "Replace with",
"Find": "Find",
"Replace all": "Replace all",
"Match case": "Match case",
"Prev": "Prev",
"Spellcheck": "Spell-check",
"Finish": "Finish",
"Ignore all": "Ignore all",
"Ignore": "Ignore",
"Add to Dictionary": "Add to Dictionary",
"Insert row before": "Insert row before",
"Rows": "Rows",
"Height": "Height",
"Paste row after": "Paste row after",
"Alignment": "Alignment",
"Border color": "Border colour",
"Column group": "Column group",
"Row": "Row",
"Insert column before": "Insert column before",
"Split cell": "Split cell",
"Cell padding": "Cell padding",
"Cell spacing": "Cell spacing",
"Row type": "Row type",
"Insert table": "Insert table",
"Body": "Body",
"Caption": "Caption",
"Footer": "Footer",
"Delete row": "Delete row",
"Paste row before": "Paste row before",
"Scope": "Scope",
"Delete table": "Delete table",
"H Align": "H Align",
"Top": "Top",
"Header cell": "Header cell",
"Column": "Column",
"Row group": "Row group",
"Cell": "Cell",
"Middle": "Middle",
"Cell type": "Cell type",
"Copy row": "Copy row",
"Row properties": "Row properties",
"Table properties": "Table properties",
"Bottom": "Bottom",
"V Align": "V Align",
"Header": "Header",
"Right": "Right",
"Insert column after": "Insert column after",
"Cols": "Cols",
"Insert row after": "Insert row after",
"Width": "Width",
"Cell properties": "Cell properties",
"Left": "Left",
"Cut row": "Cut row",
"Delete column": "Delete column",
"Center": "Centre",
"Merge cells": "Merge cells",
"Insert template": "Insert template",
"Templates": "Templates",
"Preformatted": "Preformatted",
"Align":"Align",
"Template": "Template",
"Date\/time": "Date\/time",
"Media": "Media",
"Media Manager": "Media Manager",
"Image": "Image",
"Insert\/edit media": "Insert\/edit media",
"Lists": "Lists",
"Bootstrap Blocks": "Bootstrap Blocks",
"Bootstrap Buttons": "Bootstrap Buttons",
"Bootstrap Images": "Bootstrap Images",
"Bootstrap Tables": "Bootstrap Tables",
"Bootstrap table": "Bootstrap table",
"Image Left": "Image Left",
"Image Right": "Image Right",
"Insert e107 BBcode": "Insert e107 BBcode",
"BbCode": "BbCode",
"Smileys": "Smileys",
"e107 BBcode": "e107 BBcode",
"Small": "Small",
"Code Highlighted": "Code Highlighted",
"Background color": "Background color",
"Custom...": "Custom...",
"Custom color": "Custom colour",
"No color": "No colour",
"Text color": "Text colour",
"Show blocks": "Show blocks",
"Show invisible characters": "Show invisible characters",
"Words: {0}": "Words: {0}",
"{0} words": "{0} words",
"Insert": "Insert",
"File": "File",
"Edit": "Edit",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help",
"Tools": "Tools",
"View": "View",
"Table": "Table",
"Format": "Format",
"Well": "Well",
"Class": "Class",
"Alert Link": "Alert Link",
"Select...": "Select...",
"Border width": "Border width",
"Border style": "Border style",
"Lead": "Lead",
"1/4 Width Block": "1/4 Width Block",
"3/4 Width Block": "3/4 Width Block",
"1/3 Width Block": "1/3 Width Block",
"2/3 Width Block": "2/3 Width Block",
"1/2 Width Block": "1/2 Width Block",
"Solid": "Solid",
"Dotted": "Dotted",
"Dashed": "Dashed",
"Double": "Double",
"Groove": "Groove",
"Ridge": "Ridge",
"Inset": "Inset",
"Outset": "Outset",
"Adds a Bootstrap 3 table at cursor": "Adds a Bootstrap 3 table at cursor",
"Bootstrap Row 2 Column - 4:8": "Bootstrap Row 2 Column - 4:8",
"Powered by {0}": "Powered by {0}"
});
