<?php

/*
+----------------------------------------------------+
|   e107 website system
|   e107_config.php
|
|   ©Steve Dunstan 2001-2002
|   http://e107.org
|   jalist@e107.org
|
|   Released under the terms and conditions of the
|   GNU General Public License (http://gnu.org).
+----------------------------------------------------+
This file has been generated by the installation script.
*/

$mySQLserver    = '{{ mySQLserver }}';
$mySQLuser      = '{{ mySQLuser }}';
$mySQLpassword  = '{{ mySQLpassword }}';
$mySQLdefaultdb = '{{ mySQLdefaultdb }}';
$mySQLprefix    = '{{ mySQLprefix }}';
// $mySQLcharset can only contain 'utf8' or ''
$mySQLcharset   = 'utf8';

$ADMIN_DIRECTORY     = 'e107_admin/';
$FILES_DIRECTORY     = 'e107_files/';
$IMAGES_DIRECTORY    = 'e107_images/';
$THEMES_DIRECTORY    = 'e107_themes/';
$PLUGINS_DIRECTORY   = 'e107_plugins/';
$HANDLERS_DIRECTORY  = 'e107_handlers/';
$LANGUAGES_DIRECTORY = 'e107_languages/';
$HELP_DIRECTORY      = 'e107_docs/help/';
$MEDIA_DIRECTORY     = 'e107_media/';
$SYSTEM_DIRECTORY    = 'e107_system/';

$E107_CONFIG = array('site_path' => '000000test');

define('e_MOD_REWRITE',true);
