<?php
/*
+ ----------------------------------------------------------------------------+
|     e107 website system - Language File.
|
|     $Source: /cvs_backup/e107_langpacks/legacy_langpacks/e107_plugins/content/languages/Danish/lan_content_help.php,v $
|     $Revision: 1.1 $
|     $Date: 2005-09-17 09:52:21 $
|     $Author: e107dk $
+----------------------------------------------------------------------------+
*/

define("CONTENT_ADMIN_HELP_1", "Indholds H&aring;ndtering Hj&aelig;lp Omr&aring;de");

define("CONTENT_ADMIN_HELP_ITEM_1", "<i>hvis du endnu ikke har opretet hoved for&aelig;lder kategorier, s&aring; g&oslash;r det p&aring; <a href='".e_SELF."?cat.create'>Opret Ny Kategori</a> siden.</i><br /><br /><b>kategori</b><br />v&aelig;lg en kategori fra rullemenuen for at h&aring;ndtere indhold for den kategori.<br /><br />Ved at v&aelig;lge en hoved for&aelig;lder fra rullemenuen vises alle indholds emner i den hoved kategori.<br />Ved at v&aelig;lge en under kategori vises kun indholdet i den valgte underkategori.<br /><br />Du kan ogs&aring; bruge menuen til h&oslash;jre til at vise alle indholds emner for en bestemt kategori.");

define("CONTENT_ADMIN_HELP_ITEM_2", "<b>f&oslash;rste bogstaver</b><br />hvis flere indholds emner starter med bogstaver af content_heading er til stede, vil du se knapper til at v&aelig;lge kun de indholds emner startende med det bogstav. Ved valg af 'alle' knappen vises en liste indeholdende alle indholds emner i den kategori.<br /><br /><b>detalje liste</b><br />Du ser en liste af alle indholds emner med deres id, ikon, forfatter, overskrift [under overskrift] og indstillinger.<br /><br /><b>forklaring af ikoner</b><br />".CONTENT_ICON_USER." : link til forfatter profil<br />".CONTENT_ICON_LINK." : link til indholds emnet<br />".CONTENT_ICON_EDIT." : rediger indholds emnet<br />".CONTENT_ICON_DELETE." : slet indholds emnet<br />");

define("CONTENT_ADMIN_HELP_ITEMEDIT_1", "<b>rediger formular</b><br />du kan nu redigere alle informationerne for dette indholds emne og tilf&oslash;je dine &aelig;ndringer.<br /><br />Hvis du beh&oslash;ver at &aelig;ndre kategorien for dette indholds emne, s&aring; g&oslash;r venligst dette f&oslash;rst. Efter du har valgt den korrekte kategori, &aelig;ndrer eller opret evt. felter der er tilstede, f&oslash;r du kan tilf&oslash;je &aelig;ndringerne.");

define("CONTENT_ADMIN_HELP_ITEMCREATE_1", "<b>kategori</b><br />v&aelig;lg venligst en kategori fra boksen for at oprette dit indholds emne for.<br />");

define("CONTENT_ADMIN_HELP_ITEMCREATE_2", "<b>oprettelses formular</b><br />du kan levere alle informationer til dette indholds emne og oprette det.<br /><br />V&aelig;r opm&aelig;rksom p&aring; at forskellige hoved for&aelig;lder kategorier kan have hver deres s&aelig;t indstillinger; forskellige felter kan v&aelig;re tilg&aelig;ngelige for dig at udfylde. Derfor er du altid n&oslash;d til at v&aelig;lge en kategori f&oslash;r du udfylder andre felter !");

define("CONTENT_ADMIN_HELP_CAT_1", "<i>denne side viser alle kategorier og underkategorier der er tilstede.</i><br /><br /><b>detaljret liste</b><br />Du ser en liste over alle underkategorier med deres id, ikon, forfatter, kategori [underoverskrift] og egenskaber.<br /><br /><b>forklaring af ikoner</b><br />".CONTENT_ICON_USER." : link til forfatterens profil<br />".CONTENT_ICON_LINK." : link til kategorien<br />".CONTENT_ICON_EDIT." : rediger kategorien<br />".CONTENT_ICON_DELETE." : slet kategorien<br />");

define("CONTENT_ADMIN_HELP_CAT_2", "<i>denne side tillader at oprette en ny kategori</i><br /><br />V&aelig;lg altid en for&aelig;lder kategori f&oslash;r du udfylder de andre felter !<br /><br />Dette skal g&oslash;res, fordi nogle unikke kategori egenskaber skal indl&aelig;ses i systemet.<br /><br />Som standard vises kategori siden for at oprette en ny hovedkategori.");

define("CONTENT_ADMIN_HELP_CAT_3", "<i>denne side viser rediger kategori formularen.</i><br /><br /><b>rediger kategori formular</b><br />du kan nu redigere alle informationer for denne (under)kategori og tilf&oslash;je dine &aelig;ndringer.<br /><br />Hvis du &oslash;nsker at &aelig;ndre for&aelig;lder beliggenhed for denne kategori, s&aring; g&oslash;r venligst dette f&oslash;rst. Efter du har indstillet den kategori rediger alle andre felter.");

define("CONTENT_ADMIN_HELP_ORDER_1", "<i>denne side viser alle kategorier og underkategorier der er tilstede.</i><br /><br /><b>detaljeret liste</b><br />du ser kategori id og kategori navn. du ser ogs&aring; adskillige muligheder til at h&aring;ndtere sorteringen af kategorierne.<br /><br /><b>forklaring af ikoner</b><br />".CONTENT_ICON_USER." : link til forfatter profilen<br />".CONTENT_ICON_LINK." : link til kategorien<br />".CONTENT_ICON_ORDERALL." : h&aring;ndter den generelle sortering af indhold uanset kategori.<br />".CONTENT_ICON_ORDERCAT." : h&aring;ndter sorteringen af indholds emner i den enkelte kategori.<br />".CONTENT_ICON_ORDER_UP." : op knappen tillader dig at flytte et indholds emne en plads op i ordnen.<br />".CONTENT_ICON_ORDER_DOWN." : ned knappen lader dig at flytte et indholds emne en plads ned i ordnen.<br /><br /><b>sortering</b><br />her kan du manuelt indstille ordnen af alle kategorier i denne for&aelig;lder. Du skal &aelig;ndre v&aelig;rdierne i boksene for den orden du &oslash;nsker og s&aring; trykke p&aring; opdater knappen nedenfor for at gemme den nye sortering.<br />");

define("CONTENT_ADMIN_HELP_ORDER_2", "<i>denne side viser alle indholds emner fra den kategori du har valgt.</i><br /><br /><b>detaljeret liste</b><br />du ser indholds id, indholds forfatter og indholds overskrift. du ser ogs&aring; adskillige muligheder til at h&aring;ndtere sorteringen af indholds emnerne.<br /><br /><b>forklaring af ikoner</b><br />".CONTENT_ICON_USER." : link til forfatter profilen<br />".CONTENT_ICON_LINK." : link til indholds emne<br />".CONTENT_ICON_ORDER_UP." : op knappen lader dig flytte et indholds emne en plads op i ordnen.<br />".CONTENT_ICON_ORDER_DOWN." : ned knappen lader dig flytte et indholds emne en plads ned i ordnen.<br /><br /><b>sortering</b><br />her kan du manuelt indstille ordnen af alle kategorier i denne for&aelig;lder. Du skal &aelig;ndre v&aelig;rdierne i boksene for den orden du &oslash;nsker og s&aring; trykke p&aring; opdater knappen nedenfor for at gemme den nye sortering.<br />");

define("CONTENT_ADMIN_HELP_ORDER_3", "<i>denne side viser alle indholds emner fra den hoved kategori for&aelig;lder du har valgt.</i><br /><br /><b>detaljeret liste</b><br />du ser indholds id, indholds forfatter og indholds overskrift. du ser ogs&aring; adskillige muligheder til at h&aring;ndtere sorteringen af indholds emnerne.<br /><br /><b>forklaring af ikoner</b><br />".CONTENT_ICON_USER." : link til forfatter profilen<br />".CONTENT_ICON_LINK." : link til indholds emne<br />".CONTENT_ICON_ORDER_UP." : op knappen lader dig flytte et indholds emne en plads op i ordnen.<br />".CONTENT_ICON_ORDER_DOWN." : ned knappen lader dig flytte et indholds emne en plads ned i ordnen.<br /><br /><b>sortering</b><br />her kan du manuelt indstille ordnen af alle kategorier i hver for&aelig;lder. Du skal &aelig;ndre v&aelig;rdierne i boksene for den orden du &oslash;nsker og s&aring; trykke p&aring; opdater knappen nedenfor for at gemme den nye sortering.<br />");

define("CONTENT_ADMIN_HELP_OPTION_1", "P&aring; denne side kan du v&aelig;lge en hoved kategori for&aelig;lder til at indstille egenskaber for, eller du kan v&aelig;lge at redigere standard indstillingerne.<br /><br /><b>forklaring af ikoner</b><br />".CONTENT_ICON_USER." : link til forfatter profilen<br />".CONTENT_ICON_LINK." : link til kategorien<br />".CONTENT_ICON_OPTIONS." : rediger egenskaber<br /><br /><br />
Standard indstillingerne bruges kun n&aring;r du opretter en ny hoved for&aelig;lder. S&aring; n&aring;r du opretter en hoved for&aelig;lder vil disse standard indstillinger blive gemt. Du kan &aelig;ndre disse for at sikre at nyligt oprettede hoved for&aelig;ldre allerede har et bestemt s&aelig;t muligheder tilstede.
<br /><br />
Hver hoved for&aelig;lder har sit eget s&aelig;t indstillinger, der er unikke til den bestemte hoved kategori for&aelig;lder");


//define("CONTENT_ADMIN_HELP_OPTION_2", "<i>this page shows the options you can set for this main parent. Each main parent has their own specific set of options, so be sure to set them all correctly.</i><br /><br />");
//<b>default values</b><br />By default all values are present and already updated in the preferences when you view this page, but change any setting to your own standards.<br /><br />
define("CONTENT_ADMIN_HELP_MANAGER_1", "P&aring; denne side kan du se en liste over alle kategorier. Du kan h&aring;ndtere 'personlig indholds h&aring;ndtering' for hver kategori ved at klikke p&aring; ikonet.<br /><br /><b>forklaring af ikoner</b><br />".CONTENT_ICON_USER." : link til forfatter profilen<br />".CONTENT_ICON_LINK." : link til kategorien<br />".CONTENT_ICON_CONTENTMANAGER_SMALL." : rediger personlig indholds h&aring;ndtering<br />");

define("CONTENT_ADMIN_HELP_MANAGER_2", "<i>p&aring; denne side kan du tildele brugere til den kategori du har klikket p&aring;</i><br /><br /><b>personlig h&aring;ndtering</b><br />du kan tildele brugere til bestemte kategorier. Ved at g&oslash;re detteo, kan disse brugere h&aring;ndtere deres personlige indholds emner inden for disse kategorier uden for admin siden (content_manager.php).<br /><br />Tildel brugere fra venstre kolonne ved at klikke p&aring; deres navn. du vil se nevnet flyttes til den h&oslash;jre kolonne. Efter du klikker p&aring; tildel knappen vil brugerne i den h&oslash;jre kolonne v&aelig;re tildelt til denne kategori.");

define("CONTENT_ADMIN_HELP_SUBMIT_1", "<i>P&aring; denne side kan du se en liste over alle indholds emner der er tilf&oslash;jet af brugere.</i><br /><br /><b>detaljeret liste</b><br />Du ser en liste over disse indholds emner med deres id, ikon, hoved for&aelig;lder, overskrift [underoverskrift], forfatter og egenskaber.<br /><br /><b>egenskaber</b><br />du kan oprette eller slette et indholds emne ved hj&aelig;lp af de viste knapper.");



define("CONTENT_ADMIN_HELP_OPTION_DIV_1", "denne side lader dig indstille egenskaber for admin opret emne siden.<br /><br />Du kan definere hvilke sektioner der er tilg&aelig;ngelige n&aring;r en admin (eller personlig indholds bestyrer) opretter et nyt indholds emne<br /><br /><b>specielle data tags</b><br />du kan tillade en bruger eller admin at tilf&oslash;je yderligere felter til indholds emnet ved hj&aelig;lp af disse specielle data tags. Disse ekstra felter er tomme n&oslash;gle=>v&aelig;rdi par. For eksempel: kan du tilf&oslash;je en n&oslash;gle for 'fotograf' og her levere v&aelig;rdi felt med 'alle fotos af mig'. B&aring;de n&oslash;gle og v&aelig;rdi felterne er tomme tekst felter der vil v&aelig;re til stede i opret formularen.<br /><br /><b>forudindstilte data tags</b><br />bortset fra de specielle data tags, du kan bestemme forudindstillede data tags. Forskellen er i forudindstillede data tags, er n&oslash;glen allerede givet og brugeren skal kun levere v&aelig;rdi feltet for det forudindstillede. I samme eksempel som 'fotograf' ovenfor kan forud defineres, og brugeren skal levere 'alle fotos af mig'. Du kan v&aelig;lge element typen ved at v&aelig;lge egenskaben i valgboksen. I popup vinduet, kan du levere alle de informationer for det forudindstillede data tag.<br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_2", "Tilf&oslash;j egenskaberne har effekt p&aring; bruger tilf&oslash;j formularen for indholds emner.<br /><br />Du kan definere hvilke sektioner der er tilg&aelig;ngelige for en bruger ved tilf&oslash;jelsen af et indholds emne.<br /><br />".CONTENT_ADMIN_OPT_LAN_11.":<br />".CONTENT_ADMIN_OPT_LAN_12."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_3", "I Sti og Tema Egenskaberne kan du definere hvor billeder og filer gemmes.<br /><br />du kan definere hvilket tema der skal bruges af denne hoved for&aelig;lder. Du kan oprette yderligere temaer ved kopiere (og omd&oslash;be) hele 'default' mappen i din templates mappe.<br /><br />Du kan definere et standard layout skema for nye indholds emner. Du kan oprette nye layout skemaer ved at oprette en content_content_template_XXX.php fil i din 'templates/default' mappe. Disse layouts kan bruges til at give hvert indholds emne i denne hoved for&aelig;lder et anderledes layout.<br /><br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_4", "De Generelle Egenskaber er indstillinger der bruges gennem alle indholds siderne fra indholds h&aring;ndterings plugin.");

define("CONTENT_ADMIN_HELP_OPTION_DIV_5", "Disse egenskaber har effekt p&aring; det Personlge Indholds H&aring;ndtering omr&aring;de p&aring; indholds h&aring;ndtering admin omr&aring;det.<br /><br />".CONTENT_ADMIN_OPT_LAN_63."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_6", "Disse egenskaber bruges i Menuen for denne hoved for&aelig;lder hvis du har aktiveret menuen.<br /><br />".CONTENT_ADMIN_OPT_LAN_68."<br /><br />".CONTENT_ADMIN_OPT_LAN_118.":<br />".CONTENT_ADMIN_OPT_LAN_119."<br /><br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_7", "Indholds Emne Fremvisning egenskaber har effekt p&aring; den lille fremvisning der gives for et indholds emne.<br /><br />Denne fremvisning gives p&aring; flere sider, lige som seneste nyt siden, visningen emner i kategori side og visninger af emner af forfatter side.<br /><br />".CONTENT_ADMIN_OPT_LAN_68."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_8", "Kategori Sider viser informationer om indholds kategorier i denne hoved for&aelig;lder.<br /><br />Der er to udpr&aelig;gede omr&aring;der tilstede:<br /><br />alle kategorier side:<br />denne side viser alle kategorierne i denne hoved for&aelig;lder<br /><br />vis kategori side:<br />denne side viser kategori emne, valgfrit underkategorierne i den kategori og indholds emner i den kategori eller disse kategorier<br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_9", "Indholds Siden viser Indholds Emne.<br /><br />du kan definere hvilke sektioner der skal vises ved at markere/afmarkere boksene.<br /><br />du kan vise emailadressen p&aring; en ikke-medlem forfatter.<br /><br />du kan tilsides&aelig;tte email/udskriv/pdf ikoner, bed&oslash;mmelses systemet og kommentarerne.<br /><br />".CONTENT_ADMIN_OPT_LAN_74."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_10", "Forfatter Siden viser en liste med alle unikke forfattere af indholds emnerne i denne hoved for&aelig;lder.<br /><br />du kan definere hvilke sektioner der skal vises ved at markere/afmarkere boksene.<br /><br />Du kan begr&aelig;nse antal emner pr. side.<br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_11", "Arkiv Siden viser alle indholds emner i hoved for&aelig;lderen.<br /><br />du kan definere hvilke sektioner der skal vises ved at markere/afmarkere boksene.<br /><br />du kan vise emailadressen p&aring; en ikke-medlem forfatter.<br /><br />Du kan begr&aelig;nse antal emner der skal vises pr. side.<br /><br />".CONTENT_ADMIN_OPT_LAN_66."<br /><br />".CONTENT_ADMIN_OPT_LAN_68."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_12", "Top Bed&oslash;mt Siden viser alle indholds emner der er blevet bed&oslash;mt af  brugere.<br /><br />Du kan v&aelig;lge de sektioner der skal vises ved at markere boksene.<br /><br />Du kan ogs&aring; definere om emailadressen til en ikke-medlem forfatter skal vises.");

define("CONTENT_ADMIN_HELP_OPTION_DIV_13", "Top Score Siden viser alle indholds emner der har f&aring;et en score af forfatteren til indholds emnet.<br /><br />You can choose the sections to display by checking the boxes.<br /><br />Also you can define if the emailaddress of a non-member author will be displayed.");

?>