// UK lang variables

tinyMCE.addToLang('',{
bold_desc : 'Удебелен (Ctrl+B)',
italic_desc : 'Наклонен (Ctrl+I)',
underline_desc : 'Подчертан (Ctrl+U)',
striketrough_desc : 'Задраснат',
justifyleft_desc : 'Ляво подравняване',
justifycenter_desc : 'Централно подравняване',
justifyright_desc : 'Дясно подравняване',
justifyfull_desc : 'Подравянване всичко',
bullist_desc : 'Несортиран списък',
numlist_desc : 'Сортиран списък',
outdent_desc : 'Текст наляво',
indent_desc : 'Текст надясно',
undo_desc : 'Undo (Ctrl+Z)',
redo_desc : 'Redo (Ctrl+Y)',
link_desc : 'Вмъкване/редакция на линк',
unlink_desc : 'Премахване на линк',
image_desc : 'Вмъкване/редакция на картинка',
cleanup_desc : 'Почистване на объркан код',
focus_alert : 'Редактора трябва да е на фокус преди да ползвате тази команда.',
edit_confirm : 'Искате ли да ползвате режим WYSIWYG за това поле?',
insert_link_title : 'Вмъкване/редакция на линк',
insert : 'Вмъкване',
update : 'Актуализиране',
cancel : 'Отказ',
insert_link_url : 'URL за линка',
insert_link_target : 'Target',
insert_link_target_same : 'Отвори линка в същия прозорец',
insert_link_target_blank : 'Отвори линка в нов прозорец',
insert_image_title : 'Вмъкване/редакция на картинка',
insert_image_src : 'URL на картинката',
insert_image_alt : 'Описание на картинката',
help_desc : 'Помощ',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste не са възможни в Mozilla и Firefox.\nИскате ли да научите повече за това?',
popup_blocked : 'Съжаляваме, но забелязахме, че вашия popup-blocker забрани прозорец необходим за функциалността на този редактор. Необходимо е да позволите отварянето на popup прозорци за този сайт за да ползвате пълната функционалност на този модул.'
});
