// CZ lang variables thanks to "Pavel Novák" - repaired by Josef Klimosz

tinyMCE.addToLang('',{
bold_desc : 'Tuènì',
italic_desc : 'Kurzíva',
underline_desc : 'Podtržení',
striketrough_desc : 'Pøeškrtnutí',
justifyleft_desc : 'Zarovnání vlevo',
justifycenter_desc : 'Zarovnání na støed',
justifyright_desc : 'Zarovnání vpravo',
justifyfull_desc : 'Zarovnání do bloku',
bullist_desc : 'Seznam s odrážkami',
numlist_desc : 'Èíslovaný seznam',
outdent_desc : 'Snížit odsazení',
indent_desc : 'Zvýšit odsazení',
undo_desc : 'Zpìt',
redo_desc : 'Znovu',
link_desc : 'Vložit odkaz',
unlink_desc : 'Zrušit odkaz',
image_desc : 'Vložit obrázek',
cleanup_desc : 'Vyèistit kód',
focus_alert : 'Pøed použitím tohoto pøíkazu musí být kurzor v oknì editoru.',
edit_confirm : 'Chcete použít WYSIWYG editaci pro tento text?',
insert_link_title : 'Vložit/upravit odkaz',
insert : 'Vložit',
update : 'Zmìnit',
cancel : 'Zrušit',
insert_link_url : 'URL odkazu',
insert_link_target : 'Cíl',
insert_link_target_same : 'Otevøít odkaz ve stejném oknì',
insert_link_target_blank : 'Otevøít odkaz v novém oknì',
insert_image_title : 'Vložit/upravit obrázek',
insert_image_src : 'URL obrázku',
insert_image_alt : 'Popis obrázku',
help_desc : 'Nápovìda',
bold_img : 'bold.gif',
italic_img : 'italic.gif',
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste není použitelné v Mozille a Firefoxu.\nChcete více informací o tomto problému?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
