// ES lang variables by Alvaro Velasco

tinyMCE.addToLang('',{
bold_desc : 'Negrita',
italic_desc : 'Cursiva',
underline_desc : 'Subrayado',
striketrough_desc : 'Tachado',
justifyleft_desc : 'Alinear a la izquierda',
justifycenter_desc : 'Alinear al centro',
justifyright_desc : 'Alinear a la derecha',
justifyfull_desc : 'Alinear justificado',
bullist_desc : 'Lista sin ordenar',
numlist_desc : 'Lista ordenada',
outdent_desc : 'Disminuye sangria',
indent_desc : 'Aumentar sangria',
undo_desc : 'Deshacer',
redo_desc : 'Rehacer',
link_desc : 'Insertar enlace',
unlink_desc : 'Quitar enlace',
image_desc : 'Insertar imagen',
cleanup_desc : 'Limpiar codigo',
focus_alert : 'Una instanacia del editor debe ser enfocada antes de usar este comando.',
edit_confirm : 'Quieres usar el modo WYSIWYG para esta area de texto?',
insert_link_title : 'Insertar/editar enlace',
insert : 'Insertar',
update : 'Insertar',
cancel : 'Cancelar',
insert_link_url : 'Direccion del enlace',
insert_link_target : 'Destino',
insert_link_target_same : 'Abrir enlace en la misma ventana',
insert_link_target_blank : 'Abrir enlace en una ventana nueva',
insert_image_title : 'Insertar/editar imagen',
insert_image_src : 'URL de la imagen',
insert_image_alt : 'Descripcion de la imagen',
help_desc : 'Ayuda',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
