// FR lang variables by Pat Boens
// Modify by Laurent Dran

tinyMCE.addToLang('',{
bold_desc : 'Gras',
italic_desc : 'Italique',
underline_desc : 'Soulign&eacute;',
striketrough_desc : 'Barré',
justifyleft_desc : 'Aligner &agrave; gauche',
justifycenter_desc : 'Aligner au centre',
justifyright_desc : 'Aligner &agrave; droite',
justifyfull_desc : 'Justifier',
bullist_desc : 'Liste désordonn&eacute;e (puces)',
numlist_desc : 'Liste ordonn&eacute;e (num&eacute;ros)',
outdent_desc : 'Diminuer le retrait',
indent_desc : 'Augmenter le retrait',
undo_desc : 'D&eacute;faire',
redo_desc : 'Refaire',
link_desc : 'Ins&eacute;rer/éditer le lien',
unlink_desc : 'Enlever le lien',
image_desc : 'Ins&eacute;rer/éditer une image',
cleanup_desc : 'Nettoyer le code',
focus_alert : 'Une instance de l\&eacute;diteur doit avoir le focus avant d\'utiliser cette commande.',
edit_confirm : 'Voulez-vous utiliser le mode WYSIWYG pour cette zone de texte (textarea) ?',
insert_link_title : 'Insertion/&eacute;dition lien',
insert : 'Insertion',
update : 'Insertion',
cancel : 'Annuler',
insert_link_url : 'Lien URL',
insert_link_target : 'Cible',
insert_link_target_same : 'Ouvrir le lien dans la même fen&ecirc;tre',
insert_link_target_blank : 'Ouvrir le lien dans une nouvelle fen&ecirc;tre',
insert_image_title : 'Insertion/&eacute;dition d\'une image',
insert_image_src : 'URL de l\'image',
insert_image_alt : 'Description de l\'image',
help_desc : 'Aide',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copier/Couper/Coller ne sont pas disponibles pour Mozilla et Firefox.\nVoulez vous plus d\'informatios à ce sujet?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
