// HU lang variables
// Edited by 2XP (2xp@dino.hu)

tinyMCE.addToLang('',{
bold_desc : 'F&#233;lk&#246;v&#233;r',
italic_desc : 'D&#245;lt',
underline_desc : 'Al&#225;h&#250;zott',
striketrough_desc : '&#193;th&#250;zott',
justifyleft_desc : 'Balra igaz&#237;t&#225;s',
justifycenter_desc : 'K&#246;z&#233;pre igaz&#237;t&#225;s',
justifyright_desc : 'Jobbra igaz&#237;t&#225;s',
justifyfull_desc : 'Sorkiz&#225;rt',
bullist_desc : 'Felsorol&#225;s',
numlist_desc : 'Sz&#225;mozott lista',
outdent_desc : 'Beh&#250;z&#225;s balra',
indent_desc : 'Beh&#250;z&#225;s jobbra',
undo_desc : 'Visszavon&#225;s',
redo_desc : 'Ism&#233;tl&#233;s',
link_desc : 'Link felv&#233;tele',
unlink_desc : 'Link t&#246;rl&#233;se',
image_desc : 'K&#233;p beilleszt&#233;se',
cleanup_desc : 'K&#243;d tiszt&#237;t&#225;sa',
focus_alert : 'Miel\u00F5tt haszn\u00E1lja ezt a funkci\u00F3t, ki kell jel\u00F6lnie a szerkeszteni k\u00EDv\u00E1nt ter\u00FCletet.',
edit_confirm : 'K\u00EDv\u00E1nja a WYSIWYG m\u00F3dot erre a sz\u00F6vegter\u00FCletre alkalmazni??',
insert_link_title : 'Link beilleszt&#233;se/szerkeszt&#233;se',
insert : 'Beilleszt&#233;s',
update : 'Beilleszt&#233;s',
cancel : 'M&#233;gsem',
insert_link_url : 'Link URL',
insert_link_target : 'C&#233;l',
insert_link_target_same : 'Link megnyit&#225;sa azonos ablakban',
insert_link_target_blank : 'Link megnyit&#225;sa &#250;j ablakban',
insert_image_title : 'K&#233;p beilleszt&#233;se/szerkeszt&#233;se',
insert_image_src : 'K&#233;p URL',
insert_image_alt : 'K&#233;ple&#237;r&#225;s',
help_desc : 'Seg&#237;t&#233;g',
bold_img : 'bold.gif',
italic_img : 'italic.gif',
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
