// NL lang variables thanks to "Meint Post"

tinyMCE.addToLang('',{
bold_desc : 'Vet',
italic_desc : 'Schuin',
underline_desc : 'Onderstrepen',
striketrough_desc : 'Doorhalen',
justifyleft_desc : 'Links uitlijnen',
justifycenter_desc : 'Centreren',
justifyright_desc : 'Rechts uitlijnen',
justifyfull_desc : 'Volledig uitlijnen',
bullist_desc : 'Ongeordende lijst',
numlist_desc : 'Geordende lijst',
outdent_desc : 'Uitspringen',
indent_desc : 'Inspringen',
undo_desc : 'Ongedaan maken',
redo_desc : 'Opnieuw uitvoeren',
link_desc : 'Link invoegen',
unlink_desc : 'Link verwijderen',
image_desc : 'Afbeelding invoegen',
cleanup_desc : 'Slordige code verbeteren',
focus_alert : 'Verplaats de focus naar de editor voor het uitvoeren van dit commado.',
edit_confirm : 'Wilt u de WYSIWYG mode voor deze textarea gebruiken?',
insert_link_title : 'Link invoegen/bewerken',
insert : 'Invoegen',
update : 'Bewerken',
cancel : 'Afbreken',
insert_link_url : 'URL link',
insert_link_target : 'Bestemming',
insert_link_target_same : 'Open link in hetzelfde venster',
insert_link_target_blank : 'Open link in een nieuw venster',
insert_image_title : 'Afbeelding invoegen/bewerken',
insert_image_src : 'Afbeelding',
insert_image_alt : 'Beschrijving',
help_desc : 'Help',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
