// NO lang variables made by Sten Aksel Heien

tinyMCE.addToLang('',{
bold_desc : 'Uthevet',
italic_desc : 'Kursiv',
underline_desc : 'Understreket',
striketrough_desc : 'Gjennomstreket',
justifyleft_desc : 'Vensterestille',
justifycenter_desc : 'Sentrere',
justifyright_desc : 'Høyerestille',
justifyfull_desc : 'Fyll',
bullist_desc : 'Punktliste',
numlist_desc : 'Nummerliste',
outdent_desc : 'Undrag',
indent_desc : 'Indrag',
undo_desc : 'Angre',
redo_desc : 'Gjør om',
link_desc : 'Opprett/endre lenke',
unlink_desc : 'Fjern lenke',
image_desc : 'Sett inn/endre bilde',
cleanup_desc : 'Rens grisete kode',
focus_alert : 'Editoren må være i fokus før du benytter denne kommando.',
edit_confirm : 'Vil du benytte WYSIWYG editoren for dette tekstfelt?',
insert_link_title : 'Opprett/endre lenke',
insert : 'Opprett',
update : 'Opprett',
cancel : 'Avbryt',
insert_link_url : 'Lenkens URL',
insert_link_target : 'Vindu',
insert_link_target_same : 'Åpne i samme vindu',
insert_link_target_blank : 'Åpne i nytt vindu',
insert_image_title : 'Opprett/endre bilde',
insert_image_src : 'Bildets URL',
insert_image_alt : 'Bildets beskrivelse',
help_desc : 'Hjelp',
bold_img : 'bold_de_se.gif',
italic_img : 'italic_de_se.gif',
underline_img : 'underline.gif',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
