// PT lang variables, updated by X-fact0r (2006/01/27)

tinyMCE.addToLang('',{
bold_desc : 'Negrito',
italic_desc : 'Itálico',
underline_desc : 'Sublinhado',
striketrough_desc : 'Riscado',
justifyleft_desc : 'Alinhar á esquerda',
justifycenter_desc : 'Alinhar ao centro',
justifyright_desc : 'Alinhar á direita',
justifyfull_desc : 'Justificado',
bullist_desc : 'Lista não ordenada',
numlist_desc : 'Lista ordenada',
outdent_desc : 'Retirar indentação',
indent_desc : 'Indentar',
undo_desc : 'Desfazer',
redo_desc : 'Refazer',
link_desc : 'Inserir hiperligação',
unlink_desc : 'Remover hiperligação',
image_desc : 'Inserir referência a imagem externa',
object_desc : 'Inserir objecto multimédia da galeria',
cleanup_desc : 'Limpeza de código',
focus_alert : 'Uma instância do editor deverá estar seleccionada antes de utilizar este comando.',
edit_confirm : 'Deseja utilizar o modo visual de edição para esta área de texto?',
insert_link_title : 'Inserir/editar hiperligação',
insert : 'Inserir',
update : 'Actualizar',
cancel : 'Cancelar',
insert_link_url : 'URL da hiperligação',
insert_link_target : 'Destino',
insert_link_target_same : 'Abrir endereço na mesma janela',
insert_link_target_blank : 'Abrir endereço numa nova janela',
insert_image_title : 'Inserir/editar imagem',
insert_image_src : 'Endereço da imagem',
insert_image_alt : 'Descrição alt.',
help_desc : 'Ajuda',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copiar/Cortar/Colar não está disponível em Mozilla e Firefox.\nPretende obter mais informações acerca desta questão?',
popup_blocked : 'Lamentamos, mas verificámos que o seu popup-blocker desabilitou uma janela que contém algumas funções da aplicação. Necessita de desligar o bloquieo de popups neste site para poder utlizar todas as funções desta ferramenta.'
});
