// TH lang variables Thai contributed by Innozent

tinyMCE.addToLang('',{
bold_desc : 'ตัวหนา',
italic_desc : 'ตัว้เอียง',
underline_desc : 'ขีดเส้นใต้',
striketrough_desc : 'ขีดคล่อม',
justifyleft_desc : 'ชิดขอบซ้าย',
justifycenter_desc : 'กึ่งกลาง',
justifyright_desc : 'ชิดขอบขวา',
justifyfull_desc : 'จัดชิดขอบ',
bullist_desc : 'สัญลักษณ์แสดงหัวข้อย่อย',
numlist_desc : 'ลำดับเลข',
outdent_desc : 'ลดการเยื้อง',
indent_desc : 'เพิ่มการเยื้อง',
undo_desc : 'เลิกทำ',
redo_desc : 'ทำใหม่',
link_desc : 'เพิ่มลิงค์',
unlink_desc : 'ลบลิงค์',
image_desc : 'ใส่รูป',
cleanup_desc : 'ทำความสะอาดข้อความ',
focus_alert : 'ต้องเลือกกล่องข้อความก่อนที่จะใช้คำสั่งนี้',
edit_confirm : 'คุณต้องการที่จะใช้ WYSIWYG mode สำหรับกล่องข้อความนี้หรือไม่?',
insert_link_title : 'เพิ่ม/แก้ไข ลิงค์',
insert : 'เพิ่ม',
cancel : 'ยกเลิก',
insert_link_url : 'Link URL',
insert_link_target : 'เปิดลิงค์ใน',
insert_link_target_same : 'หน้าต่างเดียวกัน',
insert_link_target_blank : 'หน้าต่างใหม่',
insert_image_title : 'เพิ่ม/แก้ไข รูป',
insert_image_src : 'URL ของรูป',
insert_image_alt : 'คำอธิบายรูป',
help_desc : 'ช่วยเหลือ',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
