// Simplified Chinese lang variables contributed by cube316 (cube316@gmail.com)
//请访问 http://www.cube316.net/ 以获取TinyMCE的中文支持

tinyMCE.addToLang('',{
bold_desc : '粗体',
italic_desc : '斜体',
underline_desc : '下划线',
striketrough_desc : '删除线',
justifyleft_desc : '左对齐',
justifycenter_desc : '居中对齐',
justifyright_desc : '右对齐',
justifyfull_desc : '两端对齐',
bullist_desc : '无序列表',
numlist_desc : '有序列表',
outdent_desc : '减少缩进',
indent_desc : '增加缩进',
undo_desc : '撤消',
redo_desc : '重做',
link_desc : '插入/编辑 链接',
unlink_desc : '删除链接',
image_desc : '插入/编辑 图像',
cleanup_desc : '清除冗余代码',
focus_alert : '在使用此命令前某个编辑器必须先获得焦点！',
edit_confirm : '你想在此TextArea上使用所见即所得编辑器么？',
insert_link_title : '插入/编辑 链接',
insert : '插入',
update : '更新',
cancel : '取消',
insert_link_url : '链接地址',
insert_link_target : '目标',
insert_link_target_same : '在同一窗口中打开链接',
insert_link_target_blank : '在新窗口中打开链接',
insert_image_title : '插入/编辑 图像',
insert_image_src : '图像地址',
insert_image_alt : '图像描述',
help_desc : '帮助',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : '剪切/复制/粘贴功能在Mozilla和Firefox上尚不可用。\n你想了解关于这个问题的更多信息吗？',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
