// CZ lang variables thanks to "Pavel Novák"

tinyMCE.addToLang('',{
table_desc : 'Vložit novou tabulku',
table_insert_row_before_desc : 'Vložit øádek pøed',
table_insert_row_after_desc : 'Vložit øádek po',
table_delete_row_desc : 'Smazat øádek',
table_insert_col_before_desc : 'Vložit sloupec pøed',
table_insert_col_after_desc : 'Vložit sloupec po',
table_delete_col_desc : 'Odstranit sloupec',
insert_table_title : 'Vložit/upravit tabulku',
insert_table_width : 'Šíøka',
insert_table_height : 'Výška',
insert_table_cols : 'Sloupce',
insert_table_rows : 'Øádky',
insert_table_cellspacing : 'Vnìjší okraj bunìk',
insert_table_cellpadding : 'Vnitøní okraj bunìk',
insert_table_border : 'Rámeèek',
insert_table_align : 'Zarovnání',
insert_table_align_default : 'Výchozí',
insert_table_align_left : 'Vlevo',
insert_table_align_right : 'Vpravo',
insert_table_align_middle : 'Na støed',
insert_table_class : 'Class',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
