// Greek lang variables by Jacaranda Bill

tinyMCE.addToLang('',{
table_desc : 'Εισαγωγή πίνακα',
table_insert_row_before_desc : 'Εισαγωγή γραμμής επάνω',
table_insert_row_after_desc : 'Εισαγωγή γραμμής κάτω',
table_delete_row_desc : 'Διαγραφή γραμμής',
table_insert_col_before_desc : 'Εισαγωγή στήλης αριστερά',
table_insert_col_after_desc : 'Εισαγωγή στήλης δεξιά',
table_delete_col_desc : 'Διαγραφή στήλης',
insert_table_title : 'Εισαγωγή/Διόρθωση πίνακα',
insert_table_width : 'Πλάτος',
insert_table_height : 'Ύψος',
insert_table_cols : 'Στήλες',
insert_table_rows : 'Γραμμές',
insert_table_cellspacing : 'Διάστιχο',
insert_table_cellpadding : 'Γέμισμα',
insert_table_border : 'Περίγραμμα',
insert_table_align : 'Στοίχιση',
insert_table_align_default : 'Προκαθ.',
insert_table_align_left : 'Αριστερά',
insert_table_align_right : 'Δεξιά',
insert_table_align_middle : 'Στο κέντρο',
insert_table_class : 'Κλάση',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
