// ES lang variables by Alvaro Velasco

tinyMCE.addToLang('',{
table_desc : 'Insertar una tabla nueva',
table_insert_row_before_desc : 'Insertar una fila antes',
table_insert_row_after_desc : 'Insertar una fila despues',
table_delete_row_desc : 'Eliminar una fila',
table_insert_col_before_desc : 'Insertar una columna before',
table_insert_col_after_desc : 'Insertar columna after',
table_delete_col_desc : 'Eliminar una columna',
insert_table_title : 'Insertar/Modificar tabla',
insert_table_width : 'Anchura',
insert_table_height : 'Altura',
insert_table_cols : 'Columnas',
insert_table_rows : 'Filas',
insert_table_cellspacing : 'Espacio entre celdas',
insert_table_cellpadding : 'Desplazamiento entre celdas',
insert_table_border : 'Borde',
insert_table_align : 'Alineamiento',
insert_table_align_default : 'Por defecto',
insert_table_align_left : 'Izquierda',
insert_table_align_right : 'Derecha',
insert_table_align_middle : 'Centro',
insert_table_class : 'Class',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
