// FI lang variables by Urho Konttori from Absolutions

tinyMCE.addToLang('',{
table_desc : 'Lis‰‰ uusi taulu',
table_insert_row_before_desc : 'Lis‰‰ rivi edelle',
table_insert_row_after_desc : 'Lis‰‰ rivi j‰lkeen',
table_delete_row_desc : 'Posita rivi',
table_insert_col_before_desc : 'Lis‰‰ sarake edelle',
table_insert_col_after_desc : 'Lis‰‰ sarake j‰lkeen',
table_delete_col_desc : 'Poista sarake',
insert_table_title : 'Lis‰‰/muokkaa taulua',
insert_table_width : 'Leveys',
insert_table_height : 'Korkeus',
insert_table_cols : 'Sarakkeet',
insert_table_rows : 'Rivit',
insert_table_cellspacing : 'Solujen v‰li',
insert_table_cellpadding : 'Solun reunan ja sis‰llˆn v‰li',
insert_table_border : 'Reuna',
insert_table_align : 'Asettelu',
insert_table_align_default : 'Oletus',
insert_table_align_left : 'Vasen',
insert_table_align_right : 'Oikea',
insert_table_align_middle : 'Keskelle',
insert_table_delta_height'] = 20;
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
