// French lang variables by Laurent Dran

tinyMCE.addToLang('',{
table_desc : 'Ins&eacute;rer un nouveau tableau',
table_insert_row_before_desc : 'Ins&eacute;rer une ligne avant',
table_insert_row_after_desc : 'Ins&eacute;rer une ligne apr&eacute;s',
table_delete_row_desc : 'Supprimer la ligne',
table_insert_col_before_desc : 'Ins&eacute;rer une colonne avant',
table_insert_col_after_desc : 'Ins&eacute;rer une colonne apr&eacute;s',
table_delete_col_desc : 'Supprimer la colonne',
insert_table_title : 'Ins&eacute;rer/Modifier le tableau',
insert_table_width : 'Largeur',
insert_table_height : 'Hauteur',
insert_table_cols : 'Colonnes',
insert_table_rows : 'Lignes',
insert_table_cellspacing : 'Cellspacing',
insert_table_cellpadding : 'Cellpadding',
insert_table_border : 'Bordure',
insert_table_align : 'Alignement',
insert_table_align_default : 'D&eacute;faut',
insert_table_align_left : 'Gauche',
insert_table_align_right : 'Droit',
insert_table_align_middle : 'Milieu',
insert_table_class : 'Classe CSS',
table_row_title : 'Propri&eacute;t&eacute;s de la rang&eacute;e',
table_cell_title : 'Propri&eacute;t&eacute;s de la cellule',
table_row_desc : 'Propri&eacute;t&eacute;s de la rang&eacute;e',
table_cell_desc : 'Propri&eacute;t&eacute;s de la cellule',
insert_table_valign : 'Alignement Vertical',
insert_table_align_top : 'Haut',
insert_table_align_bottom : 'Bas',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
