// Canadian French lang variables by Virtuelcom   last modification: 2005-06-15

tinyMCE.addToLang('',{
table_desc : 'Ins&eacute;rer un nouveau tableau',
table_insert_row_before_desc : 'Ins&eacute;rer une ligne avant',
table_insert_row_after_desc : 'Ins&eacute;rer une ligne apr&egraves',
table_delete_row_desc : 'Supprimer la ligne',
table_insert_col_before_desc : 'Ins&eacute;rer une colonne avant',
table_insert_col_after_desc : 'Ins&eacute;rer une colonne apr&egraves',
table_delete_col_desc : 'Supprimer la colonne',
insert_table_title : 'Ins&eacute;rer/Modifier le tableau',
insert_table_width : 'Largeur',
insert_table_height : 'Hauteur',
insert_table_cols : 'Colonnes',
insert_table_rows : 'Lignes',
insert_table_cellspacing : 'Cellspacing',
insert_table_cellpadding : 'Cellpadding',
insert_table_border : 'Bordure',
insert_table_align : 'Alignement',
insert_table_align_default : 'D&eacute;faut',
insert_table_align_left : 'Gauche',
insert_table_align_right : 'Droit',
insert_table_align_middle : 'Milieu',
insert_table_class_name : 'Classe CSS',
table_row_title : 'Propri&eacute;t&eacute;s de ligne',
table_cell_title : 'Propri&eacute;t&eacute;s de cellule',
table_row_desc : 'Propri&eacute;t&eacute;s de ligne',
table_cell_desc : 'Propri&eacute;t&eacute;s de cellule',
insert_table_valign : 'Alignement vertical',
insert_table_align_top : 'Haut',
insert_table_align_bottom : 'Bas',
table_props_desc : 'Propri&eacute;t&eacute; du tableau ',
table_bordercolor : 'Couleur de la bordure',
table_bgcolor : 'Couleur Bg ',
table_merge_cells_title : 'Fusionner les cellules',
table_split_cells_desc : 'Fragmenter les cellules',
table_merge_cells_desc : 'Fusionner les cellules ',
table_cut_row_desc : 'Supprimer une ligne ',
table_copy_row_desc : 'Copier une ligne',
table_paste_row_before_desc : 'Copier une ligne apr&egrave;s',
table_paste_row_after_desc : 'Copier une ligne avant',
table_insert_desc : 'Ins&eacute;rer un nouveau tableau'
});
});
