// HU lang variables, Edited by 2XP (2xp@dino.hu)

tinyMCE.addToLang('',{
table_desc : '&#218;j t&#225;bl&#225;zat beilleszt&#233;se',
table_insert_row_before_desc : 'Sor beilleszt&#233;se el&#233;',
table_insert_row_after_desc : 'Sor beilleszt&#233;se ut&#225;na',
table_delete_row_desc : 'Sor t&#246;rl&#233;se',
table_insert_col_before_desc : 'Oszlop beillszt&#233;se el&#233;',
table_insert_col_after_desc : 'Oszlop beilleszt&#233;se ut&#225;na',
table_delete_col_desc : 'Oszlop elt&#225;vol&#237;t&#225;sa',
insert_table_title : 'T&#225;bla beilleszt&#233;se/m&#243;dos&#237;t&#225;sa',
insert_table_width : 'Sz&#233;less&#233;g',
insert_table_height : 'Magass&#225;g',
insert_table_cols : 'Oszlopok',
insert_table_rows : 'Sorok',
insert_table_cellspacing : 'Cellspacing',
insert_table_cellpadding : 'Cellpadding',
insert_table_border : 'Keret',
insert_table_align : 'Igaz&#237;t&#225;s',
insert_table_align_default : 'Alap&#233;rtelmezett',
insert_table_align_left : 'Balra',
insert_table_align_right : 'Jobbra',
insert_table_align_middle : 'K&#246;z&#233;pre',
insert_table_class : 'Class',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
