// Variabili di lingua IT - fabrix.xm@lombardiacom.it

tinyMCE.addToLang('',{
table_desc : 'Inserisci una nuova tabella',
table_insert_row_before_desc : 'Inserisci una riga prima',
table_insert_row_after_desc : 'Inserisci una riga dopo',
table_delete_row_desc : 'Cancella riga',
table_insert_col_before_desc : 'Inserisci colonna prima',
table_insert_col_after_desc : 'Inserisci colonna dopo',
table_delete_col_desc : 'Rimuovi colonna',
insert_table_title : 'Inserisci/modifica tabella',
insert_table_width : 'Larghezza',
insert_table_height : 'Altezza',
insert_table_cols : 'Colonne',
insert_table_rows : 'Righe',
insert_table_cellspacing : 'Cellspacing',
insert_table_cellpadding : 'Cellpadding',
insert_table_border : 'Bordo',
insert_table_align : 'Allineamento',
insert_table_align_default : 'Default',
insert_table_align_left : 'Sinistra',
insert_table_align_right : 'Destra',
insert_table_align_middle : 'Centro',
insert_table_class : 'Classe',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
