// KO lang variables

tinyMCE.addToLang('',{
table_desc : '표 넣기',
table_insert_row_before_desc : '앞에 행 넣기',
table_insert_row_after_desc : '뒤에 행 넣기',
table_delete_row_desc : '행 지우기',
table_insert_col_before_desc : '앞에 열 넣기',
table_insert_col_after_desc : '뒤에 열 넣기',
table_delete_col_desc : '열 지우기',
insert_table_title : '표 넣기/고치기',
insert_table_width : '너비',
insert_table_height : '높이',
insert_table_cols : '행',
insert_table_rows : '열',
insert_table_cellspacing : '셀 간격',
insert_table_cellpadding : '셀 여백',
insert_table_border : '테두리',
insert_table_align : '정렬',
insert_table_align_default : '기본값',
insert_table_align_left : '왼쪽',
insert_table_align_right : '오른쪽',
insert_table_align_middle : '가운데',
insert_table_class : '클래스',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
