// NL lang variables

tinyMCE.addToLang('',{
table_desc : 'Voeg een nieuwe tabel in',
table_insert_row_before_desc : 'Voeg rij in voor ...',
table_insert_row_after_desc : 'Voeg rij in na ...',
table_delete_row_desc : 'Verwijder rij',
table_insert_col_before_desc : 'Voeg kolom in voor ...',
table_insert_col_after_desc : 'Voeg kolom in na ...',
table_delete_col_desc : 'Verwijder kolom',
insert_table_title : 'Invoegen/Bewerken tabel',
insert_table_width : 'Breedte',
insert_table_height : 'Hoogte',
insert_table_cols : 'Kolommen',
insert_table_rows : 'Rijen',
insert_table_cellspacing : 'Celafstand',
insert_table_cellpadding : 'Celvulling',
insert_table_border : 'Omranding',
insert_table_align : 'Positionering',
insert_table_align_default : 'Standaard',
insert_table_align_left : 'Links',
insert_table_align_right : 'Rechts',
insert_table_align_middle : 'Midden',
insert_table_class : 'CSS-Stijl',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
