// NO lang variables

tinyMCE.addToLang('',{
table_desc : 'Opprett/endre tabell',
table_insert_row_before_desc : 'Opprett rad før',
table_insert_row_after_desc : 'Opprett rad etter',
table_delete_row_desc : 'Fjern rad',
table_insert_col_before_desc : 'Opprett kolonne før',
table_insert_col_after_desc : 'Opprett kolonne etter',
table_delete_col_desc : 'Fjern kolonne',
insert_table_title : 'Opprett/endre tabell',
insert_table_width : 'Bredde',
insert_table_height : 'Høyde',
insert_table_cols : 'Kolonner',
insert_table_rows : 'Rader',
insert_table_cellspacing : 'Celle-mellomrom',
insert_table_cellpadding : 'Celle-padding',
insert_table_border : 'Rammebredde',
insert_table_align : 'Justering',
insert_table_align_default : 'Ingen',
insert_table_align_left : 'Venstre',
insert_table_align_right : 'Høyre',
insert_table_align_middle : 'Midten',
insert_table_class : 'Stil',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
