// PL lang variables

tinyMCE.addToLang('',{
table_desc : 'Wstaw nowa tabele',
table_insert_row_before_desc : 'Wstaw wiersz przed',
table_insert_row_after_desc : 'Wstaw wiersz po',
table_delete_row_desc : 'Skasuj wiersz',
table_insert_col_before_desc : 'Wstaw kolumne przed',
table_insert_col_after_desc : 'Wstaw kolumne po',
table_delete_col_desc : 'Skasuj kolumne',
insert_table_title : 'Wstaw/Modyfikuj tabele',
insert_table_width : 'Szerokosc',
insert_table_height : 'Wysokosc',
insert_table_cols : 'Kolumny',
insert_table_rows : 'Wiersze',
insert_table_cellspacing : 'Cellspacing',
insert_table_cellpadding : 'Cellpadding',
insert_table_border : 'Ramka',
insert_table_align : 'Wyrównanie',
insert_table_align_default : 'Domyslny',
insert_table_align_left : 'Do lewej',
insert_table_align_right : 'Do prawej',
insert_table_align_middle : 'Wycentrowanie',
insert_table_class : 'Klasa',
table_row_title : 'Wlasciwosci wiersza',
table_cell_title : 'Wlasciwosci komórki',
table_row_desc : 'Wlasciwosci wiersza',
table_cell_desc : 'Wlasciwosci komórki',
insert_table_valign : 'Wyrównanie pionowe',
insert_table_align_top : 'do góry',
insert_table_align_bottom : 'do dolu',
table_props_desc : 'Wlasciwosci tabeli',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
