// PT lang variables by X-fact0r (2006/01/27)

tinyMCE.addToLang('table',{
general_tab : 'Geral',
advanced_tab : 'Avançado',
general_props : 'Propriedades Gerais',
advanced_props : 'Propriedades Avançadas',
desc : 'Inserir uma nova tabela',
row_before_desc : 'Inserir uma linha antes',
row_after_desc : 'Inserir uma linha depois',
delete_row_desc : 'Apagar linha',
col_before_desc : 'Inserir uma coluna antes',
col_after_desc : 'Inserir uma coluna depois',
delete_col_desc : 'Remover coluna',
rowtype : 'Linhas na tabela parcial',
title : 'Inserir/Modificar Tabela',
width : 'Largura',
height : 'Altura',
cols : 'Colunas',
rows : 'Linhas',
cellspacing : 'Espaçamento das células',
cellpadding : 'Margem interna',
border : 'Contorno',
align : 'Alinhamento',
align_default : 'Padrão',
align_left : 'Esquerda',
align_right : 'Direita',
align_middle : 'Centrado',
row_title : 'Propriedades das linhas',
cell_title : 'Propriedades das células',
cell_type : 'Tipo de célula',
row_desc : 'Propriedades das linhas',
cell_desc : 'Propriedades das células',
valign : 'Alinhamento vertical',
align_top : 'Cima',
align_bottom : 'Baixo',
props_desc : 'Propriedades da tabela',
bordercolor : 'Cor do contorno',
bgcolor : 'Cor do fundo',
merge_cells_title : 'Juntar células',
split_cells_desc : 'Separar células',
merge_cells_desc : 'Juntar células',
split_cells_title : 'Separar células',
cut_row_desc : 'Apagar linha',
copy_row_desc : 'Copiar linha',
paste_row_before_desc : 'Colar linha antes',
paste_row_after_desc : 'Colar linha depois',
id : 'Id',
style: 'Estilo',
langdir : 'Direção do texto',
langcode : 'Código do idioma',
mime : 'Tipo MIME do objeto',
ltr : 'Esquerda para direita',
rtl : 'Direita para esquerda',
bgimage : 'Imagem de fundo',
summary : 'Sumário',
td : "Dados",
th : "Cabeçalho",
cell_cell : 'Actulizar célula actual',
cell_row : 'Actualizar todas as células na linha',
cell_all : 'Actualizar todas as células na tabela',
row_row : 'Actualizar linha actual',
row_odd : 'Actualizar linhas ímpares na tabela',
row_even : 'Actualizar linhas pares na tabela',
row_all : 'Actualizar todas as linhas na tabela',
thead : 'Cabeçalho da tabela',
tbody : 'Corpo da tabela',
tfoot : 'Rodapé da tabela',
del : 'Apagar tabela',
dir : 'Direcção',
scope : 'Range/Destino',
row : 'Linha',
col : 'Coluna',
rowgroup : 'Grupo de linhas',
colgroup : 'Grupo de colunas',
missing_scope: 'Tem certeza que deseja continuar sem especificar um range/destino para este célula de cabeçalho. Desta forma poderá criar dificuldades a alguns utilizadores com disfunções em entenderem o conteúdo ou visualizarem a tabela.'
});
