// SE lang variables

tinyMCE.addToLang('table',{
desc : 'Skapa ny tabell',
insert_row_before_desc : 'Skapa rad f&ouml;re',
insert_row_after_desc : 'Skapa rad efter',
delete_row_desc : 'Ta bort rad',
insert_col_before_desc : 'Skapa kolumn f&ouml;re',
insert_col_after_desc : 'Skapa kolumn efter',
delete_col_desc : 'Ta bort kolumn',
title : 'Skapa/Redigera tabell',
width : 'Bredd',
height : 'H&ouml;jd',
cols : 'Kolumner',
rows : 'Rader',
cellspacing : 'Cellmellanrum',
cellpadding : 'Cellutfyllnad',
border : 'Rambredd',
align : 'Justering',
align_default : 'Ingen',
align_left : 'V&auml;nster',
align_right : 'H&ouml;ger',
align_middle : 'Mitten',
class : 'Stil',
row_title : 'Tabellradsinst&auml;llningar',
cell_title : 'Tabellcellsinst&auml;llningar',
row_desc : 'Tabellradsinst&auml;llningar',
cell_desc : 'Tabellcellsinst&auml;llningar',
valign : 'Vertikal justering',
align_top : 'Toppen',
align_bottom : 'Botten',
props_desc : 'Tabell egenskaper',
bordercolor : 'Ramf&auml;rg',
bgcolor : 'Bakgrundsfärd',
merge_cells_title : 'Sammanfoga tabell celler',
split_cells_desc : 'Delaupp tabell celler',
merge_cells_desc : 'Sammanfoga tabell celler',
cut_row_desc : 'Klipput tabell rad',
copy_row_desc : 'Kopiera tabell rad',
paste_row_before_desc : 'Klistra in tabell rad f&ouml;re',
paste_row_after_desc : 'Klistra in tabell rad efter',
insert_desc : 'Insert a new table'
});
