/*
+ ----------------------------------------------------------------------------+
|     Swedish (SE) language variables
|
|     $Source: /cvs_backup/e107_langpacks/e107_handlers/tiny_mce/plugins/table/langs/sv.js,v $
|     $Revision: 1.3 $
|     $Date: 2006-01-24 12:42:35 $
|     $Author: mrpiercer $
+----------------------------------------------------------------------------+
*/

tinyMCE.addToLang('table',{
general_tab : 'Generella inställningar',
advanced_tab : 'Avancerade inställningar',
general_props : 'Generella inställningar',
advanced_props : 'Avancerade inställningar',
desc : 'Skapa ny tabell',
before_desc : 'Skapa rad före',
after_desc : 'Skapa rad efter',
row_before_desc : 'Skapa rad före',
row_after_desc : 'Skapa rad efter',
delete_row_desc : 'Ta bort rad',
col_before_desc : 'Skapa kolumn före',
col_after_desc : 'Skapa kolumn efter',
delete_col_desc : 'Ta bort kolumn',
rowtype : 'Rad typ',
title : 'Skapa/redigera ny tabell',
width : 'Bredd',
height : 'Höjd',
cols : 'Columner',
rows : 'Rader',
cellspacing : 'Cellmellanrum',
cellpadding : 'Cellutfyllnad',
border : 'Ram',
align : 'Justering',
align_default : 'Ingen',
align_left : 'Vänster',
align_right : 'Höger',
align_middle : 'Mitten',
row_title : 'Tabell radsinställningar',
cell_title : 'Tabell cellsinställningar',
cell_type : 'Cell typ',
row_desc : 'Tabell rads inställningar',
cell_desc : 'Tabell cells inställningar',
valign : 'Vertical justering',
align_top : 'Toppen',
align_bottom : 'Botten',
props_desc : 'Tabell inställningar',
bordercolor : 'Ram färg',
bgcolor : 'Bakgrundsfärg',
merge_cells_title : 'Sammanfoga tabell celler',
split_cells_desc : 'Delaupp tabell celler',
merge_cells_desc : 'Sammanfoga tabell celler',
cut_row_desc : 'Klipput tabell rad',
copy_row_desc : 'Kopiera tabell rad',
paste_row_before_desc : 'Klistra in tabell rad före',
paste_row_after_desc : 'Klistra in tabell rad efter',
id : 'Id',
style: 'Stil',
langdir : 'Skrift riktning',
langcode : 'Språk kåd',
ltr : 'Vänster till höger',
rtl : 'Höger till vänster',
bgimage : 'Bakgrundsbild',
summary : 'Sammanfattning',
td : "Data",
th : "Huvud",
cell_cell : 'Updatera nuvarande cell',
cell_row : 'Updatera alla celler i raden',
cell_all : 'Updatera alla celler t tabellen',
row_row : 'Updatera nuvarande rad',
row_odd : 'Updatera udda rader i tabellen',
row_even : 'Updatera jämna rader i tabellen',
row_all : 'Updatera alla rader i tabellen',
thead : 'Tabell Huvud',
tbody : 'Tabell Kropp',
tfoot : 'Tabell Fot',
del : 'Tabort tabell',
scope : 'Scope',
row : 'Rad',
col : 'Kolumn',
rowgroup : 'Rad grupp',
colgroup : 'Kolumn grupp',
missing_scope: 'Är du säker på att du vill fortsätta utan att specifisera ett scope, utan denna kan det bli svårt för handikappade att förstå tabellen.'
});
