// Simplified Chinese lang variables contributed by cube316 (cube316@gmail.com)
//请访问 http://www.cube316.net/ 以获取TinyMCE的中文支持

tinyMCE.addToLang('',{
table_desc : '插入新表格',
table_insert_row_before_desc : '在前面插入行',
table_insert_row_after_desc : '在后面插入行',
table_delete_row_desc : '删除行',
table_insert_col_before_desc : '在前面插入列',
table_insert_col_after_desc : '在后面插入列',
table_delete_col_desc : '删除列',
insert_table_title : '插入/修改 表格',
insert_table_width : '宽度',
insert_table_height : '高度',
insert_table_cols : '列数',
insert_table_rows : '行数',
insert_table_cellspacing : '间距',
insert_table_cellpadding : '填充',
insert_table_border : '边框',
insert_table_align : '对齐方式',
insert_table_align_default : '默认',
insert_table_align_left : '左对齐',
insert_table_align_right : '右对齐',
insert_table_align_middle : '居中对齐',
insert_table_class_name : '类',
table_row_title : '表格行属性',
table_cell_title : '单元格属性',
table_row_desc : '表格行属性',
table_cell_desc : '单元格属性',
insert_table_valign : '垂直对齐',
insert_table_align_top : '顶端',
insert_table_align_bottom : '底部',
table_props_desc : '表格属性',
table_bordercolor : '边框颜色',
table_bgcolor : '背景颜色',
table_merge_cells_title : '合并单元格',
table_split_cells_desc : '拆分单元格',
table_merge_cells_desc : '合并单元格',
table_cut_row_desc : '剪切行',
table_copy_row_desc : '复制行',
table_paste_row_before_desc : '在前面插入行',
table_paste_row_after_desc : '在后面插入行',
table_insert_desc : 'Insert a new table'
});
