<?php
/*
+ ----------------------------------------------------------------------------+
|     e107 website system - Language File.
|
|     $Source: /cvs_backup/e107_langpacks/legacy_langpacks/e107_plugins/content/languages/Swedish/lan_content_help.php,v $
|     $Revision: 1.1 $
|     $Date: 2005-09-17 14:44:06 $
|     $Author: mrpiercer $
+----------------------------------------------------------------------------+
*/

define("CONTENT_ADMIN_HELP_1", "Inneh&aring;llshantering hj&auml;lp");

define("CONTENT_ADMIN_HELP_ITEM_1", "<i>Om du &auml;nnu inte lagt till n&aring;gra huvudv&auml;rdkategorier, g&ouml; det nu p&aring; sidan <a href='".e_SELF."?cat.create'>Skapa ny kategori</a>.</i><br /><br /><b>Kategori</b><br />V&auml;lj en kategori fr&aring;n rullgardinsmenyn f&ouml;r att hantera inneh&aring;ll f&ouml;r den kategorin.<br /><br />Om du v&auml;ljer en huvudv&auml;rdkategori fr&aring;n menyn kommer allt inneh&aring;ll i den huvudkategorin att visas.<br />V&auml;ljer du en underkategori kommer enbart inneh&aring;llet under den underkategorin att visas.<br /><br />Du kan ocks&aring; anv&auml;nda menyn till h&ouml;ger f&ouml;r att visa allt inneh&aring;ll i en specificerad kategori.");

define("CONTENT_ADMIN_HELP_ITEM_2", "<b>F&ouml;rsta bokst&auml;verna</b><br />Om du klickar p&aring; en bokstavsknapp kommer endast inneh&aring;ll med denna initialbokstav i rubriken att visas. V&auml;ljer du knappen 'alla' s&aring; kommer en lista med alla objekt i den valda kategorin att visas.<br /><br /><b>Detaljerad lista</b><br />Visar en lista &ouml;ver allt inneh&aring;ll med dess id, ikon, f&ouml;rfattare, rubrik [underrubrik] och alternativ.<br /><br /><b>F&ouml;rklaring av ikoner</b><br />".CONTENT_ICON_USER." : L&auml;nk till f&ouml;rfattarens profil<br />".CONTENT_ICON_LINK." : L&auml;nk till inneh&aring;llsobjektet<br />".CONTENT_ICON_EDIT." : Redigera inneh&aring;llsobjektet<br />".CONTENT_ICON_DELETE." : Radera inneh&aring;llsobjektet<br />");

define("CONTENT_ADMIN_HELP_ITEMEDIT_1", "<b>Redigeringsformul&auml;r</b><br />H&auml;r kan du redigera all information f&ouml;r detta objekt och spara dina &auml;ndringar.<br /><br />Om du beh&ouml;ver byta kategori f&ouml;r objektet, g&ouml;r det f&ouml;rst. Efter att du valt r&auml;tt kategori, &auml;ndra eller l&auml;gg till f&auml;lt innan du sparar &auml;ndringarna.");

define("CONTENT_ADMIN_HELP_ITEMCREATE_1", "<b>Kategori</b><br />V&auml;lj den kategori fr&aring;n rutan f&ouml;r att skapa ett nytt objekt i den.<br />");

define("CONTENT_ADMIN_HELP_ITEMCREATE_2", "<b>Formul&auml;r f&ouml;r att skapa</b><br />H&auml;r anger du all information f&ouml;r detta inneh&aring;llsobjekt och sparar det.<br /><br />T&auml;nk p&aring; att olika huvudkategorier kan ha olika preferensinst&auml;llningar s&aring; det kan finna olika f&auml;lt att fylla i. D&auml;rf&ouml;r m&aring;ste du alltid v&auml;lja kategori innan du fyller i n&aring;got i de andra f&auml;lten!");

define("CONTENT_ADMIN_HELP_CAT_1", "<i>Denna sida visar alla tillg&auml;ngliga kategorier och underkategorier.</i><br /><br /><b>Detaljerad lista</b><br />H&auml;r ser du en lista p&aring; alla underkategorier med dess id, ikon, f&ouml;rfattare, kategori [underrubrik] och alternativ.<br /><br /><b>F&ouml;rklaring av ikoner</b><br />".CONTENT_ICON_USER." : L&auml;nk till f&ouml;rfattarens profil<br />".CONTENT_ICON_LINK." : L&auml;nk till kategorin<br />".CONTENT_ICON_EDIT." : Redigera kategorin<br />".CONTENT_ICON_DELETE." : Radera kategorin<br />");

define("CONTENT_ADMIN_HELP_CAT_2", "<i>Denna sida l&aring;ter dig skapa en ny kategori</i><br /><br />V&auml;lj alltid en v&auml;rdkategori innan du fyller i de andra f&auml;lten!<br /><br />Detta m&aring;ste g&ouml;ras eftersom egenskaper unika f&ouml;r varje kategori m&aring;ste laddas av systemet.<br /><br />Som standard visas sidan f&ouml;r att skapa en ny hyvydkategori.");

define("CONTENT_ADMIN_HELP_CAT_3", "<i>Denna sida visar formul&auml;ret f&ouml;r att redigera kategori.</i><br /><br /><b>Kategori redigering</b><br />H&auml;r kan du &auml;ndra all information f&ouml;r denna (under)kategori och spara dina &auml;ndringar.<br /><br />Om du vill byta v&auml;rd f&ouml;r denna kategori, g&ouml;r det f&ouml;rst. Efter att du valt r&auml;tt v&auml;rd kan du &auml;ndra de &ouml;vriga f&auml;lten.");

define("CONTENT_ADMIN_HELP_ORDER_1", "<i>Denna sida visar alla tillg&auml;ngliga kategorier och underkategorier.</i><br /><br /><b>Detaljerad lista</b><br />H&auml;r ser du kategorins id och namn. Du ser ocks&aring; flera alternativ f&ouml;r att hantera ordningen p&aring; kategorierna.<br /><br /><b>F&ouml;rklaring av ikoner</b><br />".CONTENT_ICON_USER." : L&auml;nk till f&ouml;rfattarens profil<br />".CONTENT_ICON_LINK." : L&auml;nk till kategorin<br />".CONTENT_ICON_ORDERALL." : Hantera den globala ordningen av inneh&aring;llsobjekt oavsett kategori.<br />".CONTENT_ICON_ORDERCAT." : Hantera ordningen av inneh&aring;llsobjekt i den specifika kategorin.<br />".CONTENT_ICON_ORDER_UP." : Upp&aring;tknappen flyttar objektet ett steg upp&aring;t i ordningen.<br />".CONTENT_ICON_ORDER_DOWN." : Ned&aring;tknappen flyttar objektet ett steg ned&aring;t i ordningen.<br /><br /><b>Ordning</b><br />H&auml;r kan du manuellt ange ordningen p&aring; alla kategorier i varje v&auml;rd. Du &auml;ndrar v&auml;rdet i valrutorna och klickar sedan p&aring; knappen f&ouml;r uppdatering nedan f&ouml;r att spara den.<br />");

define("CONTENT_ADMIN_HELP_ORDER_2", "<i>Denna sida visar alla inneh&aring;llsobjekt i kategorin du valt.</i><br /><br /><b>Detaljerad lista</b><br />Du ser h&auml;r inneh&aring;llsobjektets id, f&ouml;rfattare och rubrik. Du ser ocks&aring; flera alternativ f&ouml;r att hantera ordningen p&aring; objekten.<br /><br /><b>F&ouml;rklaring av ikoner</b><br />".CONTENT_ICON_USER." : L&auml;nk till f&ouml;rfattarens profil<br />".CONTENT_ICON_LINK." : L&auml;nk till objektet<br />".CONTENT_ICON_ORDER_UP." : Upp&aring;tknappen flyttar objektet ett steg upp&aring;t i ordningen.<br />".CONTENT_ICON_ORDER_DOWN." : Ned&aring;tknappen flyttar objektet ett steg ned&aring;t i ordningen.<br /><br /><b>Ordning</b><br />H&auml;r s&auml;tter du manuellt ordningen p&aring; alla kategorierna i denna huvudv&auml;rd. Du &auml;ndrar v&auml;rdet i valrutorna och klickar sedan p&aring; knappen f&ouml;r uppdatering nedan f&ouml;r att spara den.<br />");

define("CONTENT_ADMIN_HELP_ORDER_3", "<i>Denna sida visar alla inneh&aring;llsobjekt i den huvudv&auml;rdkategori du valt.</i><br /><br /><b>Detaljerad lista</b><br />Du ser objektets id, f&ouml;rfattare och rubrik. Du ser ocks&aring; flera alternativ f&ouml;r att hantera ordningen p&aring; objekten.<br /><br /><b>F&ouml;rklaring av ikoner</b><br />".CONTENT_ICON_USER." : L&auml;nk till f&ouml;rfattarens profil<br />".CONTENT_ICON_LINK." : L&auml;nk till objektet<br />".CONTENT_ICON_ORDER_UP." : Upp&aring;tknappen flyttar objektet ett steg upp&aring;t i ordningen.<br />".CONTENT_ICON_ORDER_DOWN." : Ned&aring;tknappen flyttar objektet ett steg ned&aring;t i ordningen.<br /><br /><b>Ordning</b><br />H&auml;r s&auml;tter du manuellt ordningen p&aring; alla kategorierna i denna huvudv&auml;rd. Du &auml;ndrar v&auml;rdet i valrutorna och klickar sedan p&aring; knappen f&ouml;r uppdatering nedan f&ouml;r att spara den.<br />");

define("CONTENT_ADMIN_HELP_OPTION_1", "P&aring; denna sida v&auml;ljer du en huvudv&auml;rdkategori att s&auml;tta alternativ f&ouml;r eller s&aring; kan du v&auml;lja att redigera standardpreferenserna.<br /><br /><b>F&ouml;rklaring av ikoner</b><br />".CONTENT_ICON_USER." : L&auml;nk till f&ouml;rfattarens profil<br />".CONTENT_ICON_LINK." : L&auml;nk till kategorin<br />".CONTENT_ICON_OPTIONS." : Redigera alternativen<br /><br /><br />Standardprefernserna anv&auml;nds bara n&auml;r du skapar en ny v&auml;rd. S&aring; n&auml;r du skapar en ny huvudv&auml;rd kommer dessa inst&auml;llningar att sparas. Du kan &auml;ndra dessa f&ouml;r att f&ouml;rs&auml;kra dig om att nyskapade v&auml;rdar alltid har en viss upps&auml;ttning alternativ tillg&auml;ngliga.<br /><br />Varje huvudv&auml;rd har sina egna inst&auml;llningar som &auml;r unika f&ouml;r den specifika huvudv&auml;rdkategorin");

//define("CONTENT_ADMIN_HELP_OPTION_2", "<i>Denna sida visar de alternativ du kan s&auml;tta f&ouml;r denna v&auml;rd. Varje v&auml;rd har sin egen upps&auml;ttning alternativ, s&aring; f&ouml;rs&auml;kra dig om att alla s&auml;tts korrekt.</i><br /><br />");
//<b>Standardv&auml;rden</b><br />Som standard finns alla v&auml;rden och &auml;r uppdaterade i preferenser n&auml;r du tittar p&aring; denna sidan, men du m&aring;ste g&aring; genom och &auml;ndra alla v&auml;rden efter dina behov.<br /><br />
define("CONTENT_ADMIN_HELP_MANAGER_1", "P&aring; denna sida ser du en lista &ouml;ver alla kategorier. Du kan hantera den 'Personliga inneh&aring;llshanteraren' f&ouml;r varje kategori genom att klicka p&aring; ikonen.<br /><br /><b>F&ouml;rklaring av ikoner</b><br />".CONTENT_ICON_USER." : L&auml;nk till f&ouml;rfattarens profil<br />".CONTENT_ICON_LINK." : L&auml;nk till kategorin<br />".CONTENT_ICON_CONTENTMANAGER_SMALL." : Redigera personliga inneh&aring;llshanterare<br />");

define("CONTENT_ADMIN_HELP_MANAGER_2", "<i>P&aring; denna sida kan du tilldela anv&auml;ndare till den valda kategorin du har klickat</i><br /><br /><b>Personlig hanterare</b><br />Du kan tilldela anv&auml;ndare till s&auml;rskilda kategorier. Genom att g&ouml;ra det kan dessa anv&auml;ndare hantera sina egna personliga inneh&aring;llsobjekt utanf&ouml;r adminsektionen (content_manager.php).<br /><br />Tilldela anv&auml;ndare genom att klicka p&aring; deras namn i den v&auml;nstra kolumnen, d&aring; ser du att namnet flyttas till den h&ouml;gra kolumnen. Efter att du klickat p&aring; tilldelningsknappen kommer anv&auml;ndarna i den h&ouml;gra kolumnen att tilldelas r&auml;ttigheten i denna kategorin.");

define("CONTENT_ADMIN_HELP_SUBMIT_1", "<i>P&aring; denna sidan ser du allt inneh&aring;ll som s&auml;nts in av anv&auml;ndare.</i><br /><br /><b>Detaljerad lista</b><br />Du ser en lista med dessa inneh&aring;llsobjekt och deras id, ikon, v&auml;rd, rubrik [underrubrik], f&ouml;rfattare och alternativ.<br /><br /><b>Alternativ</b><br />Du kan posta eller radera ett objekt med de visade knapparna.");



define("CONTENT_ADMIN_HELP_OPTION_DIV_1", "Denna sidan l&aring;ter dig s&auml;tta alternativen f&ouml;r admins sida att skapa objekt.<br /><br />Du kan ange vilka sektioner som skall vara tillg&auml;ngliga n&auml;r admin (eller personlig hanterare) skapar ett nytt inneh&aring;llsobjekt<br /><br /><b>Egna datataggar</b><br />Du kan till&aring;ta att anv&auml;ndare eller admin kan l&auml;gga till egna f&auml;lt till objektet genom dessa egna datataggar. De egna f&auml;lten &auml;r tomma nyckel=>v&auml;rde par. T.ex: Du kan l&auml;gga till ett nyckelf&auml;lt f&ouml;r 'fotograf' och ange ett v&auml;rde med 'alla foton av mig'. B&aring;da nyckel och v&auml;rde f&auml;lt &auml;r tomma textrutor som kommer att visas i formul&auml;ret f&ouml;r att skapa inneh&aring;ll.<br /><br /><b>F&ouml;rinst&auml;llda datataggar</b><br />Ut&ouml;ver egna datataggar kan du &auml;ven skapa f&ouml;rinst&auml;llda datataggar. Skillnaden &auml;r att i de f&ouml;rinst&auml;llda datataggarna &auml;r nyckelv&auml;rdet redan angivet och anv&auml;ndaren beh&ouml;ver bara fylla i v&auml;rdef&auml;ltet f&ouml;r taggen. I samma exempel som ovan kan 'fotografr' vara f&ouml;rinst&auml;llt och anv&auml;ndaren m&aring;ste ange 'alla foton av mig'. Du kan v&auml;lja elementtyp genom att v&auml;lja i valrutan. I popup-f&ouml;nstret kan du ange all information f&ouml;r den f&ouml;rinst&auml;llda datataggen.<br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_2", "Skicka in alternativ har effekt p&aring; anv&auml;ndarens formul&auml;r f&ouml;r att skicka in inneh&aring;ll.<br /><br />Du kan ange vilka delar som skall vara tillg&auml;ngliga f&ouml;r en anv&auml;ndare som s&auml;nder in inneh&aring;ll.<br /><br />".CONTENT_ADMIN_OPT_LAN_11.":<br />".CONTENT_ADMIN_OPT_LAN_12."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_3", "I s&ouml;kv&auml;g och tema alternativen anger du var bilder och filer skall sparas.<br /><br />Du kan ocks&aring; ange vilket tema som skall anv&auml;ndas av denna v&auml;rd. Du kan skapa ytterligare teman genom att kopiera (och byta namn) p&aring; hela 'default' katalogen i ditt mallbibliotek.<br /><br />Du kan ange ett standard layoutschema f&ouml;r nya inneh&aring;llsobjekt. Du kan skapa nya layoutscheman genom att skapa en content_content_template_XXX.php fil i din 'templates/default' folder. Dessa layouter kan anv&auml;ndas f&ouml;r att ge varje inneh&aring;llsobjekt under denna v&auml;rd egna layouter.<br /><br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_4", "De generella alternativen &auml;r de alternativ som anv&auml;nds genom allt inneh&aring;ll i hela inneh&aring;llspluginen.");

define("CONTENT_ADMIN_HELP_OPTION_DIV_5", "TDessa alternativ har effekt p&aring; den personliga inneh&aring;llshanteraren i inneh&aring;llshanteringens admin area.<br /><br />".CONTENT_ADMIN_OPT_LAN_63."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_6", "Dessa alternativ anv&auml;nds i menyn f&ouml;r denna v&auml;rd om du aktiverat menyn.<br /><br />".CONTENT_ADMIN_OPT_LAN_68."<br /><br />".CONTENT_ADMIN_OPT_LAN_118.":<br />".CONTENT_ADMIN_OPT_LAN_119."<br /><br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_7", "F&ouml;rhandsgranskning av inneh&aring;llsobjekt har effekt p&aring; en lite f&ouml;rhandsgranskning som &auml;r m&ouml;jlig f&ouml;r varje objekt.<br /><br />Denna f&ouml;rhandsgranskning finns p&aring; ett flertal sidor som tidiagare sida, visa objekt i kategori sida och visa objekt fr&aring;n f&ouml;rfattares sida.<br /><br />".CONTENT_ADMIN_OPT_LAN_68."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_8", "Kategorisidorna visar information om inneh&aring;llskategorierna i denna v&auml;rd.<br /><br />Det finns tv&aring; distinkta areor n&auml;rvarande:<br /><br />All kategorier:<br />Denna sida visar alla kategorier under denna v&auml;rd<br /><br />Visa kategori sida:<br />Denna sida visar kategorin, eventuella underkategorier till kategorin och objekten i kategorin/underkategorierna<br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_9", "Inneh&aring;llssidan visar inneh&aring;llsobjektet.<br /><br />Du kan ange vilka sektioner att visa genom att markera/avmarkera i rutorna.<br /><br />Du kan visa e-postadressen till en f&ouml;rfattare som inte &auml;r medlem h&auml;r.<br /><br />Du kan &aring;sidos&auml;tta e-post/skriv ut/pdf ikonerna, betygssystemet och kommentarerna.<br /><br />".CONTENT_ADMIN_OPT_LAN_74."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_10", "F&ouml;rfattarsidan visar en lista med alla f&ouml;rfattare av inneh&aring;ll under denna v&auml;rd.<br /><br />Du kan ange vilka sektioner att visa genom att markera/avmarkera i rutorna.<br /><br />Du kan begr&auml;nsa antal objekt att visa per sida.<br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_11", "Arkivsidan visar allt inneh&aring;ll under denna v&auml;rd.<br /><br />Du kan ange vilka sektioner att visa genom att markera/avmarkera i rutorna.<br /><br />Du kan ange om e-postadressen till en f&ouml;rfattare som inte &auml;r medlem h&auml;r skall visas.<br /><br />Du kan begr&auml;nsa antal objekt att visa per sida.<br /><br />".CONTENT_ADMIN_OPT_LAN_66."<br /><br />".CONTENT_ADMIN_OPT_LAN_68."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_12", "Toppbetygssidan visa allt inneh&aring;ll som blivit betygssatt av anv&auml;ndare.<br /><br />Du kan ange vilka sektioner att visa genom att markera/avmarkera i rutorna.<br /><br />Du kan ange om e-postadressen till en f&ouml;rfattare som inte &auml;r medlem h&auml;r skall visas.");

define("CONTENT_ADMIN_HELP_OPTION_DIV_13", "Topprankningssidan visar allt innh&aring;ll som har f&aring;tt en rankning satt av f&ouml;rfattaren till inneh&aring;llet.<br /><br />Du kan ange vilka sektioner att visa genom att markera/avmarkera i rutorna.<br /><br />Du kan ange om e-postadressen till en f&ouml;rfattare som inte &auml;r medlem h&auml;r skall visas.");

?>
