<?php
/*
+----------------------------------------------------------------------------+
|     e107 website system - PT Language File.
|
|     $Revision: 1.1 $
|     $Date: 2006-04-15 21:09:14 $
|     $Author: e107coders $
+----------------------------------------------------------------------------+
*/
define("CONTENT_ADMIN_HELP_1", "Ajuda = Área de Gestão de Conteúdos");

define("CONTENT_ADMIN_HELP_ITEM_1", "<i>Se aínda não adicionou nenhuma categoria principal, deverá fazê-lo agora a partir da página <a href='".e_SELF."?cat.create'>Criar Nova Categoria</a>.</i><br /><br /><b>Categoria</b><br />Seleccione a categoria a partir do menu pulldown para gerir o seu conteúdo.<br /><br />Se seleccionar uma categoria principal nesse menu, ser-lhe-ão mostrados todos os itens de conteúdo nessa categoria principal.<br />Ao seleccionar uma sub-categoria serão mostrados apenas os itens de conteúdo dessa categoria.<br /><br />Poderá aínda utilizar os menus à direita para ver os todos os conteúdos da categoria especificada.");

define("CONTENT_ADMIN_HELP_ITEM_2", "<b>Letras iniciais</b><br />Se existirem vários conteúdos começados pela mesma letra no cabeçalho do conteúdo, poderá utilizar os botões disponibilizados para seleccionar apenas os itens com essa inicial. Se clicar no botão 'todos' ser-lhe-á apresentada uma lista com todos os itens de conteúdo nessa categoria.<br /><br /><b>Lista detalhada</b><br />Poderá consultar a lista de todos os itens de conteúdo com a sua ID, ícone, autor, cabeçalho, sub-cabeçalho e opções.<br /><br /><b>Explicação dos ícones</b><br />".CONTENT_ICON_USER." : Link para o perfil do autor<br />".CONTENT_ICON_LINK." : Link para o item de conteúdo<br />".CONTENT_ICON_EDIT." : Editar o item de conteúdo<br />".CONTENT_ICON_DELETE." : Apagar o item de conteúdo<br />");

define("CONTENT_ADMIN_HELP_ITEMEDIT_1", "<b>Formulário de edição</b><br />Poderá editar toda a informação deste item de conteúdo e submeter as suas alterações.<br /><br />Se necessitar alterar a categoria deste item de conteúdo, deverá efectuá-la em primeiro lugar. Após seleccionar a categoria desejada, altere ou adicione os campos mostrados antes de submeter as alterações.");

define("CONTENT_ADMIN_HELP_ITEMCREATE_1", "<b>Cateogria</b><br />Por favor seleccione a categoria (a partir da caixa de selecção) para a qual deseja criar o item de conteúdo.<br />");

define("CONTENT_ADMIN_HELP_ITEMCREATE_2", "<b>Formulário de criação</b><br />Poderá adicionar toda a informação para este item de conteúdo e efectuar a sua submissão.<br /><br />Tenha em atenção que as diferentes categorias principais têm conjuntos diferentes de definições (poderá encontrar outros campos para preencher). Devido a este facto, é conveniente escolher sempre a categoria antes de preencher os outros campos!");

define("CONTENT_ADMIN_HELP_CAT_1", "<i>Esta página mostra-lhe todas as categorias e sub-categorias disponíveis.</i><br /><br /><b>Lista detalhada</b><br />Poderá consultar a lista de todos as sub-categorias com a sua ID, ícone, autor, cabeçalho, sub-cabeçalho e opções.<br /><br /><b>Explicação dos ícones</b><br />".CONTENT_ICON_USER." : Link para o perfil do autor<br />".CONTENT_ICON_LINK." : Link para a categoria<br />".CONTENT_ICON_EDIT." : Editar a categoria<br />".CONTENT_ICON_DELETE." : Apagar a categoria<br />");

define("CONTENT_ADMIN_HELP_CAT_2", "<i>Esta página permite-lhe criar uma nova cateogria</i><br /><br />Deverá escolher sempre a categoria principal antes de preencher os outros campos!<br /><br />Isto deve-se ao facto de algumas definições da categoria necessitarem de ser carregadas no sistema.<br /><br />Por defeito ser-lhe-á pedido para criar uma nova categoria principal."); //By default the category page is shown to create a new main category

define("CONTENT_ADMIN_HELP_CAT_3", "<i>Esta página mostra-lhe o formulário de edição de categorias.</i><br /><br /><b>Formulário de edição de categoria</b><br />Pode editar toda a informação desta (sub-)categoria e submeter as suas alterações.<br /><br />Se desejar alterar a localização principal desta categoria, deverá efectuar essa operação em primeiro lugar. Após ter efectuado a escolha correcta da categoria, edite todos os outros campos.");

define("CONTENT_ADMIN_HELP_ORDER_1", "<i>Esta página mostra todas as categorias e sub-categorias disponíveis.</i><br /><br /><b>Lista detalhada</b><br />Poderá consultar a lista de todos as categorias pelo nome/ID e dispõe aínda de um conjunto de opções diversas para ordenar as categorias.<br /><br /><b>Explicação dos ícones</b><br />".CONTENT_ICON_USER." : Link para o perfil do autor<br />".CONTENT_ICON_LINK." : Link para a categoria<br />".CONTENT_ICON_ORDERALL." : Gerir a ordem global dos itens de conteúdo, independentemente da categoria.<br />".CONTENT_ICON_ORDERCAT." : Gerir a ordem dos itens de conteúdo dentro da categoria.<br />".CONTENT_ICON_ORDER_UP." : O botão cima permite-lhe mover o conteúdo uma posição para cima na ordem.<br />".CONTENT_ICON_ORDER_DOWN." : O botão baixo permite-lhe mover o conteúdo uma posição para baixo na ordem.<br /><br /><b>Ordem</b><br />Aqui pode alterar manualmente a ordem de todas as categorias dentro das categorias principais. Altere o valor da ordem desejada nas caixas de selecção e depois clique no botão de actualização para gravar a nova ordem.<br />");

define("CONTENT_ADMIN_HELP_ORDER_2", "<i>Esta página mostra a lista total de conteúdos na categoria seleccionada.</i><br /><br /><b>Lista detalhada</b><br />Poderá consultar a lista de todos os conteúdos pelo ID, autor e cabeçalho e dispõe aínda de um conjunto de opções diversas para ordenar os itens de conteúdo.<br /><br /><b>Explicação dos ícones</b><br />".CONTENT_ICON_USER." : Link para o perfil do autor<br />".CONTENT_ICON_LINK." : Link para o item de conteúdo<br />".CONTENT_ICON_ORDER_UP." : O botão cima permite-lhe mover o conteúdo uma posição para cima na ordem.<br />".CONTENT_ICON_ORDER_DOWN." : O botão baixo permite-lhe mover o conteúdo uma posição para baixo na ordem.<br /><br /><b>Ordem</b><br />Aqui pode alterar manualmente a ordem de todas as categorias dentro desta categoria principal. Altere o valor da ordem desejada nas caixas de selecção e depois clique no botão de actualização para gravar a nova ordem.<br />");

define("CONTENT_ADMIN_HELP_ORDER_3", "<i>Esta página mostra-lhe todos os itens de conteúdo na categoria principal da sua escolha.</i><br /><br /><b>Lista detalhada</b><br />Poderá consultar a lista de todos os conteúdos pelo ID, autor e cabeçalho e dispõe aínda de um conjunto de opções diversas para ordenar os itens de conteúdo.<br /><br /><b>explanation of icons</b><br />".CONTENT_ICON_USER." : Link para o perfil do autor<br />".CONTENT_ICON_LINK." : Link para o item de conteúdo<br />".CONTENT_ICON_ORDER_UP." : O botão cima permite-lhe mover o conteúdo uma posição para cima na ordem.<br />".CONTENT_ICON_ORDER_DOWN." : O botão baixo permite-lhe mover o conteúdo uma posição para baixo na ordem.<br /><br /><b>Ordem</b><br />Aqui pode alterar manualmente a ordem de todas as categorias dentro desta categoria principal. Altere o valor da ordem desejada nas caixas de selecção e depois clique no botão de actualização para gravar a nova ordem.<br />");

define("CONTENT_ADMIN_HELP_OPTION_1", "Nesta página pode alterar a configuração das categorias principais, ou editar as definições por defeito.<br /><br /><b>Explicação dos ícones</b><br />".CONTENT_ICON_USER." : Link para o perfil do autor<br />".CONTENT_ICON_LINK." : Link para a categoria<br />".CONTENT_ICON_OPTIONS." : Editar as definições<br /><br /><br />
As definições por defeito são usadas apenas na criação de uma nova categoria principal. Quando cria uma categoria principal, essas definições são guardadas por defeito. Poderá alterar estas definições para garantir que as categorias principais criadas posteriormente já têm um deteminado número de opções definidas.
<br /><br />
Cada categoria principal tem o seu conjunto específico de definições que é único a essa secção");

//define("CONTENT_ADMIN_HELP_OPTION_2", "<i>Esta página são mostradas as opções disponiveis para esta categoria principal. Cada categoria principal tem o seu conjunto específico de definições, por isso certifique-se que estas são atribuidas de uma forma correcta.</i><br /><br />");
//<b>Valores por defeito</b><br />Por defeito, todos as definições já estão atribuidos e actualizadas nesta página,  mas podem ser ajustadas de acordo com as suas preferências.<br /><br />
define("CONTENT_ADMIN_HELP_MANAGER_1", "Nesta página será mostrada a lista completa de categorias. Poderá alterar os 'gestores pessoais de conteúdo' de cada categoria através do ícone respectivo.<br /><br /><b>Explicação dos ícones</b><br />".CONTENT_ICON_USER." : Link para o perfil do autor<br />".CONTENT_ICON_LINK." : Link para a categoria<br />".CONTENT_ICON_CONTENTMANAGER_SMALL." : Editar os gestores pessoais de conteúdo<br />");

define("CONTENT_ADMIN_HELP_MANAGER_2", "<i>Nesta página pode atribuir utilizadores às categorias desejadas</i><br /><br /><b>Gestor pessoal</b><br />Poderá atribuir utilizadores a determinadas categorias. Desta forma estes utilizadores podem gerir os seus itens pessoais de conteúdo dentro das categorias, ou externamente através da página de administração (content_manager.php).<br /><br />Escolha os utilizadores na coluna da esquerda e verá que os seus nomes são transferidos para a coluna da direita. Após ter validado a sua escolha, os nomes na coluna da direita terão sido atribuidos a esta categoria.");

define("CONTENT_ADMIN_HELP_SUBMIT_1", "<i>Nesta página pode ver a lista de conteúdos submetidos pelos utilizadores.</i><br /><br /><b>Lista detalhada</b><br />Poderá consultar a lista de todos os conteúdos com a sua ID, ícone, categoria principal, cabeçalho [sub-cabeçalho], autor e opções.<br /><br /><b>Opções</b><br />Poderá publicar ou apagar itens de conteúdo através dos botões diponibilizados.");

define("CONTENT_ADMIN_HELP_OPTION_DIV_1", "Esta página permite-lhe definir as opções para a criação de páginas de conteúdo pelos administradores.<br /><br />Pode definir quais as secções disponiveis quando um admin (ou gestor pessoal de conteúdo) criam um novo item de conteúdo.<br /><br /><b>Etiquetas de dados personalizadas</b><br />Pode disponibilizar ao admin ou gestor pessoal de conteúdo campos adicionais para o item de conteúdo, através da utilização destas etiquetas de dados personalizadas. Estes campos opcionais encontram-se vazios e aos pares (chave=>valor). Por exemplo: se desejar adicionar um campo chave para 'fotógrafo' e disponibilizar um valor 'todas as fotos são da minha autoria', ambos os campos de texto estarão vazios e disponiveis no formulário de criação.<br /><br /><b>Etiquetas de dados pré-definidas </b><br />Além das etiquetas de dados personalizadas, também poderá disponibilizar etiquetas de dados pré-definidas. A diferença nas etiquetas pré-deinidas é que o campo da 'chave' já é dado e o utilizador só necessita de preenchera o 'valor' para essa pré-definição. Tomando o exemplo anterior, o 'fotógrafo' já estará definido e o utilizador apenas necessita de preencher a informação 'todas as fotos são da minha autoria'. Poderá ainda escolher o tipo de elemento através da selecção na caixa respectiva. Na janela popup poderá aínda fornecer toda a informação necessária à pré-deinição da etiqueta de dados.<br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_2", "As opções de submissão afectam o formulário de envio de itens de conteúdo pelo utilizador.<br /><br />Poderá definir quais as secções disponibilizadas ao utilizador na submissão de itens de conteúdo.<br /><br />".CONTENT_ADMIN_OPT_LAN_11.":<br />".CONTENT_ADMIN_OPT_LAN_12."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_3", "No caminho e opções do tema, poderá definir o local de armazenamento das imagens e dos ficheiros.<br /><br />Poderá definir qual o tema utilizado na secção principal. Poderá criar temas adicionais através da cópia (e renomeação) da directoria completa 'default' na sua directoria de esquemas/templates.<br /><br />Poderá ainda definir um esquema por defeito para os novos itens de conteúdo e criar novos esquemas através da criação de um ficheiro 'content_content_template_XXX.php' na sua directoria 'templates/default'. Estes esquemas podem ser utilizados para atribuir uma visualização diferente a cada item de conteúdo nesta secção principal.<br /><br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_4", "As opções gerais são definições usadas em todas as páginas do plugin de gestão de conteúdos.");

define("CONTENT_ADMIN_HELP_OPTION_DIV_5", "Estas opções afectam a área da gestão pessoal de conteúdos (na área de administração).<br /><br />".CONTENT_ADMIN_OPT_LAN_63."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_6", "Estas opções são utilizadas no menu desta secção principal, se o respectivo menu estiver activado.<br /><br />".CONTENT_ADMIN_OPT_LAN_68."<br /><br />".CONTENT_ADMIN_OPT_LAN_118.":<br />".CONTENT_ADMIN_OPT_LAN_119."<br /><br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_7", "As opções de previsão de conteúdos afectam a previsão disponibilizada para um item de conteúdo.<br /><br />Esta previsão está disponivel em diversas páginas, tais como a página de recentes, a página de visualização de itens na categoria e a página de autores.<br /><br />".CONTENT_ADMIN_OPT_LAN_68."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_8", "A página de categoria mostra a informação das categorias de conteúdo na secção principal.<br /><br />Existem duas áreas distintas:<br /><br />Página de todas as categorias:<br />Esta página mostra todas as categorias na secção pincipal.<br /><br />Página de categoria:<br />Esta página mostra o conteúdo da categoria seleccionada, opcionalmente serão mostradas as sub-categorias e o conteúdo dessas categorias.<br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_9", "A página de conteúdo mostra os itens de conteúdo.<br /><br />Poderá escolher as secções que serão mostradas através das caixas de selecção respectivas.<br /><br />Poderá ou não mostrar o endereço de email de um autor não registado/membro.<br /><br />Poderá ajustar os ícones de email/impressão/pdf, o sistema de votação e os comentários.<br /><br />".CONTENT_ADMIN_OPT_LAN_74."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_10", "A página de autores mostra uma lista dos diferentes autores de itens de conteúdo na categoria principal.<br /><br />Poderá escolher as secções que serão mostradas através das caixas de selecção respectivas.<br /><br />Pode ainda limitar o número de itens mostrados em cada página.<br />");

define("CONTENT_ADMIN_HELP_OPTION_DIV_11", "A página de arquivo mostra todos os itens de conteúdo na categoria principal.<br /><br />Poderá escolher as secções que serão mostradas através das caixas de selecção respectivas.<br /><br />Poderá ou não mostrar o endereço de email de um autor não registado/membro.<br /><br />Pode ainda limitar o número de itens mostrados em cada página.<br /><br />".CONTENT_ADMIN_OPT_LAN_66."<br /><br />".CONTENT_ADMIN_OPT_LAN_68."");

define("CONTENT_ADMIN_HELP_OPTION_DIV_12", "A página de mais votados permite mostrar todas as páginas de conteúdo que tenham recebido votações dos utilizadores.<br /><br />Poderá escolher as secções que serão mostradas através das caixas de selecção respectivas.<br /><br />Poderá ainda definir se o endereço de email de um autor não registado/membro será ou não mostrado.");

define("CONTENT_ADMIN_HELP_OPTION_DIV_13", "A página das maiores avaliações permite-lhe visualizar todas as páginas de conteúdo que tenham recebido uma votação do autor dos conteúdos.<br /><br />Poderá escolher as secções que serão mostradas através das caixas de selecção respectivas.<br /><br />Poderá ainda definir se o endereço de email de um autor não registado/membro será ou não mostrado.");

?>