// UK lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Styles --',
theme_code_desc : 'Редакция на HTML кода',
theme_code_title : 'Редактор за HTML код',
theme_code_wordwrap : 'Пренос на думи',
theme_sub_desc : 'Subscript',
theme_sup_desc : 'Superscript',
theme_hr_desc : 'Insert horizontal ruler',
theme_removeformat_desc : 'Премахване на форматирането',
theme_custom1_desc : 'Вашето описание тук',
insert_image_border : 'Рамка',
insert_image_dimensions : 'Размери',
insert_image_vspace : 'Вертикално отстояние',
insert_image_hspace : 'Хоризонтално отстояние',
insert_image_align : 'Подравняване',
insert_image_align_default : '-- Не е избрано --',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Най-горе',
insert_image_align_middle : 'Среда',
insert_image_align_bottom : 'Най-долу',
insert_image_align_texttop : 'Най-горе текст',
insert_image_align_absmiddle : 'Абсолютна среда',
insert_image_align_absbottom : 'Абсолютно най-долу',
insert_image_align_left : 'Ляво',
insert_image_align_right : 'Дясно',
theme_font_size : '-- Шрифт размер --',
theme_fontdefault : '-- Избор шрифт --',
theme_block : '-- Форматиране --',
theme_paragraph : 'Параграф',
theme_div : 'Div',
theme_address : 'Адрес',
theme_pre : 'Преформатирано',
theme_h1 : 'Heading 1',
theme_h2 : 'Heading 2',
theme_h3 : 'Heading 3',
theme_h4 : 'Heading 4',
theme_h5 : 'Heading 5',
theme_h6 : 'Heading 6',
theme_blockquote : 'Blockquote',
theme_code : 'Код',
theme_samp : 'Примерен код',
theme_dt : 'Definition term ',
theme_dd : 'Definition description',
theme_colorpicker_title : 'Избор на цвят',
theme_colorpicker_apply : 'Приеми',
theme_forecolor_desc : 'Избор на цвят за текст',
theme_backcolor_desc : 'Избор на цвят за фон',
theme_charmap_title : 'Select custom character',
theme_charmap_desc : 'Insert custom character',
theme_visualaid_desc : 'Toggle guidelines/invisible elements',
insert_anchor_title : 'Insert/edit anchor',
insert_anchor_name : 'Anchor name',
theme_anchor_desc : 'Insert/edit anchor',
theme_insert_link_titlefield : 'Title',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
class_name : 'Class',
newdocument : 'Are you sure you want clear all contents?',
about_title : 'About TinyMCE',
about : 'About',
license : 'License',
plugins : 'Plugins',
plugin : 'Plugin',
author : 'Author',
version : 'Version',
loaded_plugins : 'Loaded plugins',
help : 'Help',
not_set : '-- Not set --',
close : 'Close',
toolbar_focus : 'Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X'
});
