// BG lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Styles --',
theme_code_desc : 'Редакция на HTML кода',
theme_code_title : 'Редактор за HTML код',
theme_code_wordwrap : 'Пренос на думи',
theme_sub_desc : 'Subscript',
theme_sup_desc : 'Superscript',
theme_hr_desc : 'Insert horizontal ruler',
theme_removeformat_desc : 'Премахване на форматирането',
theme_custom1_desc : 'Вашето описание тук',
insert_image_border : 'Рамка',
insert_image_dimensions : 'Размери',
insert_image_vspace : 'Вертикално отстояние',
insert_image_hspace : 'Хоризонтално отстояние',
insert_image_align : 'Подравняване',
insert_image_align_default : '-- Не е избрано --',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Най-горе',
insert_image_align_middle : 'Среда',
insert_image_align_bottom : 'Най-долу',
insert_image_align_texttop : 'Най-горе текст',
insert_image_align_absmiddle : 'Абсолютна среда',
insert_image_align_absbottom : 'Абсолютно най-долу',
insert_image_align_left : 'Ляво',
insert_image_align_right : 'Дясно',
theme_font_size : '-- Шрифт размер --',
theme_fontdefault : '-- Избор шрифт --',
theme_block : '-- Форматиране --',
theme_paragraph : 'Параграф',
theme_div : 'Div',
theme_address : 'Адрес',
theme_pre : 'Преформатирано',
theme_h1 : 'Heading 1',
theme_h2 : 'Heading 2',
theme_h3 : 'Heading 3',
theme_h4 : 'Heading 4',
theme_h5 : 'Heading 5',
theme_h6 : 'Heading 6',
theme_blockquote : 'Blockquote',
theme_code : 'Код',
theme_samp : 'Примерен код',
theme_dt : 'Definition term ',
theme_dd : 'Definition description',
theme_colorpicker_title : 'Избор на цвят',
theme_colorpicker_apply : 'Приеми',
theme_forecolor_desc : 'Избор на цвят за текст',
theme_backcolor_desc : 'Избор на цвят за фон',
theme_charmap_title : 'Избери символ',
theme_charmap_desc : 'Вмъкни символ',
theme_visualaid_desc : 'Скриване/показване на елементи',
insert_anchor_title : 'Вмъкване/редакция на anchor',
insert_anchor_name : 'Име на anchor',
theme_anchor_desc : 'Вмъкване/редакция на anchor',
theme_insert_link_titlefield : 'Заглавие',
theme_clipboard_msg : 'Copy/Cut/Paste е не възможно в Mozilla и Firefox.\nИскате ли повече информация по този въпрос?',
theme_path : 'Път',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Списък линкове',
image_list : 'Списък картинки',
browse : 'Разглеждане',
image_props_desc : 'Свойства на картинката',
newdocument_desc : 'Нов документ',
class_name : 'Клас',
newdocument : 'Сигурен ли сте, че искате да изтриете всичко?',
about_title : 'Относно TinyMCE',
about : 'Относно TinyMCE',
license : 'Лиценз',
plugins : 'Модули',
plugin : 'Модул',
author : 'Автор',
version : 'Версия',
loaded_plugins : 'Заредени модули',
help : 'Помощ',
not_set : '-- Не е зададено --',
close : 'Затвори',
toolbar_focus : 'Отиди на бутоните за инструменти - Alt+Q, Отиди към редактор - Alt-Z, Отиди към път на елементите - Alt-X'
});
