tinyMCE.addI18n('es.advanced',{
style_select: "Estilos",
font_size: "Tamaño",
fontdefault: "Familia de fuentes",
block: "Formato",
paragraph: "Párrafo",
div: "div",
address: "Dirección",
pre: "preformateado",
h1: "Título 1",
h2: "Título 2",
h3: "Título 3",
h4: "Título 4",
h5: "Título 5",
h6: "Título 6",
blockquote: "entrecomillado",
code: "Código",
samp: "Código Muestra",
dt: "término definido",
dd: "Definición",
bold_desc: "Negrita (Ctrl + B)",
italic_desc: "Cursiva (Ctrl + I)",
underline_desc: "Subrayado (Ctrl + U)",
striketrough_desc: "Tachado",
justifyleft_desc: "Alinear a la izquierda",
justifycenter_desc: "Alinear al centro",
justifyright_desc: "Alinear a la derecha",
justifyfull_desc: "Alinear",
bullist_desc: "Lista desordenada",
numlist_desc: "Lista ordenada",
outdent_desc: "Sangría",
indent_desc: "Sangría",
undo_desc: "Deshacer (Ctrl + Z)",
redo_desc: "Rehacer (Ctrl + Y)",
link_desc: "Insertar / Editar Vínculo",
unlink_desc: "Desvincular",
image_desc: "Insertar / editar imagen",
cleanup_desc: "Código de limpieza sucia",
code_desc: "Editar HTML",
sub_desc: "Subíndice",
sup_desc: "Superíndice",
hr_desc: "Insertar regla horizontal",
removeformat_desc: "Eliminar formato",
custom1_desc: "Su descripción personal aquí",
forecolor_desc: "Seleccione el color del texto",
backcolor_desc: "Seleccione el color de fondo",
charmap_desc: "Insertar caracteres personalizados",
visualaid_desc: "Guidelines / elementos invisibles",
anchor_desc: "Insertar / editar ancla",
cut_desc: "Cortar",
copy_desc: "Copiar",
paste_desc: "Pegar",
image_props_desc: "Características de la imagen",
newdocument_desc: "Nuevo documento",
help_desc: "Ayuda",
blockquote_desc: "entrecomillado",
clipboard_msg: "Copiar / Cortar / Pegar no se encuentra disponible en Mozilla y Firefox. \ r \ n ¿Desea obtener más información acerca de este problema?",
path: "Path",
newdocument: "¿Estás seguro de que quieres borrar todo el contenido?",
toolbar_focus: "Saltar a la barra de herramientas - Alt + Q, Saltar al editor - Alt-Z, Saltar al elemento de la ruta - Alt-X",
more_colors: "Más colores" 
});