// ES lang variables by Alvaro Velasco

tinyMCE.addToLang('',{
theme_style_select : 'Estilos',
theme_code_desc : 'Editar codigo HTML',
theme_code_title : 'Editor codigo HTML',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : 'Subindice',
theme_sup_desc : 'Superindice',
theme_hr_desc : 'Insertar un separador horizontal',
theme_removeformat_desc : 'Quitar formato',
theme_custom1_desc : 'Tu descricion',
insert_image_border : 'Borde',
insert_image_dimensions : 'Dimensiones',
insert_image_vspace : 'Espacio vertical',
insert_image_hspace : 'Espacio horizontal',
insert_image_align : 'Alineamiento',
insert_image_align_default : 'Por defecto',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Superior',
insert_image_align_middle : 'Centro',
insert_image_align_bottom : 'Inferior',
insert_image_align_texttop : 'Alinear texto arriba',
insert_image_align_absmiddle : 'Centrado horizontal',
insert_image_align_absbottom : 'Centrado abajo',
insert_image_align_left : 'Izquierda',
insert_image_align_right : 'Derecha',
insert_image_delta_height'] = 10;
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraph',
theme_div : 'Div',
theme_address : 'Address',
theme_pre : 'Preformatted',
theme_h1 : 'Heading 1',
theme_h2 : 'Heading 2',
theme_h3 : 'Heading 3',
theme_h4 : 'Heading 4',
theme_h5 : 'Heading 5',
theme_h6 : 'Heading 6',
theme_colorpicker_title : 'Select a color',
theme_colorpicker_apply : 'Apply',
theme_forecolor_desc : 'Select forecolor',
theme_backcolor_desc : 'Select background color',
theme_charmap_title : 'Select custom character',
theme_charmap_desc : 'Insert custom character',
theme_visualaid_desc : 'Toggle guidelines/invisible elements',
insert_anchor_title : 'Insert/edit anchor',
insert_anchor_name : 'Anchor name',
theme_anchor_desc : 'Insert/edit anchor',
theme_insert_link_titlefield : 'Title',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
newdocument : 'Are you sure you want clear all contents?'
});
