// FI lang variables by Urho Konttori from Absolutions

tinyMCE.addToLang('',{
theme_style_select : 'Tyylit',
theme_code_desc : 'Muokkaa HTML l‰hdekoodia',
theme_code_title : 'HTML L‰hdekoodin muokkaus',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : 'Alam‰‰re',
theme_sup_desc : 'Yl‰m‰‰re',
theme_hr_desc : 'Lis‰‰ vaakaviiva',
theme_removeformat_desc : 'Poista muotoilu',
theme_custom1_desc : 'Kirjoita oma selityksesi t‰h‰n',
insert_image_border : 'Reuna',
insert_image_dimensions : 'Mitat',
insert_image_vspace : 'Pystyv‰li',
insert_image_hspace : 'Vaakav‰li',
insert_image_align : 'Asettelu',
insert_image_align_default : 'Oletus',
insert_image_align_baseline : 'Perustasoon',
insert_image_align_top : 'Yl‰laitaan',
insert_image_align_middle : 'Keskelle',
insert_image_align_bottom : 'Alalaitaan',
insert_image_align_texttop : 'Tekstin yl‰laitaan',
insert_image_align_absmiddle : 'Absoluuttisen keskelle',
insert_image_align_absbottom : 'Absoluuttisen alas',
insert_image_align_left : 'Vasemmalle',
insert_image_align_right : 'Oikealle',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : 'Kappale',
theme_div : 'Div',
theme_address : 'Osoite',
theme_pre : 'Etuk‰teen muotoiltu',
theme_h1 : 'Otsikko 1',
theme_h2 : 'Otsikko 2',
theme_h3 : 'Otsikko 3',
theme_h4 : 'Otsikko 4',
theme_h5 : 'Otsikko 5',
theme_h6 : 'Otsikko 6',
theme_colorpicker_title : 'Valitse v‰ri',
theme_colorpicker_apply : 'Aseta v‰ri',
theme_forecolor_desc : 'Valitse etuv‰ri',
theme_backcolor_desc : 'Select background color',
theme_charmap_title : 'Select custom character',
theme_charmap_desc : 'Insert custom character',
theme_visualaid_desc : 'Toggle guidelines/invisible elements',
insert_anchor_title : 'Insert/edit anchor',
insert_anchor_name : 'Anchor name',
theme_anchor_desc : 'Insert/edit anchor',
theme_insert_link_titlefield : 'Title',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
newdocument : 'Are you sure you want clear all contents?'
});
