// Canadian French lang variables by Virtuelcom
// Modify by Laurent Dran 13-02-2006

tinyMCE.addToLang('',{
theme_style_select : 'Styles',
theme_code_desc : 'Modifier le code source HTML',
theme_code_title : '&Eacute;diteur de code source HTML',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : 'Souscrit',
theme_sup_desc : 'Indice sup&eacute;rieur',
theme_hr_desc : 'Ins&eacute;rer un s&eacute;parateur horizontal',
theme_removeformat_desc : 'Supprimer le formattage',
theme_custom1_desc : 'Votre description personnalis&eacute;e ici',
insert_image_border : 'Bordure',
insert_image_dimensions : 'Dimensions',
insert_image_vspace : 'VSpace',
insert_image_hspace : 'HSpace',
insert_image_align : 'Alignement',
insert_image_align_default : 'D&eacute;faut',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Haut',
insert_image_align_middle : 'Milieu',
insert_image_align_bottom : 'Bas',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Milieu absolu',
insert_image_align_absbottom : 'Bas absolu',
insert_image_align_left : 'Gauche',
insert_image_align_right : 'Droit',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraphe',
theme_div : 'Div',
theme_address : 'Addresse',
theme_pre : 'Pr&eacute;formatt&eacute;',
theme_h1 : 'Ent&ecirc;te 1',
theme_h2 : 'Ent&ecirc;te 2',
theme_h3 : 'Ent&ecirc;te 3',
theme_h4 : 'Ent&ecirc;te 4',
theme_h5 : 'Ent&ecirc;te 5',
theme_h6 : 'Ent&ecirc;te 6',
theme_colorpicker_title : 'Choisir une couleur',
theme_colorpicker_apply : 'Appliquer',
theme_forecolor_desc : 'Choisir la couleur d\'avant plan',
theme_backcolor_desc : 'Choisir la couleur de fond',
theme_charmap_title : 'S&eacute;lectionner un charact&egrave;re sp&eacute;cial',
theme_charmap_desc : 'Ins&eacute;rer un charact&egrave;re sp&eacute;cial',
theme_visualaid_desc : 'Active/D&eacute;sactive les lignes guides et les &eacute;l&eacute;ments invisibles',
insert_anchor_title : 'Ins&eacute;rer/Modifier une ancre',
insert_anchor_name : 'Nom de l\'ancre',
theme_anchor_desc : 'Ins&eacute;rer/Modifier une ancre',
theme_insert_link_titlefield : 'Titre',
theme_clipboard_msg : 'Copier/Couper/Coller ne sont pas disponibles pour Mozilla et Firefox.\nVoulez vous plus d\'informations à ce sujet?',
theme_path : 'Chemin',
cut_desc : 'Couper',
copy_desc : 'Copier',
paste_desc : 'Coller',
link_list : 'Lien de la liste',
image_list : 'Image de la liste',
browse : 'Naviguer',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
class_name : 'Classe CSS',
newdocument : 'Are you sure you want clear all contents?'
});
