// HU lang variables
// Edited by 2XP (2xp@dino.hu)

tinyMCE.addToLang('',{
theme_style_select : 'St&#237;lusok',
theme_code_desc : 'HTML k&#243;d szerkeszt&#233;se',
theme_code_title : 'HTML k&#243;dszerkezt&#245;',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : 'Als&#243; index',
theme_sup_desc : 'Fels&#245; index',
theme_hr_desc : 'V&#237;zszintes vonal beilleszt&#233;se',
theme_removeformat_desc : 'Form&#225;z&#225;s elt&#225;vol&#237;t&#225;sa',
theme_custom1_desc : 'Az &#214;n &#225;ltal kiv&#225;lasztott le&#237;r&#225;s',
insert_image_border : 'Keret',
insert_image_dimensions : 'M&#233;retek',
insert_image_vspace : 'F&#252;gg&#245;leges t&#233;rk&#246;z',
insert_image_hspace : 'V&#237;zszintes t&#233;rk&#246;z',
insert_image_align : 'Igaz&#237;t&#233;s',
insert_image_align_default : 'Alap&#233;rtelmezett',
insert_image_align_baseline : 'Alapvonalra',
insert_image_align_top : 'Fel&#252;lre',
insert_image_align_middle : 'K&#246;z&#233;pre',
insert_image_align_bottom : 'Alulra',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Abszol&#250;t k&#246;z&#233;pre',
insert_image_align_absbottom : 'Abszol&#250;t alulra',
insert_image_align_left : 'Balra',
insert_image_align_right : 'Jobbra',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraph',
theme_div : 'Div',
theme_address : 'Address',
theme_pre : 'Preformatted',
theme_h1 : 'Heading 1',
theme_h2 : 'Heading 2',
theme_h3 : 'Heading 3',
theme_h4 : 'Heading 4',
theme_h5 : 'Heading 5',
theme_h6 : 'Heading 6',
theme_colorpicker_title : 'Select a color',
theme_colorpicker_apply : 'Apply',
theme_forecolor_desc : 'Select forecolor',
theme_backcolor_desc : 'Select background color',
theme_charmap_title : 'Select custom character',
theme_charmap_desc : 'Insert custom character',
theme_visualaid_desc : 'Toggle guidelines/invisible elements',
insert_anchor_title : 'Insert/edit anchor',
insert_anchor_name : 'Anchor name',
theme_anchor_desc : 'Insert/edit anchor',
theme_insert_link_titlefield : 'Title',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
newdocument : 'Are you sure you want clear all contents?'
});
