// Variabili di lingua IT - fabrix.xm@lombardiacom.it

tinyMCE.addToLang('',{
theme_style_select : 'Stili',
theme_code_desc : 'Edita il sorgente HTML',
theme_code_title : 'Editor Sorgente HTML',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : 'Pedice',
theme_sup_desc : 'Apice',
theme_hr_desc : 'Inserisce linea orizzontale',
theme_removeformat_desc : 'Rimuovi formattazione',
theme_custom1_desc : 'Scrivi qui la tua descrizione personalizzata',
insert_image_border : 'Bordo',
insert_image_dimensions : 'Dimensioni',
insert_image_vspace : 'Spazio verticale',
insert_image_hspace : 'Spazio orizzontale',
insert_image_align : 'Allineamento',
insert_image_align_default : 'Default',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Superiore',
insert_image_align_middle : 'Centrale',
insert_image_align_bottom : 'Inferiore',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Centro assoluto',
insert_image_align_absbottom : 'Inferiore assoluto',
insert_image_align_left : 'Sinistra',
insert_image_align_right : 'Destra',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : 'Paragrafo',
theme_div : 'Div',
theme_address : 'Indirizzo',
theme_pre : 'Preformattato',
theme_h1 : 'Intestazione 1',
theme_h2 : 'Intestazione 2',
theme_h3 : 'Intestazione 3',
theme_h4 : 'Intestazione 4',
theme_h5 : 'Intestazione 5',
theme_h6 : 'Intestazione 6',
theme_colorpicker_title : 'Seleziona un colore',
theme_colorpicker_apply : 'Appplica',
theme_forecolor_desc : 'Seleziona il colore',
theme_backcolor_desc : 'Select background color',
theme_charmap_title : 'Seleziona un carattere custom',
theme_charmap_desc : 'Inserisci un carattere custom',
theme_visualaid_desc : 'Mostra/nascondi linee guida e elementi invisibili',
insert_anchor_title : 'Inserisci/modifica &agrave;ncora',
insert_anchor_name : 'Nome &agrave;ncora',
theme_anchor_desc : 'Inserisci/modifica &agrave;ncora',
theme_insert_link_titlefield : 'Titolo',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
class_name : 'Classe', 
newdocument : 'Are you sure you want clear all contents?'
});
