// KO lang variables

tinyMCE.addToLang('',{
theme_style_select : '스타일',
theme_code_desc : 'HTML 소스 고치기',
theme_code_title : 'HTML 소스 편집기',
theme_code_wordwrap : 'Word wrap',
theme_code_save : '저장',
theme_sub_desc : '아래첨자',
theme_sup_desc : '위첨자',
theme_hr_desc : '가로줄 넣기',
theme_removeformat_desc : '속성 지우기',
theme_custom1_desc : 'Your custom description here',
insert_image_border : '테두리',
insert_image_dimensions : '크기',
insert_image_vspace : '세로 여백',
insert_image_hspace : '가로 여백',
insert_image_align : '정렬',
insert_image_align_default : '기본값',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Top',
insert_image_align_middle : 'Middle',
insert_image_align_bottom : 'Bottom',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Absolute Middle',
insert_image_align_absbottom : 'Absolute Bottom',
insert_image_align_left : 'Left',
insert_image_align_right : 'Right',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : '단락',
theme_div : 'Div',
theme_address : '주소',
theme_pre : '서식 있음',
theme_h1 : '제목 1',
theme_h2 : '제목 2',
theme_h3 : '제목 3',
theme_h4 : '제목 4',
theme_h5 : '제목 5',
theme_h6 : '제목 6',
theme_colorpicker_title : '색상 선택',
theme_colorpicker_apply : '적용',
theme_forecolor_desc : '글자 색상',
theme_backcolor_desc : 'Select background color',
theme_charmap_title : 'Select custom character',
theme_charmap_desc : 'Insert custom character',
theme_visualaid_desc : 'Toggle guidelines/invisible elements',
insert_anchor_title : '앵커 넣기/고치기',
insert_anchor_name : '앵커 이름',
theme_anchor_desc : '앵커 넣기/고치기',
theme_insert_link_titlefield : '제목',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
class_name : '클래스',
newdocument : 'Are you sure you want clear all contents?'
});
