// NL lang variables

tinyMCE.addToLang('',{
theme_style_select : 'Stijlen',
theme_code_desc : 'Toon/bewerk HTML broncode',
theme_code_title : 'HTML broncode editor',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : 'Subscript',
theme_sup_desc : 'Superscript',
theme_hr_desc : 'Invoegen horizontale lijn',
theme_removeformat_desc : 'Verwijder opmaak',
theme_custom1_desc : 'Uw eigen omschrijving hier',
insert_image_border : 'Omranding (pixels)',
insert_image_dimensions : 'Afmetingen (Leeg: Originele afm.)',
insert_image_vspace : 'Verticale marge (pixels)',
insert_image_hspace : 'Horizontale marge (pixels)',
insert_image_align : 'Uitlijning',
insert_image_align_default : 'Standaard',
insert_image_align_baseline : 'Basislijn',
insert_image_align_top : 'Boven',
insert_image_align_middle : 'Midden',
insert_image_align_bottom : 'Onder',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Absoluut Midden',
insert_image_align_absbottom : 'Absoluut Onder',
insert_image_align_left : 'Links',
insert_image_align_right : 'Rechts',
insert_image_delta_height'] = 0;
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraaf',
theme_div : 'Div',
theme_address : 'Adres',
theme_pre : 'voorgeformatteerd',
theme_h1 : 'Titel 1',
theme_h2 : 'Titel 2',
theme_h3 : 'Titel 3',
theme_h4 : 'Titel 4',
theme_h5 : 'Titel 5',
theme_h6 : 'Titel 6',
theme_colorpicker_title : 'Kies een kleur',
theme_colorpicker_apply : 'Toepassen',
theme_forecolor_desc : 'Selecteer voorgrondkleur',
theme_backcolor_desc : 'Select background color',
theme_charmap_title : 'Kies een bijzonder karakter',
theme_charmap_desc : 'Voeg een bijzonder karakter in',
theme_preview_desc : 'Toon de pagina in een nieuw venster',
theme_visualaid_desc : 'Toon/verberg hulplijnen',
insert_anchor_title : 'Anker toevoegen/wijzigen',
insert_anchor_name : 'Anker naam',
theme_anchor_desc : 'Anker toevoegen/wijzigen',
theme_insert_link_titlefield : 'Titel',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
class_name : 'CSS-Stijl',
newdocument : 'Are you sure you want clear all contents?'
});
