// NO lang variables

tinyMCE.addToLang('',{
theme_style_select : 'Stiler',
theme_code_desc : 'Redigere HTML Koden',
theme_code_title : 'HTML Kildekode Redigering',
theme_code_wordwrap : 'Word wrap',
theme_code_save : 'Lagre',
theme_sub_desc : 'Subscript',
theme_sup_desc : 'Superscript',
theme_hr_desc : 'Sett in horisontal linie',
theme_removeformat_desc : 'Fjern formatering',
theme_custom1_desc : 'Din spesialfunksjons beskriving her',
insert_image_border : 'Ramme',
insert_image_dimensions : 'Dimensjoner',
insert_image_vspace : 'Vertikalt tomrom',
insert_image_hspace : 'Horizontellt tomrom',
insert_image_align : 'Justering',
insert_image_align_default : 'Intet',
insert_image_align_baseline : 'Buttenlinjen',
insert_image_align_top : 'Lengst opp',
insert_image_align_middle : 'Midten',
insert_image_align_bottom : 'Lengst ned',
insert_image_align_texttop : 'Tekstens top',
insert_image_align_absmiddle : 'Absolutt midten',
insert_image_align_absbottom : 'Absolutt lengst ned',
insert_image_align_left : 'Venstre',
insert_image_align_right : 'Høyre',
insert_image_delta_width : '',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraf',
theme_div : 'Div',
theme_address : 'Addresse',
theme_pre : 'Pre-formattert',
theme_h1 : 'Overskrift 1',
theme_h2 : 'Overskrift 2',
theme_h3 : 'Overskrift 3',
theme_h4 : 'Overskrift 4',
theme_h5 : 'Overskrift 5',
theme_h6 : 'Overskrift 6',
theme_colorpicker_title : 'Velg en farge',
theme_colorpicker_apply : 'Bruk',
theme_forecolor_desc : 'Velg forgrunnsfarge',
theme_backcolor_desc : 'Select background color',
theme_charmap_title : 'Velg spesialtegn',
theme_charmap_desc : 'Sett inn spesialtegn',
theme_visualaid_desc : 'Slå av/på usynlige elementer',
insert_anchor_title : 'Opprette/endre anker',
insert_anchor_name : 'Ankernavn',
theme_anchor_desc : 'Opprett/endre anker',
theme_insert_link_titlefield : 'Tittel',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
class_name : 'Stil',
newdocument : 'Are you sure you want clear all contents?'
});
