// UK lang variables

tinyMCE.addToLang('',{
theme_style_select : 'Styl',
theme_code_desc : 'Edytuj zródlo html',
theme_code_title : 'Edytor zródla html',
theme_code_wordwrap : 'Zwijanie wierszy',
theme_sub_desc : 'Nadpisywanie',
theme_sup_desc : 'Podpisywanie',
theme_hr_desc : 'Wstaw pozioma linie',
theme_removeformat_desc : 'Usun formatowanie',
theme_custom1_desc : 'Wstaw wlasny opis',
insert_image_border : 'Ramka',
insert_image_dimensions : 'Wymiary',
insert_image_vspace : 'VSpace',
insert_image_hspace : 'HSpace',
insert_image_align : 'Otaczanie',
insert_image_align_default : 'Domyslne',
insert_image_align_baseline : 'Glówne',
insert_image_align_top : 'Górne',
insert_image_align_middle : 'Srodkowe',
insert_image_align_bottom : 'Dolne',
insert_image_align_texttop : 'Tekst powyzej',
insert_image_align_absmiddle : 'Absolutny srodek',
insert_image_align_absbottom : 'Absolutny dól',
insert_image_align_left : 'Lewe',
insert_image_align_right : 'Prawe',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : '-- Paragraf --',
theme_div : 'Div',
theme_address : 'Adres',
theme_pre : 'Preformatowanie',
theme_h1 : 'Naglówek 1',
theme_h2 : 'Naglówek 2',
theme_h3 : 'Naglówek 3',
theme_h4 : 'Naglówek 4',
theme_h5 : 'Naglówek 5',
theme_h6 : 'Naglówek 6',
theme_colorpicker_title : 'Wybierz kolor',
theme_colorpicker_apply : 'Wybierz',
theme_forecolor_desc : 'Wybierz kolor tekstu',
theme_backcolor_desc : 'Wybierz kolor tla',
theme_charmap_title : 'Wybierz znak',
theme_charmap_desc : 'Wstaw znak',
theme_visualaid_desc : 'Toggle guidelines/invisible elements',
insert_anchor_title : 'Kotwica',
insert_anchor_name : 'Nazwa kotwicy',
theme_anchor_desc : 'Wstaw/Edytuj kotwice',
theme_insert_link_titlefield : 'Tytul',
theme_clipboard_msg : 'Kopiuj/Edytuj/Wklej nie jest dostepne w przegladarkach Mozilla and Firefox.\nPotrzebujesz wiecej informacji na ten temat?',
theme_path : 'Sciezka',
cut_desc : 'Wytnij',
copy_desc : 'Kopiuj',
paste_desc : 'Wklej',
link_list : 'Lista linków',
image_list : 'Lista obrazków',
browse : 'Przegladaj',
image_props_desc : 'Wlasciwosci obrazka',
newdocument_desc : 'New document',
class_name : 'Klasa',
newdocument : 'Are you sure you want clear all contents?'
});
