// PT lang variables by X-fact0r (2006/01/27)

tinyMCE.addToLang('',{
theme_style_select : '-- Estilos --',
theme_code_desc : 'Editar Código HTML',
theme_code_title : 'Editor de Código HTML',
theme_code_wordwrap : 'Quebrar Linhas',
theme_sub_desc : 'Subscrito',
theme_sup_desc : 'Superescrito',
theme_hr_desc : 'Inserir linha horizontal',
theme_removeformat_desc : 'Remover formatação',
theme_custom1_desc : 'Insira aqui a sua descrição personalizada',
insert_image_border : 'Contorno',
insert_image_dimensions : 'Dimensões',
insert_image_vspace : 'Espaçamento Vertical',
insert_image_hspace : 'Espaçamento Horizontal',
insert_image_align : 'Alinhamento',
insert_image_align_default : 'Por defeito',
insert_image_align_baseline : 'Linha base',
insert_image_align_top : 'Cima',
insert_image_align_middle : 'Centro',
insert_image_align_bottom : 'Baixo',
insert_image_align_texttop : 'Texto ao Topo',
insert_image_align_absmiddle : 'Centro absoluto',
insert_image_align_absbottom : 'Fundo absoluto',
insert_image_align_left : 'Esquerda',
insert_image_align_right : 'Direita',
theme_font_size : '-- Tamanho de Letra --',
theme_fontdefault : '-- Tipo de Fonte --',
theme_block : '-- Formato --',
theme_paragraph : 'Parágrafo',
theme_div : 'Div',
theme_address : 'Endereço',
theme_pre : 'Pré-formatado',
theme_h1 : 'Cabeçalho 1',
theme_h2 : 'Cabeçalho 2',
theme_h3 : 'Cabeçalho 3',
theme_h4 : 'Cabeçalho 4',
theme_h5 : 'Cabeçalho 5',
theme_h6 : 'Cabeçalho 6',
theme_colorpicker_title : 'Seleccionar cor',
theme_colorpicker_apply : 'Aplicar',
theme_forecolor_desc : 'Seleccionar cor do texto',
theme_backcolor_desc : 'Seleccionar cor de fundo',
theme_charmap_title : 'Seleccionar caracter especial',
theme_charmap_desc : 'Inserir caracter especial',
theme_charmap_all_title : 'Todos',
theme_charmap_all_desc : 'Todos os caracteres',
theme_charmap_alpha_title : 'Alfabéticos',
theme_charmap_alpha_desc : 'Caracteres alfabéticos',
theme_charmap_arrows_title : 'Setas',
theme_charmap_arrows_desc : 'Caracteres de setas',
theme_charmap_greek_title : 'Gregos',
theme_charmap_greek_desc : 'Caracteres Gregos',
theme_charmap_math_title : 'Matemáticos',
theme_charmap_math_desc : 'Caracteres matemáticos',
theme_charmap_misc_title : 'Diversos',
theme_charmap_misc_desc : 'Caracteres diversos',
theme_charmap_money_title : 'Moedas',
theme_charmap_money_desc : 'Caracteres de moedas',
theme_charmap_quotaion_title : 'Apóstrofos',
theme_charmap_quotaion_desc : 'Caracteres de Apóstrofos',
theme_visualaid_desc : 'Trocar as linhas de ajuda por elementos invisíveis',
insert_anchor_title : 'Inserir/editar âncora',
insert_anchor_name : 'Nome da âncora',
theme_anchor_desc : 'Inserir/editar âncora',
theme_insert_link_titlefield : 'Título',
theme_clipboard_msg : 'Não é possivel utilizar os comandos Copiar/Cortar/Colar no Mozilla e Firefox.\r\nPor favor utilize o teclado para Copiar (Ctrl+C) / Cortar (Ctrl+X) / Colar (Ctrl+V)\r\nDeseja obter mais informações?',
theme_path : 'Caminho',
cut_desc : 'Cortar (Ctrl+X)',
copy_desc : 'Copiar (Ctrl+C)',
paste_desc : 'Colar (Ctrl+V)',
link_list : 'Lista de Links',
image_list : 'Lista de Imagens',
browse : 'Navegar',
image_props_desc : 'Propriedades da imagem',
newdocument_desc : 'Novo documento',
class_name : 'Classe',
newdocument : 'Tem a certeza que deseja apagar todo o conteúdo?',
about_title : 'Sobre o TinyMCE',
about : 'Sobre',
license : 'Licença',
plugins : 'Plugins',
plugin : 'Plugin',
author : 'Autor',
version : 'Versão',
loaded_plugins : 'Plugins carregados',
help : 'Ajuda',
not_set : '-- Por defeito --',
close : 'Fechar',
toolbar_focus : 'Ir para a barra de ferramentas - Alt+Q, Ir para o editor - Alt+Z, Ir para o elemento de destino - Alt+X',
theme_advanced_anchor_delta_width : 20
});
