// Russian lang variables UTF-8

tinyMCE.addI18n('ru.advanced',{
style_select:"Стили",
font_size:"Размер",
fontdefault:"Шрифт",
block:"Формат",
paragraph:"Абзац",
div:"Раздел",
address:"Адрес",
pre:"Форматированный",
h1:"Заголовок 1",
h2:"Заголовок 2",
h3:"Заголовок 3",
h4:"Заголовок 4",
h5:"Заголовок 5",
h6:"Заголовок 6",
blockquote:"Цитата",
code:"Код",
samp:"Пример кода",
dt:"Термин ",
dd:"Определение",
bold_desc:"Полужирный (Ctrl+B)",
italic_desc:"Курсив (Ctrl+I)",
underline_desc:"Подчёркнутый (Ctrl+U)",
striketrough_desc:"Зачёркнутый",
justifyleft_desc:"По левому краю",
justifycenter_desc:"По центру",
justifyright_desc:"По правому краю",
justifyfull_desc:"По ширине",
bullist_desc:"Маркированный список",
numlist_desc:"Нумерованный список",
outdent_desc:"Уменьшить отступ",
indent_desc:"Увеличить отступ",
undo_desc:"Отменить (Ctrl+Z)",
redo_desc:"Повторить (Ctrl+Y)",
link_desc:"Вставить/редактировать ссылку",
unlink_desc:"Удалить ссылку",
image_desc:"Вставить/редактировать изображение",
cleanup_desc:"Очистить",
code_desc:"Редактировать HTML-код",
sub_desc:"Нижний индекс",
sup_desc:"Верхний индекс",
hr_desc:"Вставить горизонтальную линию",
removeformat_desc:"Убрать форматирование",
custom1_desc:"Введите описание",
forecolor_desc:"Выбрать цвет текста",
backcolor_desc:"Выбрать цвет фона",
charmap_desc:"Вставить специальный символ",
visualaid_desc:"Вкл/выкл направляющие и невидимые элементы",
anchor_desc:"Вставить/редактировать якорь",
cut_desc:"Вырезать",
copy_desc:"Копировать",
paste_desc:"Вставить",
image_props_desc:"Свойства изображения",
newdocument_desc:"Новый документ",
help_desc:"Помощь",
blockquote_desc:"Цитата",
clipboard_msg:"Команды Копировать/Вырезать/Вставить не работают в Firefox. Хотите узнать об этом подробнее?",
path:"Путь",
newdocument:"Вы уверены, что хотите очистить содержимое?",
toolbar_focus:"Перейти к кнопкам инструментов - Alt+Q, перейти к редактору - Alt+Z, перейти к пути элемента - Alt+X",
more_colors:"Выбрать цвет"
});