// Russian lang variables UTF-8

tinyMCE.addI18n('ru.advanced_dlg',{
about_title:"О TinyMCE",
about_general:"О программе",
about_help:"Помощь",
about_license:"Лицензия",
about_plugins:"Дополнения",
about_plugin:"Дополнение",
about_author:"Автор",
about_version:"Версия",
about_loaded:"Загруженные дополнения",
anchor_title:"Вставить/редактировать якорь",
anchor_name:"Имя якоря",
code_title:"Редактор HTML-кода",
code_wordwrap:"Переносить по словам",
colorpicker_title:"Выберите цвет",
colorpicker_picker_tab:"Выбор",
colorpicker_picker_title:"Выбор цвета",
colorpicker_palette_tab:"Палитра",
colorpicker_palette_title:"Цвета палитры",
colorpicker_named_tab:"Стандартные",
colorpicker_named_title:"Стандартные цвета",
colorpicker_color:"Цвет:",
colorpicker_name:"Название:",
charmap_title:"Выберите специальный символ",
image_title:"Вставить/редактировать изображение",
image_src:"Адрес изображения",
image_alt:"Описание изображения",
image_list:"Список изображений",
image_border:"Граница",
image_dimensions:"Размеры",
image_vspace:"Отступ по вертикали",
image_hspace:"Отступ по горизонтали",
image_align:"Выравнивание",
image_align_baseline:"По базовой линии",
image_align_top:"По верху",
image_align_middle:"По центру",
image_align_bottom:"По низу",
image_align_texttop:"По верху текста",
image_align_textbottom:"По низу текста",
image_align_left:"Влево",
image_align_right:"Вправо",
link_title:"Вставить/редактировать ссылку",
link_url:"Адрес ссылки",
link_target:"Цель",
link_target_same:"Открыть ссылку в том же окне",
link_target_blank:"Открыть ссылку в новом окне",
link_titlefield:"Название",
link_is_email:"Введённый адрес похож на адрес электронной почты, хотите добавить префикс mailto:?",
link_is_external:"Введённый адрес похож на внешнюю ссылку, хотите добавить префикс http://?",
link_list:"Список ссылок"
});