/*
+ ----------------------------------------------------------------------------+
|     Swedish (SE) language variables
|
|     $Source: /cvs_backup/e107_langpacks/e107_handlers/tiny_mce/themes/advanced/langs/sv.js,v $
|     $Revision: 1.2 $
|     $Date: 2005-09-17 11:39:40 $
|     $Author: mrpiercer $
+----------------------------------------------------------------------------+
*/

tinyMCE.addToLang('',{
theme_style_select : '-- Stilar --',
theme_code_desc : 'Redigera HTML källa',
theme_code_title : 'HTML källkodsredigerare',
theme_code_wordwrap : 'Radbrytning',
theme_sub_desc : 'Nedsänkt',
theme_sup_desc : 'Upphöjt',
theme_hr_desc : 'Infoga horisontell linjal',
theme_removeformat_desc : 'Radera formatering',
theme_custom1_desc : 'Din egen beskrivning här',
insert_image_border : 'Ram',
insert_image_dimensions : 'Dimensioner',
insert_image_vspace : 'Vertikalt utrymme',
insert_image_hspace : 'Horisontellt utrymme',
insert_image_align : 'Justering',
insert_image_align_default : '-- Inte aatt --',
insert_image_align_baseline : 'Baslinje',
insert_image_align_top : 'Topp',
insert_image_align_middle : 'Mitt',
insert_image_align_bottom : 'Botten',
insert_image_align_texttop : 'TextTopp',
insert_image_align_absmiddle : 'Absolut Mitt',
insert_image_align_absbottom : 'Absolut Botten',
insert_image_align_left : 'Vänster',
insert_image_align_right : 'Höger',
theme_font_size : 'Fontstorlek',
theme_fontdefault : '-- Fontfamilj --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraf',
theme_div : 'Div',
theme_address : 'Adress',
theme_pre : 'Förformaterad',
theme_h1 : 'Rubrik 1',
theme_h2 : 'Rubrik 2',
theme_h3 : 'Rubrik 3',
theme_h4 : 'Rubrik 4',
theme_h5 : 'Rubrik 5',
theme_h6 : 'Rubrik 6',
theme_colorpicker_title : 'Välj en färg',
theme_colorpicker_apply : 'Verkställ',
theme_forecolor_desc : 'Välj textfärg',
theme_backcolor_desc : 'Välj bakgrundsfärg',
theme_charmap_title : 'Välj specialtecken',
theme_charmap_desc : 'Infoga specialtecken',
theme_visualaid_desc : 'Växla guider/osynliga element',
insert_anchor_title : 'Infoga/redigera ankare',
insert_anchor_name : 'Ankarets namn',
theme_anchor_desc : 'Infoga/redigera ankare',
theme_insert_link_titlefield : 'Titel',
theme_clipboard_msg : 'Kopiera/Klipp ut/Klistra in är inte tillgängligt i Mozilla och Firefox.\nVill du ha mer information om detta?',
theme_path : 'Sökväg',
cut_desc : 'Klipp ut',
copy_desc : 'Kopiera',
paste_desc : 'Klistra in',
link_list : 'Länklista',
image_list : 'Bildlista',
browse : 'Bläddra',
image_props_desc : 'Bildattribut',
newdocument_desc : 'Nytt dokument',
class_name : 'Klass',
newdocument : 'Är du säker på att du vill rensa allt innehåll?',
about_title : 'Om TinyMCE',
about : 'Om',
license : 'Licens',
plugins : 'Plugins',
plugin : 'Plugin',
author : 'Författare',
version : 'Version',
loaded_plugins : 'Laddade plugins',
help : 'Hjälp',
not_set : '-- Inte satt --',
close : 'Stäng'
});
