// SE lang variables

tinyMCE.addToLang('',{
theme_style_select : 'Stilar',
theme_code_desc : 'Editera HTML-koden',
theme_code_title : 'HTML-k&auml;llkodseditor',
theme_code_wordwrap : 'Automatiskt radbyte',
theme_sub_desc : 'Neds&auml;nkt text',
theme_sup_desc : 'Upph&ouml;jd text',
theme_hr_desc : 'S&auml;tt in horisontell linje',
theme_removeformat_desc : 'Ta bort formatering',
theme_custom1_desc : 'Din specialbeskriving h&auml;r',
insert_image_border : 'Ram',
insert_image_dimensions : 'Dimensioner',
insert_image_vspace : 'Vertikalt tomrum',
insert_image_hspace : 'Horisontellt tomrum',
insert_image_align : 'Justering',
insert_image_align_default : 'Ingen',
insert_image_align_baseline : 'Bottenlinjen',
insert_image_align_top : 'L&auml;ngst upp',
insert_image_align_middle : 'Mitten',
insert_image_align_bottom : 'L&auml;ngst ner',
insert_image_align_texttop : 'Textens top',
insert_image_align_absmiddle : 'Absoluta mitten',
insert_image_align_absbottom : 'Absolut l&auml;ngst ner',
insert_image_align_left : 'V&auml;nster',
insert_image_align_right : 'H&ouml;ger',
insert_image_delta_width : 30,
insert_image_delta_height : 10,
theme_font_size : '-- Fontstorlek --',
theme_fontdefault : '-- Font familj --',
theme_block : '-- Stycke --',
theme_paragraph : 'Paragraf',
theme_div : 'Div',
theme_address : 'Adress',
theme_pre : 'F&ouml;rformatterad',
theme_h1 : 'Rubrik 1',
theme_h2 : 'Rubrik 2',
theme_h3 : 'Rubrik 3',
theme_h4 : 'Rubrik 4',
theme_h5 : 'Rubrik 5',
theme_h6 : 'Rubrik 6',
theme_colorpicker_title : 'Välj en färg',
theme_colorpicker_apply : 'Verkställ',
theme_forecolor_desc : 'Välj förgrundsfärg',
theme_backcolor_desc : 'Välj bakgrundsfärg',
theme_charmap_title : 'Välj specialtecken',
theme_charmap_desc : 'Sätt in specialtecken',
theme_visualaid_desc : 'Slå av/på osynliga element',
insert_anchor_title : 'Skapa/redigera ankare',
insert_anchor_name : 'Ankarnamn',
theme_anchor_desc : 'Skapa/redigera ankare',
theme_insert_link_titlefield : 'Titel',
theme_clipboard_msg : 'Klipput/Kopiera/Klistra fungerar inte Mozilla och Firefox. Vill du veta mer om detta?',
theme_path : 'S&ouml;kv&auml;g',
cut_desc : 'Klipp ut',
copy_desc : 'Kopiera',
paste_desc : 'Klistra in',
link_list : 'L&auml;nkar',
image_list : 'Bilder',
browse : 'Bl&auml;ddra',
image_props_desc : 'Bild egenskaper',
newdocument_desc : 'Nytt dokument',
class_name : 'Stil',
newdocument : 'Är du säker på att du vill tömma hela redigerings ytan?'
});
