// TW lang variables contributed by Jim Kou

tinyMCE.addToLang('',{
bold_desc : '粗體',
bold_img : "bold.gif",
bullist_desc : '符號項目',
cancel : '取消',
cleanup_desc : '清除',
help_desc : '輔助說明',
image_desc : '圖片',
indent_desc : '縮排',
insert : '新增',
insert_anchor_name : '標註名稱',
insert_anchor_title : '新增標註',
insert_image_align : '對齊',
insert_image_align_absbottom : '強制齊下',
insert_image_align_absmiddle : '強制置中',
insert_image_align_baseline : '基準線',
insert_image_align_bottom : '齊下',
insert_image_align_default : '標準',
insert_image_align_left : '齊左',
insert_image_align_middle : '置中',
insert_image_align_right : '齊右',
insert_image_align_texttop : '文字上方',
insert_image_align_top : '齊上',
insert_image_alt : '圖片說明',
insert_image_border : '外框',
insert_image_dimensions : '尺寸',
insert_image_hspace : '水平間隙',
insert_image_src : '圖片來源',
insert_image_title : '新增圖片',
insert_image_vspace : '垂直間隙',
insert_link_target : '目標',
insert_link_target_blank : '顯示於新視窗中',
insert_link_target_same : '顯示於同一視窗中',
insert_link_title : '新增超連結',
insert_link_url : '超連結',
italic_desc : '斜體',
italic_img : "italic.gif",
justifycenter_desc : '齊中',
justifyfull_desc : '填滿',
justifyleft_desc : '齊左',
justifyright_desc : '齊右',
link_desc : '建立連結',
numlist_desc : '數字項目',
outdent_desc : '凸排',
redo_desc : '重做',
striketrough_desc : '刪除線',
theme_address : '地址',
theme_anchor_desc : '標註',
theme_charmap_desc : '特殊字元',
theme_charmap_title : '特殊字元清單',
theme_code_desc : '顯示 HTML 原始碼',
theme_code_wordwrap : 'Word wrap',
theme_code_title : 'HTML 原始碼',
theme_colorpicker_apply : '變更',
theme_colorpicker_title : '顏色',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_forecolor_desc : '字型顏色',
theme_backcolor_desc : 'Select background color',
theme_h1 : '標題1',
theme_h2 : '標題2',
theme_h3 : '標題3',
theme_h4 : '標題4',
theme_h5 : '標題5',
theme_h6 : '標題6',
theme_hr_desc : '新增橫線',
theme_paragraph : '段落',
theme_pre : '內定格式',
theme_removeformat_desc : '清除格式設定',
theme_style_select : '樣式',
theme_sub_desc : '下標',
theme_sup_desc : '上標',
theme_visualaid_desc : '顯示/隱藏非可見的元素',
underline_desc : '底線',
undo_desc : '復原',
unlink_desc : '取消連結',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
newdocument : 'Are you sure you want clear all contents?'
});
