// Simplified Chinese lang variables contributed by cube316 (cube316@gmail.com)
//请访问 http://www.cube316.net/ 以获取TinyMCE的中文支持

tinyMCE.addToLang('',{
theme_style_select : '格式',
theme_code_desc : '编辑HTML源代码',
theme_code_title : 'HTML源代码编辑器',
theme_code_wordwrap : '自动换行',
theme_sub_desc : '下标',
theme_sup_desc : '上标',
theme_hr_desc : '插入水平线',
theme_removeformat_desc : '移除格式',
theme_custom1_desc : '这里填写用户自定义的描述',
insert_image_border : '边框',
insert_image_dimensions : '维数',
insert_image_vspace : '水平间距',
insert_image_hspace : '垂直间距',
insert_image_align : '对齐方式',
insert_image_align_default : '默认',
insert_image_align_baseline : '基线',
insert_image_align_top : '顶端',
insert_image_align_middle : '居中对齐',
insert_image_align_bottom : '底部',
insert_image_align_texttop : '文字上方',
insert_image_align_absmiddle : '绝对居中',
insert_image_align_absbottom : '绝对底部',
insert_image_align_left : '左对齐',
insert_image_align_right : '右对齐',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : '段落',
theme_div : '层',
theme_address : '地址',
theme_pre : '预格式化的',
theme_h1 : '标题 1',
theme_h2 : '标题 2',
theme_h3 : '标题 3',
theme_h4 : '标题 4',
theme_h5 : '标题 5',
theme_h6 : '标题 6',
theme_colorpicker_title : '选择颜色',
theme_colorpicker_apply : '应用',
theme_forecolor_desc : '选择文字颜色',
theme_backcolor_desc : '选择背景颜色',
theme_charmap_title : '选择特殊符号',
theme_charmap_desc : '插入特殊符号',
theme_visualaid_desc : '开关不可见元素',
insert_anchor_title : '插入/编辑 锚点',
insert_anchor_name : '锚点名称',
theme_anchor_desc : '插入/编辑 锚点',
theme_insert_link_titlefield : '标题',
theme_clipboard_msg : '剪切/复制/粘贴功能在Mozilla和Firefox上尚不可用。\n你想了解关于这个问题的更多信息吗？',
theme_path : '路径',
cut_desc : '剪切',
copy_desc : '复制',
paste_desc : '粘贴',
link_list : '链接列表',
image_list : '图像列表',
browse : '浏览',
image_props_desc : '图像属性',
newdocument_desc : '新建文档',
class_name : '类',
newdocument : 'Are you sure you want clear all contents?'
});
